/* ArcheAxis Knowledge v3: real desktop workbench layer.
   It intentionally runs after the legacy mock surface and keeps every
   interface UNBOUND. The shared adapter is not called with real endpoints. */
(function () {
  const routes = {
    'workspace-overview':['workspace','工作台总览','继续当前研究、处理待复核事项，并查看每一次操作的回执。'],
    'universal-intake':['workspace','通用摄取','先检查原件与转换计划，再决定是否建立派生产物。'],
    'library-browser':['library','资料库','原件、派生文档和知识版本保持分离，并可回到来源锚点。'],
    'multi-format-reader':['library','多格式阅读器','原件阅读、派生文本和证据锚点在同一任务面中协作。'],
    'evidence-workbench':['evidence','Claim–Evidence 工作台','记录来源关系、适用范围与冲突，不用单一百分比替代人工判断。'],
    'evidence-review-queue':['evidence','证据复核队列','待决事项清楚展示，冲突被保留而不是自动覆盖。'],
    'knowledge-canvas':['library','知识 Canvas','以结构关系浏览知识对象，同时提供列表等价视图。'],
    'learning-home':['learning','学习主页','从有来源的知识版本进入理解、练习、复习与迁移。'],
    'focus-review-session':['learning','专注复习','先记录回答，再揭示证据与边界。'],
    'teachback-transfer':['learning','Teach Back · 未来蓝图','界面与接口已预留，当前不可执行。'],
    'ai-asset-registry':['assets','AI 资产注册表','只有经过治理的证据束可以支持可复用资产。'],
    'ai-asset-detail':['assets','AI 资产详情','版本、作用域、证据束、评测与撤销记录保持可追溯。'],
    'jobs-receipts':['workspace','任务与回执','失败不覆盖原件，尝试、产物与差异都保留在可读回执中。'],
    'settings-capabilities':['settings','设置与能力矩阵','本地优先、权限边界、适配器与真实能力状态在此清楚呈现。'],
    'visual-lesson-studio':['learning','动态视觉课件 · 未来蓝图','仅保留场景、时间轴和证据脚注接口。'],
    'spatial-memory':['learning','空间记忆 · 未来蓝图','提供 2D 地图与低动效替代设计。']
  };
  const spaces = {
    workspace:['工作台',['workspace-overview','universal-intake','jobs-receipts']],
    library:['资料库',['library-browser','multi-format-reader','knowledge-canvas']],
    evidence:['证据',['evidence-workbench','evidence-review-queue']],
    learning:['学习',['learning-home','focus-review-session','teachback-transfer','visual-lesson-studio','spatial-memory']],
    assets:['AI 资产',['ai-asset-registry','ai-asset-detail']],
    settings:['设置',['settings-capabilities']]
  };
  const icons = {
    workspace:'<svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M4 5h16v14H4zM4 10h16M9 10v9"/></svg>',
    library:'<svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M4 4h12l4 4v12H4zM8 13h8M8 17h5"/></svg>',
    evidence:'<svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="m6 3 12 9-12 9V3Z"/></svg>',
    learning:'<svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M4 6.5 12 3l8 3.5-8 3-8-3Zm3 4.8v4.3c3 1.8 7 1.8 10 0v-4.3"/></svg>',
    assets:'<svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M12 3 20 7.5v9L12 21l-8-4.5v-9L12 3Zm0 5v8m-4-6 8 4"/></svg>',
    settings:'<svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8Zm0-5v2m0 14v2M21 12h-2M5 12H3"/></svg>'
  };
  const link = id => `${id}.html`;
  const planned = id => ['teachback-transfer','visual-lesson-studio','spatial-memory'].includes(id);
  const badge = (kind,label) => `<span class="state-tag ${kind}">${label}</span>`;

  function inspector(route) {
    const current = route==='multi-format-reader' ? ['锚点上下文','示例资料 A · 第 7 页','原件页 P07 · 区块 B03','Claim C-01','事实核验待复核；识别质量尚未采集。']
      : route==='evidence-workbench' ? ['证据检查器','Claim C-01','支持与反驳关系并存；不自动覆盖。','EvidenceBundle B-01','尚未批准，不能进入知识或 AI 资产。']
      : route==='knowledge-canvas' ? ['节点上下文','Claim C-01','当前节点提供列表等价访问。','定位锚点','示例资料 A · 第 7 页 · P07-B03']
      : ['当前上下文','示例资料 A','公开演示 fixture；不读取用户资料。','接口状态','UNBOUND · Mock Adapter'];
    return `<div class="inspector-top"><div><span class="eyebrow">${current[0]}</span><h2>${current[1]}</h2></div><button class="icon-btn inspector-close" id="inspector-toggle" aria-label="折叠上下文检查器">›</button></div>
      <div class="inspector-tabs" role="tablist"><button class="active" role="tab" aria-selected="true" data-inspector-tab="evidence">证据</button><button role="tab" aria-selected="false" data-inspector-tab="context">上下文</button><button role="tab" aria-selected="false" data-inspector-tab="activity">回执</button></div>
      <section class="inspector-panel" data-inspector-panel="evidence"><div class="inspector-object"><span>当前对象</span><strong>${current[1]}</strong><p>${current[2]}</p></div><div class="inspector-list"><div><b>${current[3]}</b><span>${current[4]}</span></div><div><b>接口状态</b><span>UNBOUND · Mock Adapter</span></div></div><button class="text-action" data-anchor>定位到关联锚点</button></section>
      <section class="inspector-panel" data-inspector-panel="context" hidden><div class="inspector-list"><div><b>来源</b><span>演示 fixture；未读取个人目录。</span></div><div><b>权限</b><span>未请求联网、上传或写入授权。</span></div><div><b>版本</b><span>原件不可变；派生产物可重建。</span></div></div></section>
      <section class="inspector-panel" data-inspector-panel="activity" hidden><div class="receipt-card"><b>转换任务 J-02</b><span>已中断 · 草稿已保留</span><p>原件保持不变。真实 Adapter 绑定后可从中断处重试。</p></div><div class="receipt-card"><b>公开核验</b><span>未知 · 未发起网络请求</span><p>离线状态下仍可保留本地阅读与学习路径。</p></div></section>`;
  }

  function shell(route) {
    const [space] = routes[route] || routes['workspace-overview'];
    const rail = Object.entries(spaces).map(([id,[label,ids]]) => `<a class="rail-link ${id===space?'active':''}" href="${link(ids[0])}" aria-label="${label}">${icons[id]}<span>${label}</span></a>`).join('');
    const sub = spaces[space][1].map(id => `<a class="sub-link ${id===route?'active':''}" href="${link(id)}"><span>${routes[id][1]}</span>${planned(id)?'<span class="tiny">蓝图</span>':''}</a>`).join('');
    const tabs = Object.entries(spaces).map(([id,[label,ids]]) => `<a class="${id===space?'active':''}" href="${link(ids[0])}">${label}</a>`).join('');
    return `<div class="shell real-shell"><header class="topbar" data-od-id="product-title-bar"><a class="brand" href="workspace-overview.html" aria-label="星环知识平台首页"><span class="mark" aria-hidden="true"></span><span><b>星环知识平台</b><small>ArcheAxis Knowledge</small></span></a><span class="context">个人研究项目 · 本地优先</span><label class="search" data-od-id="global-search"><span>⌕</span><input id="command-search" aria-label="搜索资料、Claim 或命令" placeholder="搜索资料、Claim 或命令"><kbd>Ctrl K</kbd></label><div class="top-actions"><button class="icon-btn" id="density" aria-label="切换紧凑密度">≡</button><button class="icon-btn" id="theme" aria-label="切换浅深色">◐</button></div></header><nav class="mobile-tabs" aria-label="移动一级导航">${tabs}</nav><div class="body-grid"><nav class="rail" aria-label="一级导航" data-od-id="primary-space-rail">${rail}</nav><aside class="subnav" data-od-id="context-subnav"><div class="subnav-heading"><span class="eyebrow">当前空间</span><h2>${spaces[space][0]}</h2></div>${sub}<div class="subnav-foot"><span class="eyebrow">数据边界</span><p>此界面只使用 Mock Adapter；不读取真实资料。</p></div></aside><main class="main" id="task-surface"><div class="content" id="app"></div></main><aside class="inspector" data-od-id="context-evidence-inspector">${inspector(route)}</aside></div><footer class="dock" data-od-id="activity-receipt-dock"><button id="dock-toggle" class="dock-summary" aria-expanded="false"><span class="dot"></span><span>活动与回执</span><span class="dock-copy">本地工作区 · 无真实任务正在运行</span><span aria-hidden="true">⌃</span></button><div class="dock-detail" hidden><div><b>任务 J-02</b><span>转换中断；原件安全，草稿已保留。</span></div><a href="jobs-receipts.html">查看任务与回执</a></div></footer></div>`;
  }

  function head(route) {
    const [,title,description] = routes[route] || routes['workspace-overview'];
    return `<header class="task-head" data-od-id="${route}-heading"><div><p class="eyebrow">${route==='workspace-overview'?'ArcheAxis Learning Workspace':title}</p><h1>${title}</h1><p>${description}</p></div><div class="fixture-mark">演示数据 · MOCK ADAPTER</div></header>`;
  }

  function overview() { return `<section class="workbench-hero" data-od-id="workspace-research-ledger"><div class="hero-ledger"><div><span class="eyebrow">继续研究 · 当前上下文</span><h2>把原件、主张与证据，留在同一个可审查的工作面。</h2><p>示例资料 A 尚未形成可批准的 EvidenceBundle。界面展示可追溯关系，不用进度或可信度数字代替人工判断。</p></div><div class="flow-line" aria-label="证据链"><span>原件</span><i>→</i><span>转换块</span><i>→</i><span>Claim</span><i>→</i><span>Evidence</span></div><a class="button primary" data-od-id="open-reader-cta" href="multi-format-reader.html">继续阅读与复核</a></div><aside class="next-actions"><div class="eyebrow">下一步</div><button class="next-action" data-go="multi-format-reader"><span>01</span><b>检查第 7 页锚点</b><small>Claim C-01 已定位，等待补充范围。</small></button><button class="next-action" data-go="evidence-workbench"><span>02</span><b>记录证据冲突</b><small>支持与反驳保持并列，不自动覆盖。</small></button><button class="next-action" data-go="jobs-receipts"><span>03</span><b>处理转换中断</b><small>草稿已保留；原件保持不变。</small></button></aside></section><section class="workspace-columns"><article class="surface-panel research-list" data-od-id="workspace-current-research"><header><div><span class="eyebrow">研究台账</span><h2>当前对象</h2></div><a class="text-action" href="library-browser.html">查看全部资料</a></header><div class="object-row selected"><span class="object-kind">原件</span><div><b>示例资料 A</b><small>公开演示 fixture · 页码 1–12 · 不可变</small></div><a class="anchor" href="multi-format-reader.html">打开</a></div><div class="object-row"><span class="object-kind">派生</span><div><b>转换文本 v0.2</b><small>结构块 4 待人工检查；不代表事实结论。</small></div>${badge('partial','部分可用')}</div><div class="object-row"><span class="object-kind">Claim</span><div><b>Claim C-01</b><small>适用范围与独立来源尚未采集。</small></div><a class="anchor" href="evidence-workbench.html">复核</a></div></article><article class="surface-panel work-receipts" data-od-id="workspace-receipts"><header><div><span class="eyebrow">活动回执</span><h2>可恢复，不覆盖</h2></div><a class="text-action" href="jobs-receipts.html">所有回执</a></header><div class="receipt-row"><span class="receipt-mark">01</span><div><b>转换任务 J-02 已中断</b><p>原始音频保持不变；0:00–12:42 的转写草稿已保留。</p></div><button class="button" data-go="jobs-receipts">查看恢复选项</button></div><div class="receipt-row"><span class="receipt-mark">02</span><div><b>公开核验未发起</b><p>没有访问外部来源；当前状态显示为未知而非虚构结果。</p></div>${badge('unknown','未知')}</div></article></section>`; }
  function intake() { return `<section class="intake-layout" data-od-id="universal-intake-flow"><article class="surface-panel intake-form"><header><span class="eyebrow">导入入口 · 本地草稿</span><h2>先确认对象与授权，再创建任何派生产物。</h2><p>演示模式不会读取文件、目录或网络资源。真实绑定时，此处应先展示范围与持续时间。</p></header><div class="source-well"><div class="source-glyph">＋</div><b>选择来源</b><span>文件、目录、URL、文本与音视频会按能力状态分别检查。</span><div><button class="button primary" data-message="已选择示例资料 A；未读取任何真实路径。">选择示例资料 A</button><button class="button" data-message="真实授权将说明对象、动作、范围、持续时间与撤销方式。">查看授权范围</button></div></div><div class="intake-steps" aria-label="导入步骤"><button class="active" data-intake-step="0"><span>01</span><b>来源与授权</b><small>未选择真实路径</small></button><button data-intake-step="1"><span>02</span><b>格式与处理计划</b><small>待检查</small></button><button data-intake-step="2"><span>03</span><b>转译质量门控</b><small>与事实核验分开</small></button><button data-intake-step="3"><span>04</span><b>Claim 与人工复核</b><small>仅在派生结果可审查后</small></button></div></article><aside class="surface-panel intake-explain"><span class="eyebrow">当前步骤</span><h2 id="intake-title">来源与授权</h2><p id="intake-copy">明确要读取的对象、动作、范围、持续时间和撤销方式。当前没有真实选择，因此不显示路径或权限结果。</p><div class="boundary-note"><b>原件安全</b><span>任何转换失败都不能修改原件；重试只会创建新的派生版本。</span></div></aside></section>`; }
  function browser() { return `<section class="library-layout" data-od-id="library-browser"><header class="library-toolbar"><div><span class="eyebrow">Open Vault Workbench</span><h2>资料库不是文件堆，而是一组可回溯的对象关系。</h2></div><div class="view-switch" role="group" aria-label="资料视图"><button class="active">列表</button><button>集合</button><button>表格</button></div></header><div class="library-split"><aside class="collection-tree"><span class="eyebrow">集合</span><button class="active">全部资料 <small>演示</small></button><button>最近打开</button><button>待复核</button><button>原件</button><button>派生产物</button><div class="tree-hint">真实 Vault 兼容入口在 Adapter 绑定后出现；不以第三方品牌命名。</div></aside><section class="source-table"><div class="table-caption"><span>3 个演示对象</span><button class="text-action">筛选状态</button></div><div class="source-head"><span>对象</span><span>来源与锚点</span><span>治理状态</span><span></span></div><a class="source-line selected" href="multi-format-reader.html"><span class="file-mark">原</span><span><b>示例资料 A</b><small>原件 · 公开演示 fixture</small></span><span><b>第 1–12 页</b><small>版本：不可变</small></span>${badge('unknown','未知')}<span>›</span></a><div class="source-line"><span class="file-mark derivative">派</span><span><b>示例资料 A · 转换文本</b><small>派生文档 · v0.2</small></span><span><b>来源 P07-B03</b><small>损失报告：尚未采集</small></span>${badge('partial','部分可用')}<span>›</span></div><a class="source-line" href="evidence-workbench.html"><span class="file-mark claim">C</span><span><b>Claim C-01</b><small>可核验陈述</small></span><span><b>示例资料 A · 第 7 页</b><small>适用范围：尚不明确</small></span>${badge('pending','待复核')}<span>›</span></a></section></div></section>`; }
  function reader() { return `<section class="reader-workbench" data-od-id="reader-workbench"><aside class="reader-outline"><div class="reader-object"><span class="eyebrow">当前原件</span><b>示例资料 A</b><small>公开演示 fixture · 原件不可变</small></div><nav aria-label="原件结构"><button>封面与来源 <span>01</span></button><button>转换上下文 <span>06</span></button><button class="active" data-anchor>Claim 锚点 <span>07</span></button><button>术语边界 <span>08</span></button></nav><div class="reader-tools"><button class="button">原件</button><button class="button">转换文本</button><button class="button">并排差异</button></div></aside><article class="source-paper" data-od-id="original-reader"><header><span>示例资料 A · 原件</span><span>第 7 页 / 12</span></header><div class="paper-copy"><p class="paper-kicker">P07 · B03 · 原始位置锚点</p><h2>可核验的知识对象，必须能回到它所依据的原始位置。</h2><p>原件、转换块、Claim 与 Evidence 是不同对象。阅读面保留页码、版本与位置，使后续复核能回到同一份材料的同一处上下文。</p><blockquote id="target">“识别转译质量描述派生产物是否忠实；内容事实核验则审查主张与独立、适用、及时的来源之间的关系。”<cite>示例 Claim C-01</cite></blockquote><p>重新转换、换引擎或人工纠错只新增派生版本，不会改写原件。任何差异均可被比较、说明与撤销。</p></div><footer><button class="anchor" data-anchor>锚点 P07 · B03</button><span>转译质量：尚未采集 · 事实核验：待复核</span></footer></article></section>`; }
  function workbench() { return `<section class="evidence-workbench" data-od-id="claim-evidence-workbench"><article class="claim-sheet" data-od-id="claim-record"><header><span class="eyebrow">可核验陈述 · Claim C-01</span>${badge('pending','待复核')}</header><h2>“识别转译质量不能直接代表内容的事实核验结论。”</h2><div class="claim-meta"><div><b>来源锚点</b><button class="anchor" data-anchor>示例资料 A · 第 7 页 · P07-B03</button></div><div><b>核验边界</b><span>公开可核验 · 演示 fixture</span></div><div><b>人工结论</b><span>尚未记录</span></div></div><div class="claim-actions"><button class="button" data-message="已记录演示中的冲突处理意图；真实决定需要 Adapter 回执。">记录冲突</button><button class="button primary" data-message="已创建演示中的补充证据请求；未写入真实任务。">请求补充证据</button></div></article><section class="evidence-ledger" data-od-id="evidence-relationship-ledger"><header><div><span class="eyebrow">Evidence Links</span><h2>支持、反驳与背景并列保留</h2></div><button class="text-action">关系说明</button></header><div class="evidence-head"><span>立场</span><span>来源与锚点</span><span>范围 / 决定</span></div><button class="evidence-row active" data-evidence="support"><span class="stance support">支持</span><span><b>Evidence E-01</b><small>示例来源关系 · 第 2 节</small></span><span>独立性：尚未采集</span></button><button class="evidence-row" data-evidence="conflict"><span class="stance conflict">反驳</span><span><b>Evidence E-02</b><small>冲突关系 · 待人工审阅</small></span><span>结论：不自动覆盖</span></button><button class="evidence-row" data-evidence="context"><span class="stance context">背景</span><span><b>Evidence E-03</b><small>术语边界 · 非直接结论</small></span><span>适用范围：尚不明确</span></button><footer id="evidence-detail"><b>Evidence E-01 · 支持</b><p>演示条目只体现关系结构；权威性、时效与适用范围不以伪评分代替。</p></footer></section></section>`; }
  function review() { return `<section class="review-desk" data-od-id="evidence-review-queue"><header><div><span class="eyebrow">证据复核队列</span><h2>需要人做决定的地方，才进入队列。</h2></div><span class="fixture-mark">演示队列 · 不显示伪排序分数</span></header><div class="review-line">${badge('conflict','存在冲突')}<div><b>Claim C-01</b><p>支持与反驳关系已记录；仍缺少适用范围与独立来源信息。</p></div><a class="button" href="evidence-workbench.html">打开工作台</a></div><div class="review-line">${badge('partial','证据不足')}<div><b>EvidenceBundle B-01</b><p>未形成可批准的结论；不能支持知识版本或 AI 资产。</p></div><button class="button" data-message="已创建演示中的补充证据请求；未写入真实任务。">请求补充证据</button></div></section>`; }
  function canvas() { return `<section class="canvas-workbench" data-od-id="knowledge-canvas"><header class="canvas-toolbar"><div><span class="eyebrow">关系图 · 列表等价可用</span><h2>关系视图不替代对象与锚点。</h2></div><div><button class="button" id="canvas-list-toggle">显示列表</button><button class="button">缩放 100%</button></div></header><div class="relation-canvas" role="group" aria-label="Claim 与证据关系图"><span class="canvas-edge edge-a"></span><span class="canvas-edge edge-b"></span><span class="canvas-edge edge-c"></span><button class="canvas-node claim active" data-node="claim"><b>Claim C-01</b><small>待复核</small></button><button class="canvas-node support" data-node="support"><b>Evidence E-01</b><small>支持</small></button><button class="canvas-node conflict" data-node="conflict"><b>Evidence E-02</b><small>反驳</small></button><button class="canvas-node bundle" data-node="bundle"><b>Bundle B-01</b><small>尚未批准</small></button></div><div class="canvas-list" id="canvas-list" hidden><div><b>Claim C-01</b><span>连接 Evidence E-01（支持）、E-02（反驳）与 Bundle B-01（待复核）。</span><button class="anchor" data-anchor>第 7 页</button></div></div><footer class="canvas-caption">节点状态同时有文字、形状与列表说明；选择节点只突出一跳关系。</footer></section>`; }
  function learning() { return `<section class="learning-desk" data-od-id="learning-route"><article><span class="eyebrow">示例学习路线 · 证据驱动</span><h2>理解、检索、复习与迁移</h2><p>学习步骤从知识版本与 EvidenceBundle 出发；完成记录不是掌握度预测。</p><ol class="learning-steps"><li class="done"><span>01</span><div><b>理解对象边界</b><small>原件、派生产物与 Claim 的差别。</small></div><em>已完成演示步骤</em></li><li class="current"><span>02</span><div><b>检索 Claim 边界</b><small>下一次复习区间：—（尚未计算）</small></div><a href="focus-review-session.html">开始</a></li><li><span>03</span><div><b>Teach Back 与迁移</b><small>未来蓝图；当前不可执行。</small></div><em>PLANNED</em></li></ol></article><aside><span class="eyebrow">学习依据</span><h2>每个回答都能回到依据。</h2><div class="evidence-spine"><span>知识版本</span><i></i><span>学习项目</span><i></i><span>人工复核</span></div><p>EvidenceBundle B-01 尚未批准；页面只展示合同结构，不暗示学习材料已被真实治理。</p></aside></section>`; }
  function session() { return `<section class="focus-desk" data-od-id="focus-review-session"><header><span class="eyebrow">示例学习路线 · 第 02 步</span><span class="fixture-mark">演示输入不写入真实记录</span></header><div class="focus-question"><p>请先用自己的话回答：</p><h2>为什么“识别转译质量”不能直接代表内容的事实核验结论？</h2></div><textarea class="editor" aria-label="记录你的回答" placeholder="输入你的理解；演示模式不会写入真实学习记录。"></textarea><footer><span><kbd>1</kbd> 再次 <kbd>2</kbd> 困难 <kbd>3</kbd> 良好 <kbd>4</kbd> 轻松</span><div><button class="button" data-anchor>查看原件锚点</button><button class="button primary" id="reveal">查看证据与差异</button></div></footer><aside id="reveal-box" class="reveal-sheet" hidden><b>EvidenceBundle B-01</b><p>识别转译衡量派生产物忠实度；事实核验需要查看 Claim 与来源支持、独立性、时效及适用范围。</p><button class="anchor" data-anchor>定位到第 7 页</button></aside></section>`; }
  function assetRegistry() { return `<section class="library-layout" data-od-id="ai-asset-registry"><header class="library-toolbar"><div><span class="eyebrow">AI Asset Registry</span><h2>只有经过治理的证据束，才能注册为可复用资产。</h2></div><button class="button primary" data-message="演示模式不创建资产；真实创建需要 EvidenceBundle 批准与授权回执。">注册新资产</button></header><div class="library-split"><aside class="collection-tree"><span class="eyebrow">治理筛选</span><button class="active">全部资产 <small>演示</small></button><button>已注册</button><button>草稿</button><button>已撤销</button><div class="tree-hint">每个资产必须绑定批准的 EvidenceBundle；未批准 Bundle 不能进入注册流程。</div></aside><section class="source-table"><div class="table-caption"><span>2 个演示资产</span><button class="text-action">按 Bundle 筛选</button></div><div class="source-head"><span>资产</span><span>作用域 / 版本</span><span>治理状态</span><span></span></div><a class="source-line" href="ai-asset-detail.html"><span class="file-mark claim">A</span><span><b>AA-01 · 示例可复用结论</b><small>Bundle B-01 · v1.0-draft</small></span><span><b>局部作用域</b><small>公开演示 fixture</small></span>${badge('pending','待批准')}<span>›</span></a><div class="source-line"><span class="file-mark derivative">R</span><span><b>AA-02 · 已撤销旧版本</b><small>Bundle B-00 · v0.9</small></span><span><b>已撤销</b><small>撤销记录保留</small></span>${badge('conflict','已撤销')}<span>›</span></div></section></div></section>`; }
  function assetDetail() { return `<section class="evidence-workbench" data-od-id="ai-asset-detail"><article class="claim-sheet"><header><span class="eyebrow">AI 资产 · AA-01</span>${badge('pending','待批准')}</header><h2>“示例可复用结论，绑定 EvidenceBundle B-01。”</h2><div class="claim-meta"><div><b>作用域</b><span>局部作用域 · 仅限当前研究项目</span></div><div><b>版本与签名</b><span>v1.0-draft · 尚未签名</span></div><div><b>撤销记录</b><span>无 · 该资产未撤销过</span></div></div><div class="claim-actions"><button class="button" data-message="演示模式不生成评测报告；真实报告由 Adapter 回执提供。">查看评测</button><a class="button primary" href="evidence-workbench.html">查看 EvidenceBundle</a></div></article><section class="evidence-ledger"><header><div><span class="eyebrow">依赖与使用链</span><h2>资产必须能回到批准的证据束</h2></div><button class="text-action">版本差异</button></header><div class="evidence-head"><span>类型</span><span>对象与锚点</span><span>状态</span></div><button class="evidence-row active"><span class="stance support">依赖</span><span><b>EvidenceBundle B-01</b><small>未批准 · Claim C-01</small></span><span>阻塞注册</span></button><button class="evidence-row"><span class="stance context">使用</span><span><b>示例学习路线</b><small>第 02 步 · 边界检索</small></span><span>草稿引用</span></button><button class="evidence-row"><span class="stance context">撤销</span><span><b>撤销记录</b><small>AA-02 · v0.9 → 过时</small></span><span>已保留</span></button><footer id="evidence-detail"><b>EvidenceBundle B-01</b><p>该 Bundle 尚未批准；资产注册被阻塞。真实注册会要求 Bundle 批准回执与明确作用域授权。</p></footer></section></section>`; }
  function jobsReceipts() { return `<section class="review-desk" data-od-id="jobs-receipts"><header><div><span class="eyebrow">任务与回执</span><h2>失败不覆盖原件；每次尝试都有可读回执。</h2></div><span class="fixture-mark">演示任务 · 不运行真实进程</span></header><div class="review-line">${badge('conflict','已中断')}<div><b>转换任务 J-02</b><p>示例资料 A 的转换在处理第 7 页时中断。原件保持不变，草稿 v0.2 已保留。</p></div><button class="button" data-message="演示模式不重试；真实重试会创建新的派生版本并写入回执。">重试</button></div><div class="review-line">${badge('partial','部分完成')}<div><b>转译质量评估 J-01</b><p>已完成 8/12 页；损失报告待人工检查。未发起事实核验。</p></div><button class="button" data-message="演示模式不打开报告；真实报告会指向具体页码与块位置。">查看报告</button></div><div class="review-line">${badge('unknown','未开始')}<div><b>事实核验任务 J-03</b><p>等待 EvidenceBundle 批准；当前未查询任何网络来源。</p></div><button class="button" data-message="演示模式不会排队真实任务；真实任务需要 Adapter 能力状态可用。">排队</button></div></section>`; }
  function settingsCapabilities() { return `<section class="learning-desk" data-od-id="settings-capabilities"><article><span class="eyebrow">本地优先 · 能力矩阵</span><h2>权限、适配器与真实能力状态</h2><p>设置页只展示当前环境可确认的能力；不假设云端功能可用。</p><ol class="learning-steps"><li class="done"><span>01</span><div><b>本地数据边界</b><small>未请求上传、联网或写入真实目录。</small></div><em>已启用</em></li><li class="current"><span>02</span><div><b>适配器状态</b><small>Mock Adapter · 所有端点 UNBOUND。</small></div><button class="text-action" data-message="演示模式不会切换 Adapter；真实绑定需要显式授权。">查看合同</button></li><li><span>03</span><div><b>可选能力</b><small>OCR / ASR / 网络核验 / 视觉课件 · 未来检测。</small></div><em>未启用</em></li></ol></article><aside><span class="eyebrow">能力清单</span><h2>当前仅启用前端界面能力。</h2><div class="evidence-spine"><span>本地读取</span><i></i><span>Mock Adapter</span><i></i><span>界面渲染</span></div><p>其他能力（视觉课件、空间记忆、Teach Back）标记为未来蓝图；在能力状态可检测前保持不可执行。</p></aside></section>`; }
  function blueprint(route) { return `<section class="review-desk planned-screen" data-od-id="${route}-blueprint"><header><div><span class="eyebrow">未来蓝图 · 接口预留</span><h2>${routes[route][1]}</h2></div>${badge('unknown','PLANNED')}</header><div class="review-line"><div><b>界面与接口已预留</b><p>${routes[route][2]} 当前不可执行；保留相关入口以保持导航完整。</p></div></div></section>`; }
  function legacy(route) { return typeof window.main === 'function' ? window.main(route) : `<section class="review-desk"><header><div><span class="eyebrow">可编辑界面</span><h2>${routes[route][1]}</h2></div></header><div class="review-line"><div><b>当前页面保留</b><p>该页面的 Mock Adapter 合同已存在；本轮重点重构研究工作流核心页面。</p></div></div></section>`; }
  function content(route) { const core = {'workspace-overview':overview,'universal-intake':intake,'library-browser':browser,'multi-format-reader':reader,'evidence-workbench':workbench,'evidence-review-queue':review,'knowledge-canvas':canvas,'learning-home':learning,'focus-review-session':session,'ai-asset-registry':assetRegistry,'ai-asset-detail':assetDetail,'jobs-receipts':jobsReceipts,'settings-capabilities':settingsCapabilities,'teachback-transfer':blueprint,'visual-lesson-studio':blueprint,'spatial-memory':blueprint}; return head(route) + (core[route] ? core[route](route) : legacy(route)); }
  function announce(message) { let notice=document.querySelector('#ui-notice'); if (!notice) { notice=document.createElement('div'); notice.id='ui-notice'; notice.className='ui-notice'; notice.setAttribute('role','status'); document.body.appendChild(notice); } notice.textContent=message; notice.classList.add('show'); window.setTimeout(()=>notice.classList.remove('show'),2800); }
  function bind(route) {
    const root = document.documentElement;
    try { root.dataset.theme=localStorage.getItem('archeaxis-theme')||'light'; document.body.classList.toggle('compact',localStorage.getItem('archeaxis-density')==='compact'); } catch (_) { root.dataset.theme='light'; }
    document.querySelector('#theme').addEventListener('click',()=>{root.dataset.theme=root.dataset.theme==='dark'?'light':'dark';try{localStorage.setItem('archeaxis-theme',root.dataset.theme)}catch(_){}});
    document.querySelector('#density').addEventListener('click',()=>{document.body.classList.toggle('compact');try{localStorage.setItem('archeaxis-density',document.body.classList.contains('compact')?'compact':'full')}catch(_){}});
    document.querySelector('#dock-toggle').addEventListener('click',event=>{const detail=document.querySelector('.dock-detail'),expanded=detail.hidden;detail.hidden=!expanded;event.currentTarget.setAttribute('aria-expanded',String(expanded));});
    document.querySelector('#inspector-toggle').addEventListener('click',()=>document.body.classList.toggle('inspector-collapsed'));
    document.querySelectorAll('[data-inspector-tab]').forEach(tab=>tab.addEventListener('click',()=>{document.querySelectorAll('[data-inspector-tab]').forEach(item=>{const selected=item===tab;item.classList.toggle('active',selected);item.setAttribute('aria-selected',String(selected));});document.querySelectorAll('[data-inspector-panel]').forEach(panel=>panel.hidden=panel.dataset.inspectorPanel!==tab.dataset.inspectorTab); }));
    document.querySelectorAll('[data-anchor]').forEach(button=>button.addEventListener('click',()=>{const target=document.querySelector('#target'),surface=document.querySelector('#task-surface');if(target&&surface){surface.scrollTo({top:Math.max(0,target.offsetTop-96),behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});target.classList.add('anchor-flash');window.setTimeout(()=>target.classList.remove('anchor-flash'),1800);}else{announce('该页已保留锚点合同；请在阅读器中查看原件第 7 页。');}}));
    document.querySelectorAll('[data-go]').forEach(button=>button.addEventListener('click',()=>{location.href=link(button.dataset.go);}));
    document.querySelectorAll('[data-message]').forEach(button=>button.addEventListener('click',()=>announce(button.dataset.message)));
    const steps=[['来源与授权','明确要读取的对象、动作、范围、持续时间和撤销方式。当前没有真实选择，因此不显示路径或权限结果。'],['格式与处理计划','先识别格式、可用转换路径和潜在损失；计划必须在创建派生产物前可审查。'],['转译质量门控','评估 OCR、ASR 或解析产物的忠实度；这与事实核验完全分开。'],['Claim 与人工复核','派生产物可审查后才提出 Claim 候选；冲突和未知进入人工复核。']];
    document.querySelectorAll('[data-intake-step]').forEach(button=>button.addEventListener('click',()=>{const [title,copy]=steps[Number(button.dataset.intakeStep)];document.querySelectorAll('[data-intake-step]').forEach(item=>item.classList.toggle('active',item===button));document.querySelector('#intake-title').textContent=title;document.querySelector('#intake-copy').textContent=copy;}));
    const evidence={support:['Evidence E-01 · 支持','演示条目只体现关系结构；权威性、时效与适用范围不以伪评分代替。'],conflict:['Evidence E-02 · 反驳','冲突关系保持可见，等待人工理由；不会覆盖原始 Claim。'],context:['Evidence E-03 · 背景','背景帮助解释术语边界，但不替代直接结论。']};
    document.querySelectorAll('[data-evidence]').forEach(row=>row.addEventListener('click',()=>{const copy=evidence[row.dataset.evidence];document.querySelectorAll('[data-evidence]').forEach(item=>item.classList.toggle('active',item===row));document.querySelector('#evidence-detail').innerHTML=`<b>${copy[0]}</b><p>${copy[1]}</p>`;}));
    document.querySelectorAll('[data-node]').forEach(node=>node.addEventListener('click',()=>{document.querySelectorAll('[data-node]').forEach(item=>item.classList.toggle('active',item===node));announce(`${node.textContent.trim()} 已选中；关联关系已在列表等价视图中保留。`);}));
    document.querySelector('#canvas-list-toggle')?.addEventListener('click',event=>{const list=document.querySelector('#canvas-list');list.hidden=!list.hidden;event.currentTarget.textContent=list.hidden?'显示列表':'隐藏列表';});
    document.querySelector('#reveal')?.addEventListener('click',()=>{document.querySelector('#reveal-box').hidden=false;});
    document.querySelector('#command-search').addEventListener('keydown',event=>{if(event.key==='Enter'){event.preventDefault();announce('演示搜索不会查询真实资料；可用关键词：资料、Claim、证据、回执。');}});
  }
  function init() { const route=location.hash ? location.hash.slice(1) : (document.body.dataset.route||'workspace-overview'); document.body.dataset.route=route; document.body.innerHTML=shell(route); document.querySelector('#app').innerHTML=content(route); bind(route); window.scrollTo(0,0); }
  window.addEventListener('DOMContentLoaded',init);
  window.addEventListener('hashchange',init);
})();
