"""Generate authored-expression DTOs from the bounded immutable-reference contract."""
import argparse
import json
from pathlib import Path
ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "packages/contracts/v2/expression.schema.json"
TARGET = ROOT / "frontend/src/api/generated/expression-contract.ts"
def ts(node):
    if "$ref" in node:
        return node["$ref"].split("/")[-1]
    if "const" in node:
        return json.dumps(node["const"])
    if "enum" in node:
        return " | ".join(json.dumps(value) for value in node["enum"])
    if "anyOf" in node:
        return " | ".join(ts(value) for value in node["anyOf"])
    kind=node.get("type")
    if isinstance(kind,list):
        return " | ".join(ts({"type":value}) for value in kind)
    if kind=="object":
        props=node.get("properties",{})
        if not props:
            return "Record<string, " + ts(node["additionalProperties"]) + ">" if isinstance(node.get("additionalProperties"),dict) else "Record<string, unknown>"
        required=node.get("required",[])
        return "{ " + "; ".join(f'{key}{"" if key in required else "?"}: {ts(value)}' for key,value in props.items()) + " }"
    if kind=="array":
        return f"Array<{ts(node.get('items',{}))}>"
    return {"string":"string","integer":"number","number":"number","boolean":"boolean","null":"null"}.get(kind,"unknown")
def generate(source=SOURCE,target=TARGET,check=False):
    schema=json.loads(source.read_text(encoding="utf-8"))
    result="// Generated by scripts/contracts/generate_expression_contract.py. Edit the JSON Schema.\n"
    result+="\n".join(f"export type {name} = {ts(node)};" for name,node in schema["$defs"].items())+"\n"
    if check:
        return target.exists() and target.read_text(encoding="utf-8")==result
    target.parent.mkdir(parents=True,exist_ok=True)
    target.write_text(result,encoding="utf-8",newline="\n")
    return True
if __name__=="__main__":
    parser=argparse.ArgumentParser();parser.add_argument("--schema",type=Path,default=SOURCE);parser.add_argument("--target",type=Path,default=TARGET);parser.add_argument("--check",action="store_true");args=parser.parse_args()
    raise SystemExit(0 if generate(args.schema,args.target,args.check) else 1)
