"""Generate research/relations DTOs from the immutable-reference metadata schema."""

import argparse
import json
from pathlib import Path

from generate_expression_contract import ts

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "packages/contracts/v2/research.schema.json"
TARGET = ROOT / "frontend/src/api/generated/research-contract.ts"


def generate(check=False):
    schema = json.loads(SOURCE.read_text(encoding="utf-8"))
    result = (
        "// Generated by scripts/contracts/generate_research_contract.py. Edit the JSON Schema.\n"
    )
    result += (
        "\n".join(f"export type {name} = {ts(node)};" for name, node in schema["$defs"].items())
        + "\n"
    )
    if check:
        return TARGET.exists() and TARGET.read_text(encoding="utf-8") == result
    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(result, encoding="utf-8", newline="\n")
    return True


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    raise SystemExit(0 if generate(parser.parse_args().check) else 1)
