"""Generate collection DTOs and bounded shape assertion from the single schema."""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "packages/contracts/v2/collection.schema.json"
TARGET = ROOT / "frontend/src/api/generated/collection-contract.ts"


def ts(n):
    if "$ref" in n:
        return n["$ref"].split("/")[-1]
    if "const" in n:
        return json.dumps(n["const"])
    if "enum" in n:
        return " | ".join(json.dumps(x) for x in n["enum"])
    if "anyOf" in n:
        return " | ".join(ts(x) for x in n["anyOf"])
    t = n.get("type")
    if t == "array":
        return "Array<" + ts(n["items"]) + ">"
    if t == "object":
        if not n.get("properties") and isinstance(n.get("additionalProperties"), dict):
            return "{ [key: string]: " + ts(n["additionalProperties"]) + " }"
        return (
            "{ "
            + "; ".join(
                k + ("" if k in n.get("required", []) else "?") + ": " + ts(v)
                for k, v in n.get("properties", {}).items()
            )
            + " }"
        )
    return {
        "string": "string",
        "integer": "number",
        "number": "number",
        "boolean": "boolean",
        "null": "null",
    }.get(t, "unknown")


def generate():
    d = json.loads(SOURCE.read_text(encoding="utf-8"))["$defs"]
    out = "// Generated by scripts/contracts/generate_collection.py; edit the schema.\n"
    out += "\n".join("export type " + k + " = " + ts(v) + ";" for k, v in d.items()) + "\n"
    out += "const definitions: Record<string, any> = " + json.dumps(d, ensure_ascii=False) + ";\n"
    out += r"""
function matches(n:any,v:unknown,depth=0):boolean {
 if(depth>64)return false;
 if(n.$ref)return matches(definitions[n.$ref.split('/').pop()],v,depth+1);
 if('const' in n)return v===n.const;
 if(n.enum)return n.enum.includes(v);
 if(n.anyOf)return n.anyOf.some((x:any)=>matches(x,v,depth+1));
 switch(n.type){
 case 'null':return v===null;
 case 'boolean':return typeof v==='boolean';
 case 'number':return typeof v==='number'&&Number.isFinite(v);
 case 'integer':return typeof v==='number'&&Number.isSafeInteger(v);
 case 'string':return typeof v==='string'&&(n.minLength===undefined||v.length>=n.minLength)&&(n.maxLength===undefined||v.length<=n.maxLength)&&(!n.pattern||new RegExp(n.pattern).test(v));
 case 'array':return Array.isArray(v)&&(n.minItems===undefined||v.length>=n.minItems)&&(n.maxItems===undefined||v.length<=n.maxItems)&&v.every(x=>matches(n.items,x,depth+1));
 case 'object':{
  if(!v||typeof v!=='object'||Array.isArray(v))return false;
  const r=v as Record<string,unknown>,p=n.properties||{};
  return (n.required||[]).every((k:string)=>Object.prototype.hasOwnProperty.call(r,k))&&Object.entries(r).every(([k,x])=>k in p?matches(p[k],x,depth+1):n.additionalProperties===false?false:typeof n.additionalProperties==='object'?matches(n.additionalProperties,x,depth+1):true);
 }
 default:return false;
 }
}
export function assertCollectionDto<T>(name:string,value:unknown):T {
 if(!definitions[name]||!matches(definitions[name],value))throw new Error('COLLECTION_DTO_INVALID: '+name);
 return value as T;
}
export function parseCollection(value:unknown):Collection|null {try{return assertCollectionDto<Collection>('Collection',value);}catch{return null;}}
"""
    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(out, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    generate()
