"""Generate vocabulary bindings from the two authoritative Contract v1 schemas.

--check compares exact UTF-8/LF output without writes. --print-json returns a
relative-path/content map for patch-based authoring. Default mode mechanically
regenerates only the three declared files inside the exact Git project root.
"""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import re
import stat
import subprocess


SOURCES = ("assessment-vocabulary.schema.json", "job-status.schema.json")
RUST = "crates/archeaxis-contracts/src/generated/vocabulary.rs"
CSHARP = "apps/ArcheAxis.Desktop/Contracts/Generated/Vocabulary.g.cs"
PYTHON = "services/python-workers/contracts/generated/vocabulary.py"
OUTPUTS = (RUST, CSHARP, PYTHON)
PRIVATE = {".codex", ".dsh", ".hermes", ".openhuman", ".claude", ".agents"}
NOTICE = "Generated by scripts/contracts/generate_vocabulary.py; DO NOT EDIT."


def safe_path(path: Path) -> Path:
    text = os.fspath(path).replace("\\", "/")
    if text.lower().startswith(("e:", "//")):
        raise ValueError("protected drive or UNC path is not permitted")
    path = Path(os.path.abspath(path))
    if any(part.casefold() in PRIVATE for part in path.parts):
        raise ValueError("private agent paths are not permitted")
    for ancestor in (*reversed(path.parents), path):
        try:
            info = ancestor.lstat()
        except FileNotFoundError:
            continue
        if stat.S_ISLNK(info.st_mode) or (
            getattr(info, "st_file_attributes", 0)
            & getattr(stat, "FILE_ATTRIBUTE_REPARSE_POINT", 0x400)
        ):
            raise ValueError(f"linked or reparse path is not permitted: {ancestor}")
    return path


def read_vocabulary(root: Path) -> dict[str, list[str]]:
    result = {}
    for name in SOURCES:
        path = safe_path(root / "packages/contracts/v1" / name)
        schema = json.loads(path.read_text(encoding="utf-8"))
        expected_id = f"https://archeaxis.local/contracts/v1/{name}"
        if schema.get("$id") != expected_id:
            raise ValueError(f"unexpected authority id for {name}")
        for category, definition in schema["$defs"].items():
            values = definition.get("enum")
            if not re.fullmatch(r"[a-z][a-z0-9_]*", category) or category in result:
                raise ValueError(f"invalid or duplicate category: {category}")
            if (not isinstance(values, list) or not values
                    or any(not isinstance(value, str) or not re.fullmatch(r"[A-Za-z][A-Za-z0-9_]*", value) for value in values)
                    or len(set(values)) != len(values)):
                raise ValueError(f"invalid closed string enum: {category}")
            result[category] = values
    return dict(sorted(result.items()))


def render(vocabulary: dict[str, list[str]]) -> dict[str, str]:
    quote = json.dumps
    rust = [f"// {NOTICE}", ""]
    for category, values in vocabulary.items():
        rust.append(f"pub const {category.upper()}_VALUES: &[&str] = &[{', '.join(map(quote, values))}];")
    rust.extend(["", "pub const KNOWLEDGE_TYPES: &[&str] = KNOWLEDGE_TYPE_VALUES;"])
    for category, prefix in (("review_status", "STATUS"), ("job_status", "JOB"), ("research_verdict", "VERDICT")):
        for value in vocabulary[category]:
            rust.append(f"pub const {prefix}_{value.upper()}: &str = {quote(value)};")
    rust.extend(["", "pub fn is_valid(category: &str, value: &str) -> bool {", "    match category {"])
    for category in vocabulary:
        rust.append(f"        {quote(category)} => {category.upper()}_VALUES.contains(&value),")
    rust.extend(["        _ => false,", "    }", "}", "",
                 "pub fn parse_value<'a>(category: &str, value: &'a str) -> Result<&'a str, &'static str> {",
                 '    if is_valid(category, value) { Ok(value) } else { Err("unknown vocabulary category or value") }', "}"])

    csharp = [f"// {NOTICE}", "using System;", "", "namespace ArcheAxis.Desktop.Contracts.Generated;", "",
              "public static class Vocabulary", "{",
              "    public static bool IsValid(string category, string value) => category switch", "    {"]
    for category, values in vocabulary.items():
        csharp.append(f"        {quote(category)} => value is {' or '.join(map(quote, values))},")
    csharp.extend(["        _ => false,", "    };", "",
                   "    public static string Parse(string category, string value)", "    {",
                   '        if (!IsValid(category, value)) throw new ArgumentException("Unknown vocabulary category or value.");',
                   "        return value;", "    }", "}"])

    python = [f"# {NOTICE}", "from types import MappingProxyType", "", "VOCABULARY = MappingProxyType({"]
    for category, values in vocabulary.items():
        python.append(f"    {quote(category)}: ({', '.join(map(quote, values))},),")
    python.extend(["})", "", "", "def is_valid(category, value):",
                   "    return (isinstance(category, str) and isinstance(value, str)",
                   "            and value in VOCABULARY.get(category, ()))", "", "",
                   "def parse_value(category, value):", "    if not is_valid(category, value):",
                   '        raise ValueError("unknown vocabulary category or value")', "    return value"])
    return {RUST: "\n".join(rust) + "\n", CSHARP: "\n".join(csharp) + "\n", PYTHON: "\n".join(python) + "\n"}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).absolute().parents[2])
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--print-json", action="store_true")
    args = parser.parse_args()
    try:
        root = safe_path(args.root)
        result = subprocess.run(["git", "-C", str(root), "rev-parse", "--show-toplevel"],
                                capture_output=True, text=True, encoding="utf-8", check=False)
        if result.returncode or os.path.normcase(os.path.abspath(result.stdout.strip())) != os.path.normcase(str(root)):
            raise ValueError("root must be the exact Git project root")
        targets = {relative: safe_path(root / relative) for relative in OUTPUTS}
        contents = render(read_vocabulary(root))
        if args.print_json:
            print(json.dumps(contents, ensure_ascii=False))
            return 0
        if args.check:
            drift = [relative for relative, content in contents.items()
                     if not targets[relative].is_file() or targets[relative].read_bytes() != content.encode("utf-8")]
            print(json.dumps({"status": "drift" if drift else "pass", "drift": drift}))
            return 1 if drift else 0
        for relative, content in contents.items():
            path = targets[relative]
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(content.encode("utf-8"))
        print(json.dumps({"status": "generated", "paths": list(contents)}))
        return 0
    except (OSError, ValueError, KeyError) as exc:
        print(json.dumps({"error": str(exc)}, ensure_ascii=False))
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
