"""Generate desktop DTOs from the canonical JSON Schema; no handwritten shadow types."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "packages/contracts/v1/core-document.schema.json"
TARGET = ROOT / "frontend/src/api/generated/core-contract.ts"

def ts(node):
    if "$ref" in node:
        return node["$ref"].split("/")[-1]
    if "const" in node:
        return json.dumps(node["const"])
    if "anyOf" in node:
        return " | ".join(ts(value) for value in node["anyOf"])
    if "enum" in node:
        return " | ".join(json.dumps(x) for x in node["enum"])
    kind = node.get("type")
    if isinstance(kind, list):
        return " | ".join(ts({"type": x}) for x in kind)
    if kind == "object":
        required = node.get("required", [])
        return "{ " + "; ".join(f'{key}{"" if key in required else "?"}: {ts(value)}' for key, value in node.get("properties", {}).items()) + " }"
    if kind == "array":
        return f"Array<{ts(node['items'])}>"
    return {"string":"string", "integer":"number", "number":"number", "boolean":"boolean", "null":"null"}.get(kind, "unknown")

def generate():
    schema = json.loads(SOURCE.read_text(encoding="utf-8"))
    result = "// Generated by scripts/contracts/generate_core_document.py. Edit the JSON Schema.\n"
    commands = json.loads((ROOT / "packages/contracts/v1/core-command.schema.json").read_text(encoding="utf-8"))
    result += "export type CoreOperation = " + ts(commands["properties"]["operation"]) + ";\n"
    result += "\n".join(f"export type {key} = {ts(value)};" for key, value in schema["$defs"].items()) + "\n"
    result += "const definitions: Record<string, any> = " + json.dumps(schema["$defs"], ensure_ascii=False) + ";\n"
    result += '''
function validate(node: any, value: unknown): boolean {
  if (node.$ref) return validate(definitions[node.$ref.split("/").pop()], value);
  if ("const" in node) return value === node.const;
  if (node.anyOf) return node.anyOf.some((child: any) => validate(child, value));
  if (node.enum) return node.enum.includes(value);
  if (Array.isArray(node.type)) return node.type.some((type: string) => validate({type}, value));
  switch (node.type) {
    case "string": return typeof value === "string";
    case "integer": return typeof value === "number" && Number.isInteger(value);
    case "number": return typeof value === "number" && Number.isFinite(value);
    case "boolean": return typeof value === "boolean";
    case "null": return value === null;
    case "array": return Array.isArray(value) && value.every(item => validate(node.items, item));
    case "object": {
      if (!value || typeof value !== "object" || Array.isArray(value)) return false;
      const record = value as Record<string, unknown>;
      return (node.required || []).every((key: string) => key in record)
        && (node.additionalProperties !== false || Object.keys(record).every(key => key in (node.properties || {})))
        && Object.entries(node.properties || {}).every(([key, child]) => !(key in record) || validate(child, record[key]));
    }
    default: return true;
  }
}
export function assertCoreDto<T>(name: string, value: unknown): T {
  if (!definitions[name] || !validate(definitions[name], value)) throw new Error("CORE_DTO_INVALID: " + name);
  return value as T;
}
'''
    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(result, encoding="utf-8", newline="\n")

if __name__ == "__main__":
    generate()
