"""Generate the formal-host working-state DTOs from the canonical v2 schema."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "packages/contracts/v2/ui-working-state.schema.json"
TARGET = ROOT / "frontend/src/api/generated/ui-working-state-contract.ts"


def ts(node):
    if "$ref" in node:
        return "UiWorkingState" + node["$ref"].split("/")[-1]
    if "const" in node:
        return json.dumps(node["const"])
    if "enum" in node:
        return " | ".join(json.dumps(v) for v in node["enum"])
    if "anyOf" in node:
        return " | ".join(ts(v) for v in node["anyOf"])
    kind = node.get("type")
    if kind == "object":
        properties = node.get("properties", {})
        if not properties:
            return "Record<string, " + ts(node.get("additionalProperties", {})) + ">"
        required = node.get("required", [])
        value = "{ " + "; ".join(f"{key}{'' if key in required else '?'}: {ts(child)}" for key, child in properties.items()) + " }"
        return value if node.get("additionalProperties") is False else value + " & Record<string, unknown>"
    if kind == "array":
        return "Array<" + ts(node.get("items", {})) + ">"
    return {"string": "string", "integer": "number", "number": "number", "boolean": "boolean", "null": "null"}.get(kind, "unknown")


VALIDATOR = '''
function valid(node: any, value: unknown): boolean {
  if (node.$ref) return valid(definitions[node.$ref.split("/").pop()], value);
  if ("const" in node) return value === node.const;
  if (node.enum) return node.enum.includes(value);
  if (node.anyOf) return node.anyOf.some((child: any) => valid(child, value));
  if (node.type === "null") return value === null;
  if (node.type === "boolean") return typeof value === "boolean";
  if (node.type === "string") return typeof value === "string"
    && (node.pattern === undefined || new RegExp(node.pattern).test(value))
    && (node.maxLength === undefined || Array.from(value).length <= node.maxLength);
  if (node.type === "integer") return typeof value === "number" && Number.isSafeInteger(value)
    && (node.minimum === undefined || value >= node.minimum)
    && (node.maximum === undefined || value <= node.maximum);
  if (node.type === "array") return Array.isArray(value)
    && (node.maxItems === undefined || value.length <= node.maxItems)
    && (!node.uniqueItems || new Set(value.map(item => JSON.stringify(item))).size === value.length)
    && value.every(item => valid(node.items || {}, item));
  if (node.type === "object") {
    if (!value || typeof value !== "object" || Array.isArray(value)) return false;
    const object = value as Record<string, unknown>, properties = node.properties || {}, keys = Object.keys(object);
    return (node.maxProperties === undefined || keys.length <= node.maxProperties)
      && (node.required || []).every((key: string) => Object.prototype.hasOwnProperty.call(object, key))
      && keys.every(key => (!node.propertyNames || valid(node.propertyNames, key))
        && (Object.prototype.hasOwnProperty.call(properties, key) ? valid(properties[key], object[key])
          : node.additionalProperties === false ? false
          : typeof node.additionalProperties === "object" ? valid(node.additionalProperties, object[key]) : true));
  }
  return true;
}
export function assertUiWorkingState<T>(name: string, value: unknown): T {
  if (!definitions[name] || !valid(definitions[name], value)) throw new Error("UI_WORKING_STATE_DTO_INVALID: " + name);
  return value as T;
}
'''


def generate():
    definitions = json.loads(SOURCE.read_text(encoding="utf-8"))["$defs"]
    return "// Generated by scripts/contracts/generate_ui_working_state.py; edit the canonical v2 schema.\n" + "\n".join(
        f"export type UiWorkingState{name} = {ts(node)};" for name, node in definitions.items()
    ) + "\nconst definitions: Record<string, any> = " + json.dumps(definitions, ensure_ascii=False) + ";\n" + VALIDATOR


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    output = generate()
    if args.check:
        if not TARGET.is_file() or TARGET.read_text(encoding="utf-8") != output:
            raise SystemExit("Working-state projection stale; regenerate from the canonical schema")
    else:
        TARGET.write_text(output, encoding="utf-8", newline="\n")
