"""Generate a read-only catalog projection from the two existing authorities."""
import argparse
import hashlib
import json
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[2]
ATLAS = ROOT / "docs/truth/CAPABILITY_ATLAS_V2.yaml"
LINKS = ROOT / "config/capability-map.v1.json"
TARGET = ROOT / "frontend/src/api/generated/capability-catalog.ts"


def generate():
    atlas_bytes = ATLAS.read_bytes()
    link_bytes = LINKS.read_bytes()
    atlas = yaml.safe_load(atlas_bytes)
    links = json.loads(link_bytes)
    entries = atlas["capabilities"]
    mappings = links["capabilities"]
    atlas_ids = [entry["capability_id"] for entry in entries]
    mapping_ids = [entry["capability_id"] for entry in mappings]
    if not atlas_ids or len(atlas_ids) != len(set(atlas_ids)):
        raise ValueError("Atlas must contain unique capability IDs")
    if len(mapping_ids) != len(set(mapping_ids)) or set(mapping_ids) != set(atlas_ids):
        raise ValueError("Existing capability map must cover exactly the Atlas IDs")
    by_id = {entry["capability_id"]: entry for entry in mappings}
    for mapping in mappings:
        if mapping["state"] not in {"core_native", "worker_backed", "not_implemented"}:
            raise ValueError("Unknown implementation declaration")
        if not isinstance(mapping["runtime_capabilities"], list) or any(
            not isinstance(value, str) for value in mapping["runtime_capabilities"]
        ):
            raise ValueError("Runtime capability links must be strings")
    result = {
        "sources": [
            {"path": ATLAS.relative_to(ROOT).as_posix(), "sha256": hashlib.sha256(atlas_bytes).hexdigest()},
            {"path": LINKS.relative_to(ROOT).as_posix(), "sha256": hashlib.sha256(link_bytes).hexdigest()},
        ],
        "note": "Read-only projection. Atlas declarations and implementation links are not runtime execution evidence.",
        "donor_mapping": "not_established",
        "entries": [{"atlas": entry, "implementation": by_id[entry["capability_id"]]} for entry in entries],
    }
    return (
        "// Generated by scripts/contracts/generate_capability_catalog.py. Edit the source Atlas/map only.\n"
        "export const CAPABILITY_CATALOG = " + json.dumps(result, ensure_ascii=False, indent=2) + " as const;\n"
        "export type CapabilityCatalogEntry = typeof CAPABILITY_CATALOG.entries[number];\n"
    )


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    output = generate()
    if arguments.check:
        if not TARGET.is_file() or TARGET.read_text(encoding="utf-8") != output:
            raise SystemExit("Capability catalog is stale: run its generator")
    else:
        TARGET.parent.mkdir(parents=True, exist_ok=True)
        TARGET.write_text(output, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
