"""Generate teaching DTOs from JSON Schema; request omission is distinct from response null."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "packages/contracts/v2/teaching.schema.json"
TARGET = ROOT / "frontend/src/api/generated/teaching-contract.ts"

def ts(node):
    if "$ref" in node:
        return node["$ref"].split("/")[-1]
    if "const" in node:
        return json.dumps(node["const"])
    if "enum" in node:
        return " | ".join(json.dumps(value) for value in node["enum"])
    if "anyOf" in node:
        return " | ".join(ts(value) for value in node["anyOf"])
    kind = node.get("type")
    if isinstance(kind, list):
        return " | ".join(ts({"type": value}) for value in kind)
    if kind == "object":
        required = node.get("required", [])
        return "{ " + "; ".join(f'{key}{"" if key in required else "?"}: {ts(value)}' for key, value in node.get("properties", {}).items()) + " }"
    if kind == "array":
        return f"Array<{ts(node['items'])}>"
    return {"string":"string", "integer":"number", "number":"number", "boolean":"boolean", "null":"null"}.get(kind, "unknown")

RUNTIME = r'''
function validate(node: any, value: unknown): boolean {
  if (node.$ref) return validate(definitions[node.$ref.split("/").pop()], value);
  if (Object.prototype.hasOwnProperty.call(node, "const")) return value === node.const;
  if (node.enum) return node.enum.includes(value);
  if (node.anyOf) return node.anyOf.some((child: any) => validate(child, value));
  switch (node.type) {
    case "string": {
      if (typeof value !== "string") return false;
      const length = [...value].length;
      return (node.minLength === undefined || length >= node.minLength)
        && (node.maxLength === undefined || length <= node.maxLength)
        && (!node.pattern || new RegExp(node.pattern, "u").test(value))
        && (node["x-maxUtf8Bytes"] === undefined || new TextEncoder().encode(value).length <= node["x-maxUtf8Bytes"]);
    }
    case "integer": return typeof value === "number" && Number.isSafeInteger(value)
      && (node.minimum === undefined || value >= node.minimum) && (node.maximum === undefined || value <= node.maximum);
    case "boolean": return typeof value === "boolean";
    case "null": return value === null;
    case "array": return Array.isArray(value)
      && (node.minItems === undefined || value.length >= node.minItems)
      && (node.maxItems === undefined || value.length <= node.maxItems)
      && value.every(item => validate(node.items, item));
    case "object": {
      if (!value || typeof value !== "object" || Array.isArray(value)) return false;
      const record = value as Record<string, unknown>;
      const owns = (key: string) => Object.prototype.hasOwnProperty.call(record, key);
      return (node.required || []).every((key: string) => owns(key))
        && (node.additionalProperties !== false || Object.keys(record).every(key => Object.prototype.hasOwnProperty.call(node.properties || {}, key)))
        && Object.entries(node.properties || {}).every(([key, raw]) => {
          if (!owns(key)) return true;
          const child = raw as any;
          if (!validate(child, record[key])) return false;
          if (child["x-equalsField"] && record[key] !== record[child["x-equalsField"]]) return false;
          if (child["x-notEqualsField"] && record[key] !== null && record[key] === record[child["x-notEqualsField"]]) return false;
          if (child["x-onlyForKind"] && record[key] !== null && record.kind !== child["x-onlyForKind"]) return false;
          return true;
        });
    }
    default: return false;
  }
}
/** Shape and byte constraints only: actor, SQL references and package hash remain Core authority. */
export function assertTeachingDto<T>(name: string, value: unknown): T {
  if (!Object.prototype.hasOwnProperty.call(definitions, name) || !validate(definitions[name], value)) throw new Error("TEACHING_DTO_INVALID: " + name);
  return value as T;
}
'''

def generate(source=SOURCE, target=TARGET, check=False):
    schema = json.loads(source.read_text(encoding="utf-8"))
    result = "// Generated by scripts/contracts/generate_core_teaching.py. Edit the JSON Schema.\n"
    result += "// Write inputs allow absent Options; canonical responses require explicit null.\n"
    result += "\n".join(f"export type {key} = {ts(value)};" for key, value in schema["$defs"].items()) + "\n"
    result += "const definitions: Record<string, any> = " + json.dumps(schema["$defs"], ensure_ascii=False) + ";\n"
    result += RUNTIME
    if check:
        return target.exists() and target.read_text(encoding="utf-8") == result
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(result, encoding="utf-8", newline="\n")
    return True

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--schema", type=Path, default=SOURCE)
    parser.add_argument("--target", type=Path, default=TARGET)
    parser.add_argument("--check", action="store_true", help="Fail on drift without writing")
    args = parser.parse_args()
    raise SystemExit(0 if generate(args.schema, args.target, args.check) else 1)
