"""Measure the repository's footprint per ownership class and flag anything outside the layout.

Why this exists: the ignored development root grew to tens of gigabytes and acquired directories
nobody had agreed to (`rt-before-*` snapshots, duplicate candidate trees, per-build tool dirs). Size
alone is not the problem — unbounded *unclassified* size is, because it hides which paths are
expendable cache and which are cited evidence.

The layout this asserts is the one the repository already documents:

* tracked source        crates/ services/ frontend/ src-tauri/ apps/ scripts/ config/ docs/ tests/ packages/
* ignored dev outputs   .project-local/{build,runs,task-runtime,candidates,recovery,mig,cache}
* local runtime data    data/ (git-ignored, a convenience copy, never a source of truth)
* deployment surface    a Green tree outside this repository (written only by an audited deploy)

Anything else at the repository root, or any unexpected top-level entry inside `.project-local`, is
reported as OUT-OF-LAYOUT rather than silently measured. Run with `--json <path>` to write the
report; the exit code is non-zero when something is out of layout.
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]

# Which ignored top-level entries are sanctioned. Everything else at the root is drift.
ALLOWED_IGNORED = {".git", ".github", ".worklab", ".project-local", ".project", ".codex.example",
                   ".cargo", ".ruff_cache", ".pytest_cache", ".venv", ".hermes", ".codex", ".dsh",
                   # the interpreter's own bytecode cache: gitignored, regenerated by the next
                   # import or pytest run, and already the same class as .pytest_cache above --
                   # deleting it only makes the layout test red again on the next run
                   "__pycache__",
                   # documented local runtime state: a convenience copy, never a source of truth
                   "data",
                   # declared-ignored but load-bearing, so "ignored" is not "drift":
                   # `/tools/tesseract/tessdata/` is named by `.gitignore:50` and resolved by
                   # crates/archeaxis-application/tests/ocr_job_end_to_end.rs,
                   # tests/pdf_ocr_chain.rs and scripts/launch/core_launch.py
                   "tools",
                   # agent session state: the same ownership class as .hermes and .codex above,
                   # neither this project's output nor anything this report may read or relocate
                   ".zcode"}
DEV_ALLOWED = {"build", "runs", "task-runtime", "candidates", "recovery", "mig", "cache",
               "a3-python-input", "worktrees", "legacy-scratch",
               # named by a tracked document, so it stays; sanctioned rather than re-flagged forever
               "tmp"}
# Budgets are ceilings for review, not delete triggers: exceeding one means the class needs a
# decision, and a class is only ever pruned with an audited path list and a preservation ref.
DEV_BUDGET_GB = {"build": 22.0, "task-runtime": 12.0, "candidates": 4.0, "runs": 2.0, "recovery": 4.0}
# Donor/probe trees are named by number in the clean-up records (a3 = donor, a10 = restore target),
# and `rt`/`rt-before-*` are cited by hand-off notes. They are a class, not drift.
DEV_ALLOWED_PATTERN = __import__("re").compile(r"^(a\d+(-.*)?|rt(-.*)?|legacy-scratch.*)$")


def dev_allowed(name: str) -> bool:
    return name in DEV_ALLOWED or bool(DEV_ALLOWED_PATTERN.match(name))


def is_link(entry: os.DirEntry) -> bool:
    """A symlink or a Windows junction - either way, the bytes it reaches live elsewhere.

    `Path.is_symlink()` reports False for a junction and `is_dir(follow_symlinks=False)` reports
    True for one, so a walk that only consults those two descends straight through it.
    """
    try:
        if entry.is_junction():
            return True
    except (AttributeError, OSError):
        pass
    return entry.is_symlink()


def is_reparse_point(path: Path) -> bool:
    try:
        return bool(getattr(path.stat(follow_symlinks=False), "st_reparse_tag", 0)) or path.is_symlink()
    except OSError:
        return False


def links_under(path: Path) -> list[dict[str, str]]:
    """Links inside *path* with their targets, so shared bytes are attributed to their one owner
    instead of being counted into every directory that points at them."""
    found: list[dict[str, str]] = []
    stack = [path]
    while stack:
        current = stack.pop()
        try:
            with os.scandir(current) as entries:
                for entry in entries:
                    candidate = Path(entry.path)
                    if is_link(entry):
                        try:
                            target = os.readlink(entry.path)
                        except OSError:
                            target = ""
                        found.append({"link": str(candidate), "target": str(target)})
                    elif entry.is_dir(follow_symlinks=False):
                        stack.append(candidate)
        except OSError:
            continue
    return sorted(found, key=lambda item: item["link"])


def directory_size(path: Path) -> int:
    """Bytes owned by *path*, not bytes reachable from it.

    A worktree's frontend/node_modules is a link to the single shared install; following it made
    every worktree report the same ~190 MB as its own, which is the double-count this report exists
    to prevent. `links_under` names those bytes once, at their target.
    """
    if is_reparse_point(path):
        return 0
    total = 0
    stack = [path]
    while stack:
        current = stack.pop()
        try:
            with os.scandir(current) as entries:
                for entry in entries:
                    if is_link(entry):
                        continue
                    if entry.is_file(follow_symlinks=False):
                        total += entry.stat(follow_symlinks=False).st_size
                    elif entry.is_dir(follow_symlinks=False):
                        stack.append(Path(entry.path))
        except OSError:
            continue
    return total


def protected_bytes(directory: Path) -> int:
    """Bytes inside *directory* that a documented rule puts out of reach of this report.

    The compile caches are that case: `dev.py` is explicit that no historical cache is moved or
    removed, so counting them against a budget would only ever produce a permanent false alarm.
    They are still measured and shown - the point is to see them, not to schedule their deletion.
    """
    total = 0
    try:
        children = sorted(directory.iterdir())
    except OSError:
        return 0
    for child in children:
        if not child.is_dir():
            continue
        name = child.name
        if name.startswith("cargo"):  # <root>/cargo, <root>/cargo-gnu
            total += directory_size(child)
        elif name not in {".git"} and (child / "cargo").is_dir():  # <identity>/cargo
            total += directory_size(child / "cargo")
    return total


def _git_root_names(repo: Path | None = None) -> set[str]:
    """Top-level names Git itself tracks — the authoritative expectation for the repository root.

    A hand-written allowlist flagged `.gitignore`, `.editorconfig` and every other tracked
    configuration file as drift, which is worse than useless: a checker that cries wolf gets ignored.
    Git already knows what belongs here, so the contract is asked of Git and only the *ignored* side
    needs a declared set.
    """
    import subprocess

    repo = REPO if repo is None else Path(repo)
    names: set[str] = set()
    try:
        # Paths are decoded as UTF-8: this repository tracks non-ASCII names, and the platform
        # default codec raises on their bytes, which turned the whole report into a crash instead
        # of a measurement. `surrogateescape` keeps an undecodable name visible rather than fatal.
        listing = subprocess.run(
            ["git", "ls-files", "-z"],
            cwd=repo,
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="surrogateescape",
            check=True,
        )
    except (OSError, subprocess.CalledProcessError):
        return names
    if listing.stdout is None:
        return names
    for entry in listing.stdout.split("\0"):
        if entry:
            names.add(entry.split("/", 1)[0])
    return names


def checkout_roots(repo: Path) -> list[Path]:
    """This repository's primary checkout plus every linked worktree that still exists.

    A layout contract is only worth as much as its coverage: the dev roots of the other checkouts
    are where the residue actually accumulated, so measuring just the one the script lives in
    certified a clean tree beside a dirty one.
    """
    import subprocess

    roots = [repo]
    listing = subprocess.run(["git", "-C", str(repo), "worktree", "list", "--porcelain"],
                             capture_output=True, text=True, encoding="utf-8", errors="replace")
    for line in (listing.stdout or "").splitlines():
        if line.startswith("worktree "):
            path = Path(line[len("worktree "):].strip())
            if path.is_dir() and path != repo:
                roots.append(path)
    return roots


def known_run_identities(repo: Path) -> set[str]:
    """The identity digests `dev.py` would produce for every checkout registered right now.

    `dev.py` builds each run root as `runs/<identity>/<run_id>` with
    `identity = sha256(str(root).casefold())[:10]`, so a name at the first level of `runs/` that is
    not one of these digests was not created by the launcher - it is an agent that improvised a
    directory one level too shallow. That was the actual state of this repository: hundreds of such
    directories and loose files had piled up while every existing check stayed green, because the
    checks only inspected direct children of `.project-local`.
    """
    import hashlib

    return {hashlib.sha256(str(root).casefold().encode()).hexdigest()[:10]
            for root in checkout_roots(repo)}


def runs_layout(dev: Path, repo: Path) -> tuple[list[str], list[str]]:
    """Split `runs/` into (wrong depth or shape, right shape but the checkout is gone).

    The first is a contract violation and belongs in `out_of_layout`. The second is not a violation:
    the evidence of a retired worktree is still evidence, and deciding to archive it is a call about
    retention, so it is reported separately and never auto-moved.
    """
    import re

    runs = dev / "runs"
    if not runs.is_dir():
        return [], []
    identities = known_run_identities(repo)
    violations, stale = [], []
    for entry in sorted(runs.iterdir()):
        if not entry.is_dir():
            violations.append(f"runs: {entry.name} (loose file; runs/ holds only identity digests)")
        elif not re.fullmatch(r"[0-9a-f]{10}", entry.name):
            violations.append(f"runs: {entry.name}/ (not a launcher identity digest)")
        elif entry.name not in identities:
            stale.append(f"runs: {entry.name}/ (run root of a checkout that no longer exists)")
    return violations, stale


def measure(repo: Path | None = None) -> dict:
    repo = REPO if repo is None else Path(repo)
    out_of_layout: list[str] = []
    tracked = _git_root_names(repo)
    root_entries = []
    for entry in sorted(repo.iterdir()):
        name = entry.name
        if name in tracked:
            if entry.is_dir():
                record = {"name": name + "/", "bytes": directory_size(entry), "tracked": True}
                # Name what was excluded. A directory that reports 1.1 MB while a 190 MB install
                # sits behind a link inside it is only honest if the link and its target are shown;
                # otherwise the shared bytes look like they vanished from the measurement.
                links = links_under(entry)
                if links:
                    record["links"] = links
                root_entries.append(record)
            continue
        if name in ALLOWED_IGNORED:
            continue
        out_of_layout.append(f"root: {name}/" if entry.is_dir() else f"root: {name}")

    dev = repo / ".project-local"
    dev_classes, dev_strays = [], []
    if dev.is_dir():
        for entry in sorted(dev.iterdir()):
            name = entry.name
            if not dev_allowed(name):
                dev_strays.append(entry)
                out_of_layout.append(f".project-local: {name}/" if entry.is_dir() else f".project-local: {name}")
                continue
            size = directory_size(entry)
            # Compile caches are exempt from the budget rather than silently over it. `dev.py`
            # states the rule - "Do not move or remove any historical cache" - so a class that is
            # mostly that cache cannot be brought under a ceiling by deleting it, and a ceiling that
            # is knowingly exceeded is noise. Only the rest of the class is budgeted.
            protected = protected_bytes(entry) if entry.is_dir() else 0
            budget = DEV_BUDGET_GB.get(name) or DEV_BUDGET_GB.get(name.split("-")[0])
            dev_classes.append({
                "name": name + "/" if entry.is_dir() else name,
                "bytes": size,
                "gb": round(size / 1024 ** 3, 2),
                "protected_bytes": protected,
                "budgeted_bytes": size - protected,
                "budget_gb": budget,
                "over_budget": bool(budget and size - protected > budget * 1024 ** 3),
            })
    runs_violations, runs_stale = runs_layout(dev, repo)
    return {
        "repository": str(repo),
        "root": root_entries,
        "ignored_root": sorted(ALLOWED_IGNORED),
        "dev_root": dev_classes,
        "dev_strays": [str(path.relative_to(repo)).replace("\\", "/") for path in dev_strays],
        "runs_layout": runs_violations,
        "runs_stale_identity": runs_stale,
        "out_of_layout": out_of_layout + runs_violations,
    }


def print_report(report: dict) -> None:
    print(f"repository {report['repository']}")
    print("root classes:")
    for entry in sorted(report["root"], key=lambda item: -item["bytes"]):
        # Say so out loud: the number is owned bytes, and what it left out is named here.
        links = entry.get("links") or []
        shared = f"   links out -> {', '.join(link['target'] for link in links)}" if links else ""
        print(f"  {entry['bytes'] / 1024 ** 3:8.2f} GB  {entry['name']}{shared}")
    print(".project-local classes (budget in GB; compile caches shown but not budgeted):")
    for entry in sorted(report["dev_root"], key=lambda item: -item["bytes"]):
        flag = f"  OVER budget {entry['budget_gb']}" if entry["over_budget"] else ""
        budget = f"{entry['budget_gb']}" if entry["budget_gb"] else "-"
        protected = entry.get("protected_bytes") or 0
        held = f"  ({protected / 1024 ** 3:.2f} GB of it is a cache dev.py forbids removing)" if protected else ""
        print(f"  {entry['gb']:8.2f} GB  {entry['name']:<24} budget {budget}{flag}{held}")
    runs = report.get("runs_layout") or []
    stale = report.get("runs_stale_identity") or []
    if runs or stale:
        # Two thousand lines of detail would bury the report, so the count leads and only a sample is
        # printed. The full lists are in the JSON, which is what a realignment tool consumes.
        print(f"runs/: {len(runs)} entries at the wrong depth or shape, "
              f"{len(stale)} identity dirs whose checkout is gone")
        for item in runs[:5]:
            print(f"  - {item}")
        for item in stale[:5]:
            print(f"  - {item}")
    out = report["out_of_layout"]
    if out:
        print(f"OUT-OF-LAYOUT ({len(out)} entries, needs a decision, not a silent delete):")
        for item in out[:10]:
            print(f"  - {item}")
        if len(out) > 10:
            print(f"  ... {len(out) - 10} more, see --json")
    else:
        print("layout: every entry is inside the documented set")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--json", default=None)
    # The linked worktrees hold the current scripts while the checked-out repositories hold the
    # dev roots, so measuring a *different* checkout has to be a parameter rather than a reason to
    # copy this file over or to edit the other checkout.
    parser.add_argument("--repo", default=None,
                        help="checkout to measure (default: the repository this script lives in)")
    args = parser.parse_args()
    report = measure(Path(args.repo) if args.repo else None)
    print_report(report)
    if args.json:
        Path(args.json).write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    return 1 if report["out_of_layout"] else 0


if __name__ == "__main__":
    sys.exit(main())
