import { useEffect, useId, useRef, useState } from "react";
import { coreCommand } from "../api/core";
import type { DocumentDto } from "../api/generated/core-contract";
import type { AiAsset, AssetContextGrant, AssetSnapshot, AssetPacketRequest, AssetPacketResponse } from "../api/generated/ai-asset-contract";
import { documentRequestIdentity } from "../presentation/documentRequestIdentity";
import { failureMessage } from "../presentation/labels";
import { readAssetConsumption } from "../presentation/assetConsumption";
import { ObjectReferencePicker } from "./ObjectReferencePicker";
import { RawReceiptButton } from "./DiagnosticConsole";

type Obj=Record<string,unknown>;
const record=(v:unknown):Obj=>{if(!v||typeof v!=="object"||Array.isArray(v))throw new Error("对象不兼容");return v as Obj;};
const order=(v:unknown):unknown=>Array.isArray(v)?v.map(order):v&&typeof v==="object"?Object.fromEntries(Object.entries(v).sort(([a],[b])=>a.localeCompare(b)).map(([k,x])=>[k,order(x)])):v;
const eq=(a:unknown,b:unknown)=>JSON.stringify(order(a))===JSON.stringify(order(b));
const snap=(d:DocumentDto):AssetSnapshot=>({document_id:d.document_id,version:d.version,content_sha256:d.content_sha256});
/** Human host prepares a manual packet. No peer delivery or model execution is claimed. */
export function AiAssetPacketPanel({asset,parseAsset,parseGrant,packetCommand,onUse}: {
  asset:DocumentDto|null;parseAsset:(v:unknown)=>AiAsset|null;parseGrant:(v:unknown)=>AssetContextGrant|null;
  packetCommand:(request:AssetPacketRequest)=>Promise<AssetPacketResponse>;onUse?:(request:AssetPacketRequest)=>void;
}) {
  const owner=useId(),mounted=useRef(true),busyRef=useRef(false),generation=useRef(0),serial=useRef(0);
  const [value,setValue]=useState<AssetContextGrant|null>(null),valueRef=useRef<AssetContextGrant|null>(null),[base,setBase]=useState<DocumentDto|null>(null),baseRef=useRef<DocumentDto|null>(null),[dirty,setDirty]=useState(false),dirtyRef=useRef(false);
  const [busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[message,setMessage]=useState(""),[picking,setPicking]=useState(false),pickingRef=useRef(false),[receipt,setReceipt]=useState<AssetPacketResponse|null>(null);
  const write=useRef<{op:"document_create"|"document_draft";payload:Obj;id:string;version:number;title:string;source_id:string|null;source_revision:string|null;serial:number;value:AssetContextGrant}|null>(null),request=useRef<AssetPacketRequest|null>(null);
  const [expiry,setExpiry]=useState<string|null>(null),expiryRef=useRef<string|null>(null);
  function publish(){window.dispatchEvent(new CustomEvent("archeaxis-draft-dirty",{detail:{owner,dirty:dirtyRef.current||!!write.current||!!request.current||pickingRef.current||busyRef.current||expiryRef.current!==null}}));}
  function setGrant(v:AssetContextGrant,b:DocumentDto|null,isDirty:boolean){valueRef.current=v;baseRef.current=b;dirtyRef.current=isDirty;setValue(v);setBase(b);setDirty(isDirty);publish();}
  useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;generation.current++;window.dispatchEvent(new CustomEvent("archeaxis-draft-dirty",{detail:{owner,dirty:false}}));};},[]);
  function edit(change:Partial<AssetContextGrant>){if(!valueRef.current||busyRef.current||valueRef.current.state==="revoked")return;serial.current++;setGrant({...valueRef.current,...change,state:"candidate"},baseRef.current,true);setReceipt(null);}
  function start(){if(dirtyRef.current||write.current||request.current||busyRef.current||expiryRef.current!==null){setMessage("授权草稿或冻结请求尚未确认，请先处理。");return;}if(!asset){setMessage("请先保存并选择真实资产版本。");return;}let v:AiAsset|null=null;try{v=parseAsset(record(record(asset.editor_json).attrs).archeaxis_ai_asset);}catch{setError("不兼容资产只读，不能授权。");return;}if(!v||v.state!=="adopted"){setMessage("只有已采用的真实资产可以授权消费；候选仍可独立保存。");return;}generation.current++;serial.current++;setReceipt(null);setGrant({schema:"archeaxis.asset-context-grant/v1",asset:snap(asset),purpose:"",consumer:"manual-context-packet",operations:["read_packet"],authorization_basis:"",expires_at:null,state:"candidate"},null,true);}
  async function open(s:AssetSnapshot,doc:DocumentDto){if(dirtyRef.current||write.current||request.current||busyRef.current||expiryRef.current!==null){setError("当前授权草稿保留。");return;}let grant:AssetContextGrant|null=null;try{grant=parseGrant(record(record(doc.editor_json).attrs).archeaxis_asset_context_grant);}catch{setError("不兼容授权只读。");return;}if(!grant||!eq(s,snap(doc))){setError("未知授权保持只读，未导入为新授权。");return;}generation.current++;serial.current++;setReceipt(null);setGrant(structuredClone(grant),doc,false);pickingRef.current=false;setPicking(false);publish();}
  async function save(state?:AssetContextGrant["state"]){if(!valueRef.current||busyRef.current||pickingRef.current||expiryRef.current!==null)return;if(state&&write.current){setMessage("先重试冻结请求。");return;}if(state==="granted"&&(!valueRef.current.purpose.trim()||!valueRef.current.authorization_basis.trim())){setError("明确授权需要用途和依据；候选可直接保存。");return;}
    busyRef.current=true;setBusy(true);setError(null);publish();try{if(!write.current){const v=structuredClone({...valueRef.current,...(state?{state}:{})}),b=baseRef.current,old=b?record(b.editor_json):{type:"doc",content:[]},editor={...old,attrs:{...(old.attrs?record(old.attrs):{}),archeaxis_asset_context_grant:v}},id=`assetgrant_${crypto.randomUUID()}`;
      write.current=b?{op:"document_draft",payload:{document_id:b.document_id,body:{expected_version:b.version,editor_json:editor}},id:b.document_id,version:b.version+1,title:b.title,source_id:b.source_id,source_revision:b.source_revision,serial:serial.current,value:v}:{op:"document_create",payload:{body:{create_request_id:id,title:"AI 资产消费授权",editor_json:editor}},id:await documentRequestIdentity(id),version:1,title:"AI 资产消费授权",source_id:null,source_revision:null,serial:serial.current,value:v};}
      const f=write.current,written=await coreCommand<DocumentDto>(f.op,structuredClone(f.payload)),read=await coreCommand<DocumentDto>("document_get",{document_id:f.id});
      const valid=(d:DocumentDto)=>d.document_id===f.id&&d.version===f.version&&d.title===f.title&&d.source_id===f.source_id&&d.source_revision===f.source_revision&&eq(d.editor_json,record(f.payload.body).editor_json)&&eq(parseGrant(record(record(d.editor_json).attrs).archeaxis_asset_context_grant),f.value);
      if(!valid(written)||!valid(read)||read.content_sha256!==written.content_sha256)throw new Error("授权回读不一致");write.current=null;setGrant(serial.current===f.serial?f.value:valueRef.current,read,serial.current!==f.serial);setMessage("授权版本已保存并核对；消费仍由 Core 校验版本、时效与权限。");
    }catch(e){setError(failureMessage(e));setMessage("UNKNOWN：授权写请求冻结，不自动重复。");}finally{busyRef.current=false;if(mounted.current){setBusy(false);publish();}}}
  async function packet(){const grant=valueRef.current,b=baseRef.current;if(!grant||!b||busyRef.current||write.current||pickingRef.current||expiryRef.current!==null||(!request.current&&(dirtyRef.current||grant.state!=="granted")))return;
    if(grant.consumer!=="manual-context-packet"||!grant.operations.includes("read_packet")){setError("当前人端仅准备明确授权的手工上下文包。");return;}
    busyRef.current=true;setBusy(true);publish();try{if(!request.current)request.current={request_id:`packet_${crypto.randomUUID()}`,grant:snap(b),asset:structuredClone(grant.asset),purpose:grant.purpose,consumer:"manual-context-packet",operation:"read_packet"};const f=request.current,result=await packetCommand(structuredClone(f));
      const r=result.receipt,p=result.packet;if(r.request_id!==f.request_id||!eq(r.asset,f.asset)||!eq(r.grant,f.grant)||r.purpose!==f.purpose||r.consumer!==f.consumer||r.operation!==f.operation||r.packet_sha256!==result.packet_sha256||p.purpose!==f.purpose||p.consumer!==f.consumer||!eq(p.asset,f.asset)||!eq(p.grant,f.grant)||p.operation!=="read_packet"||!/^[a-f0-9]{64}$/.test(result.packet_sha256)||!/^[a-f0-9]{64}$/.test(r.request_sha256)||r.tool_execution!=="NOT_EXECUTED"||r.grants_machine_qualification!==false||r.grants_human_mastery!==false||p.reference_only_sources!==true||p.items.some(item=>item.engine_execution!=="NOT_EXECUTED"||item.grants_professional_truth!==false||item.grants_human_mastery!==false||item.grants_machine_qualification!==false)||r.delivery_status!=="PREPARED_NOT_SENT_TO_PEER"||r.model_execution!=="NOT_EXECUTED"||p.tool_execution!=="NOT_EXECUTED"||p.private_session_access!==false||p.machine_qualification!==false||p.human_mastery!==false||p.professional_truth!==false||!p.items.length||!eq(p.items[0].snapshot,f.asset))throw new Error("上下文包身份或安全回执不符");request.current=null;setReceipt(result);setMessage("手工上下文包已准备；未发送给另一客户端，未运行模型或工具。");
    }catch(e){setError(failureMessage(e));setMessage("UNKNOWN：保留原包请求身份，核对后可显式重试。");}finally{busyRef.current=false;if(mounted.current){setBusy(false);publish();}}}
  async function use(operation:"answer"|"retest"){
    if(!baseRef.current||dirtyRef.current||busyRef.current||write.current||request.current||expiryRef.current!==null)return;
    const g=++generation.current;let selected:AssetPacketRequest|undefined;
    busyRef.current=true;setBusy(true);setError(null);publish();
    try{const current=await readAssetConsumption(snap(baseRef.current),operation);if(mounted.current&&g===generation.current){selected=structuredClone(current.request);setMessage("已固定实际资产及本地机器授权；知识授权仍必需，不自动调用模型。");}}
    catch(e){if(mounted.current&&g===generation.current)setError(failureMessage(e));}
    finally{busyRef.current=false;if(mounted.current){setBusy(false);publish();}}
    // Release this owner's read lock before the host evaluates its navigation guard.
    if(selected&&mounted.current&&g===generation.current)onUse?.(selected);
  }
  return <section aria-label="资产消费授权与手工交换" className="semantic-panel"><h3>消费授权与手工上下文包</h3><p>授权和资产保存分别进行。手工包是有限版本快照，不读取私人会话，不执行内容，不自动跨客户端发送。</p><button disabled={busy} onClick={start}>为当前已采用资产新建授权</button><button disabled={busy||dirty||!!write.current||!!request.current} onClick={()=>{pickingRef.current=true;setPicking(true);publish();}}>选择已保存资产授权</button>
  {picking?<><ObjectReferencePicker disabled={busy} onSnapshot={(s,d)=>void open(s,d)}/><button onClick={()=>{pickingRef.current=false;setPicking(false);publish();}}>取消授权选择</button></>:null}
  {value?<><p>固定资产 {value.asset.document_id} · v{value.asset.version}；授权 {value.state} · {base?`v${base.version}`:"草稿"}</p><label>消费用途<textarea disabled={busy||value.state==="revoked"} value={value.purpose} onChange={e=>edit({purpose:e.target.value})}/></label><label>消费授权依据<textarea disabled={busy||value.state==="revoked"} value={value.authorization_basis} onChange={e=>edit({authorization_basis:e.target.value})}/></label><label>授权到期 Unix 秒（空白为无期限）<input disabled={busy||value.state==="revoked"} value={expiry??(value.expires_at===null?"":String(value.expires_at))} onChange={e=>{expiryRef.current=e.target.value;setExpiry(e.target.value);publish();}}/></label>{expiry!==null?<><button onClick={()=>{const n=expiry===""?null:Number(expiry);if(n!==null&&(!Number.isSafeInteger(n)||n<0)){setError("授权时效必须为非负整数秒。");return;}edit({expires_at:n});expiryRef.current=null;setExpiry(null);publish();}}>提交授权时效</button><button onClick={()=>{expiryRef.current=null;setExpiry(null);publish();}}>取消授权时效</button></>:null}<label>授权消费端<select disabled={busy||value.state==="revoked"||!!write.current||!!request.current} value={value.consumer} onChange={e=>edit({consumer:e.target.value as AssetContextGrant["consumer"],operations:e.target.value==="local-machine"?["answer"]:["read_packet"]})}><option value="manual-context-packet">手工上下文包</option><option value="local-machine">本地机器回答与复测</option></select></label>{value.consumer==="local-machine"?<fieldset disabled={busy||value.state==="revoked"||!!write.current||!!request.current}><legend>独立允许的模型用途</legend>{(["answer","retest"] as const).map(op=><label key={op}><input type="checkbox" checked={value.operations.includes(op)} onChange={e=>edit({operations:e.target.checked?[...value.operations,op]:value.operations.filter(x=>x!==op)})}/>{op==="answer"?"回答":"独立复测"}</label>)}</fieldset>:null}<p>消费端：{value.consumer}；允许：{value.operations.join("、")}；到期：{value.expires_at??"无期限"}</p>
  <button disabled={busy||value.state==="revoked"||!!write.current} onClick={()=>void save()}>保存授权候选</button><button disabled={busy||value.state==="revoked"||!!write.current} onClick={()=>void save("granted")}>{value.consumer==="manual-context-packet"?"明确授权手工包":"明确授权本地机器"}</button><button disabled={busy||!base||dirty||!!write.current||value.state==="revoked"} onClick={()=>void save("revoked")}>撤回消费授权</button>{write.current?<button disabled={busy} onClick={()=>void save()}>重试冻结授权保存</button>:null}
  <button disabled={value.consumer!=="manual-context-packet"||busy||!!write.current||(!request.current&&(dirty||value.state!=="granted"))} onClick={()=>void packet()}>{request.current?"重试冻结手工包请求":"准备手工上下文包"}</button></>:null}
  {onUse&&value?.consumer==="local-machine"?<>{(["answer","retest"] as const).map(op=><button key={op} disabled={busy||dirty||!!write.current||!!request.current||value.state!=="granted"||!value.operations.includes(op)} onClick={()=>void use(op)}>{op==="answer"?"使用实际资产授权进入回答":"使用实际资产授权进入复测"}</button>)}</>:null}{receipt?<><p>PREPARED_NOT_SENT_TO_PEER · 模型 NOT_EXECUTED · 工具 NOT_EXECUTED</p><RawReceiptButton label="完整手工上下文包与实际回执" payload={receipt}/><p>审计任务：{receipt.audit_task_id}；{receipt.duplicate?"幂等重复回执":"新回执"}</p></>:null}{message?<p role="status">{message}</p>:null}{error?<p role="alert">{error}</p>:null}</section>;
}
