import { beforeEach,afterEach,it,expect,vi } from "vitest";
import { webcrypto } from "node:crypto";
import { fireEvent,render,screen,waitFor } from "@testing-library/react";
import { AiAssetPacketPanel } from "../components/AiAssetPacketPanel";
import { documentRequestIdentity } from "../presentation/documentRequestIdentity";
import type { DocumentDto } from "../api/generated/core-contract";
import type { AiAsset,AssetContextGrant,AssetPacketRequest,AssetPacketResponse } from "../api/generated/ai-asset-contract";
type J=Record<string,any>;
const bridge=vi.hoisted(()=>({call:vi.fn()}));vi.mock("../api/core",()=>({coreCommand:bridge.call}));
const asset:AiAsset={schema:"archeaxis.ai-asset/v1",kind:"rule",content:"惰性规则，不执行",purpose:"工作参考",scope:[],provenance:[],expires_at:null,state:"adopted",members:[],conflicts:[],revises:null,review:null,source_payload:null};
const doc:DocumentDto={document_id:"asset",version:2,title:"资产",source_id:null,source_revision:null,content_sha256:"a".repeat(64),blocks:[],text_projection:"",editor_json:{type:"doc",attrs:{archeaxis_ai_asset:asset},content:[]}};
const parseAsset=(v:unknown)=>v as AiAsset,parseGrant=(v:unknown)=>v as AssetContextGrant;
function response(request:AssetPacketRequest):AssetPacketResponse{return {packet:{schema:"archeaxis.ai-context-packet/v1",asset:request.asset,grant:request.grant,purpose:request.purpose,consumer:request.consumer,operation:"read_packet",items:[{snapshot:request.asset,kind:"rule",content:asset.content,purpose:asset.purpose,scope:[],provenance:[],engine_execution:"NOT_EXECUTED",grants_professional_truth:false,grants_human_mastery:false,grants_machine_qualification:false}],reference_only_sources:true,private_session_access:false,tool_execution:"NOT_EXECUTED",machine_qualification:false,human_mastery:false,professional_truth:false},packet_sha256:"b".repeat(64),receipt:{schema:"archeaxis.ai-context-packet-receipt/v1",request_id:request.request_id,request_sha256:"c".repeat(64),packet_sha256:"b".repeat(64),asset:request.asset,grant:request.grant,purpose:request.purpose,consumer:request.consumer,operation:"read_packet",delivery_status:"PREPARED_NOT_SENT_TO_PEER",model_execution:"NOT_EXECUTED",tool_execution:"NOT_EXECUTED",grants_machine_qualification:false,grants_human_mastery:false},audit_task_id:"audit_task_real_fixture",duplicate:false};}
let docs:Map<string,DocumentDto>,writes:J[];
beforeEach(()=>{vi.stubGlobal("crypto",webcrypto);writes=[];docs=new Map();bridge.call.mockReset();bridge.call.mockImplementation(async(op,p:J)=>{if(op==="document_get")return structuredClone(docs.get(p.document_id));if(op==="document_create"){writes.push(structuredClone(p));const id=await documentRequestIdentity(p.body.create_request_id);if(!docs.has(id))docs.set(id,{...doc,document_id:id,title:p.body.title,version:1,editor_json:p.body.editor_json});return structuredClone(docs.get(id));}if(op==="document_draft"){writes.push(structuredClone(p));const old=docs.get(p.document_id)!;const next={...old,version:old.version+1,editor_json:p.body.editor_json};docs.set(p.document_id,next);return structuredClone(next);}throw new Error("unexpected "+op);});});
afterEach(()=>{vi.unstubAllGlobals();vi.restoreAllMocks();});
async function authorize(){fireEvent.click(screen.getByRole("button",{name:"为当前已采用资产新建授权"}));fireEvent.change(screen.getByLabelText("消费用途"),{target:{value:"手工接续"}});fireEvent.change(screen.getByLabelText("消费授权依据"),{target:{value:"本人明确决定"}});fireEvent.click(screen.getByRole("button",{name:"明确授权手工包"}));await screen.findByText("授权版本已保存并核对；消费仍由 Core 校验版本、时效与权限。");await waitFor(()=>expect(screen.getByRole("button",{name:"准备手工上下文包"})).toBeEnabled());}
it("candidate asset cannot grant and candidate authorization saves without complete purpose",async()=>{render(<AiAssetPacketPanel asset={{...doc,editor_json:{type:"doc",attrs:{archeaxis_ai_asset:{...asset,state:"candidate"}}}}} parseAsset={parseAsset} parseGrant={parseGrant} packetCommand={vi.fn()}/>);fireEvent.click(screen.getByRole("button",{name:"为当前已采用资产新建授权"}));await screen.findByText("只有已采用的真实资产可以授权消费；候选仍可独立保存。");expect(writes).toEqual([]);});
it("manual context packet is prepared only after explicit saved authorization and withdrawal retains receipt",async()=>{const packet=vi.fn(async (r:AssetPacketRequest)=>response(r));render(<AiAssetPacketPanel asset={doc} parseAsset={parseAsset} parseGrant={parseGrant} packetCommand={packet}/>);await authorize();expect(packet).not.toHaveBeenCalled();fireEvent.click(screen.getByRole("button",{name:"准备手工上下文包"}));await screen.findByText("手工上下文包已准备；未发送给另一客户端，未运行模型或工具。");expect(packet.mock.calls[0][0].consumer).toBe("manual-context-packet");expect(packet.mock.calls[0][0].asset).toEqual({document_id:"asset",version:2,content_sha256:"a".repeat(64)});fireEvent.click(screen.getByRole("button",{name:"撤回消费授权"}));await waitFor(()=>expect(screen.getByRole("button",{name:"准备手工上下文包"})).toBeDisabled());expect(screen.getByText("PREPARED_NOT_SENT_TO_PEER · 模型 NOT_EXECUTED · 工具 NOT_EXECUTED")).toBeInTheDocument();});
it("lost packet acknowledgement freezes exact identity for explicit retry",async()=>{let first=true;const packet=vi.fn(async (r:AssetPacketRequest)=>{if(first){first=false;throw new Error("lost packet ack");}return {...response(r),duplicate:true};});render(<AiAssetPacketPanel asset={doc} parseAsset={parseAsset} parseGrant={parseGrant} packetCommand={packet}/>);await authorize();fireEvent.click(screen.getByRole("button",{name:"准备手工上下文包"}));await screen.findByRole("alert");expect(packet).toHaveBeenCalledTimes(1);fireEvent.click(screen.getByRole("button",{name:"重试冻结手工包请求"}));await screen.findByText("手工上下文包已准备；未发送给另一客户端，未运行模型或工具。");expect(packet.mock.calls[0][0]).toEqual(packet.mock.calls[1][0]);});
it.each(["grant","purpose","delivery_status"])("rejects %s mismatch instead of claiming prepared or delivered",async(field)=>{const packet=vi.fn(async (r:AssetPacketRequest)=>{const out=response(r);if(field==="grant")out.receipt.grant={...out.receipt.grant,version:99};else if(field==="purpose")out.packet.purpose="错用途";else (out.receipt as J).delivery_status="DELIVERED";return out;});render(<AiAssetPacketPanel asset={doc} parseAsset={parseAsset} parseGrant={parseGrant} packetCommand={packet}/>);await authorize();fireEvent.click(screen.getByRole("button",{name:"准备手工上下文包"}));await screen.findByRole("alert");expect(screen.queryByText("PREPARED_NOT_SENT_TO_PEER · 模型 NOT_EXECUTED · 工具 NOT_EXECUTED")).not.toBeInTheDocument();expect(screen.getByRole("button",{name:"重试冻结手工包请求"})).toBeInTheDocument();});
