import {act,fireEvent,render,screen,waitFor} from "@testing-library/react";
import {afterEach,beforeEach,expect,it,vi} from "vitest";
import {webcrypto} from "node:crypto";
import {getRecoveryStatus} from "../api/workspace";
import {verifyCanonicalCore} from "../api/core";
import {App} from "../app/App";
import type {WorkingRead,WorkingState} from "../presentation/coreWorkingState";
const bridge=vi.hoisted(()=>({call:vi.fn()}));
vi.mock("../api/core",()=>({coreCommand:bridge.call,verifyCanonicalCore:vi.fn().mockResolvedValue({})}));
vi.mock("../api/workspace",async original=>({...await original<typeof import("../api/workspace")>(),getRecoveryStatus:vi.fn().mockResolvedValue({state:"ready",safe_mode:false,backend_available:true,message:"SIMULATED ready",backups:[],external_dev:false})}));
const empty=():WorkingState=>({drafts:{},opened_documents:[],active_document:null,page_id:null,pending_original:null});
let read:WorkingRead,release!:(value:WorkingRead)=>void;
beforeEach(()=>{vi.mocked(getRecoveryStatus).mockResolvedValue({state:"ready",safe_mode:false,backend_available:true,message:"SIMULATED ready",backups:[],external_dev:false});vi.mocked(verifyCanonicalCore).mockResolvedValue(undefined);vi.stubGlobal("crypto",webcrypto);window.__TAURI__={core:{invoke:vi.fn()}};window.location.hash="#page=03";bridge.call.mockReset();read={schema:"archeaxis.ui-working-state/v1",workspace_id:"a".repeat(32),restore_epoch:"initial",state_revision:0,state:empty(),draft_digests:{},pending_document_id:null,recovery_candidates:null,recovery_requires_confirmation:false};
bridge.call.mockImplementation(async(op:string,p:{body?:{state:WorkingState}}={})=>{if(op==="ui_state_read")return structuredClone(read);if(op==="ui_state_write")return new Promise<WorkingRead>(resolve=>{release=value=>resolve(value);read={...read,state_revision:read.state_revision+1,state:structuredClone(p.body!.state)};});if(op==="sources_list")return {sources:[]};if(op==="documents_list")return {documents:[],next_cursor:null,snapshot_count:0};return {};});});
afterEach(()=>{delete window.__TAURI__;vi.unstubAllGlobals();vi.restoreAllMocks();});
it("SIMULATED mounted App with real CoreWorkingStateSession navigates while only scene CAS ACK is pending",async()=>{const confirm=vi.spyOn(window,"confirm").mockReturnValue(false);render(<App/>);await waitFor(()=>expect(bridge.call.mock.calls.some(([op])=>op==="ui_state_write")).toBe(true));expect(read.state.drafts).toEqual({});expect(read.state.pending_original).toBeNull();fireEvent.click(document.querySelector('.navigation-sidebar button[data-page-id="02"]')!);await waitFor(()=>expect(window.location.hash).toBe("#page=02"));expect(confirm).not.toHaveBeenCalled();await act(async()=>release(structuredClone(read)));});
it.each(["draft","pending original","editor event"])("SIMULATED mounted App still protects actual %s during navigation",async(kind)=>{window.location.hash="#page=19";read.state.page_id="19";if(kind==="draft"){read.state.drafts["doc-exact"]={base_version:1,editor_json:{type:"doc",content:[{type:"paragraph",content:[{type:"text",text:"保留"}]}]}};read.draft_digests["doc-exact"]="b".repeat(64);}if(kind==="pending original"){read.state.pending_original={create_request_id:"request-exact",title:"保留笔记",editor_json:{type:"doc",content:[]}};read.pending_document_id="doc_req_"+"b".repeat(64);}const confirm=vi.spyOn(window,"confirm").mockReturnValue(false);render(<App/>);await screen.findByRole("heading",{name:"本地工作区与恢复"});if(kind==="editor event")act(()=>window.dispatchEvent(new CustomEvent("archeaxis-draft-dirty",{detail:{owner:"actual-editor",dirty:true}})));confirm.mockClear();fireEvent.click(document.querySelector('.navigation-sidebar button[data-page-id="02"]')!);expect(confirm).toHaveBeenCalledTimes(1);expect(window.location.hash).toBe("#page=19");});

it("SIMULATED scene-only unknown ACK retains journal error without claiming a content draft",async()=>{const original=bridge.call.getMockImplementation()!;bridge.call.mockImplementation(async(op,p)=>{if(op==="ui_state_write")throw new Error("SIMULATED scene ACK lost");return original(op,p);});const confirm=vi.spyOn(window,"confirm").mockReturnValue(false);render(<App/>);await screen.findByText("SIMULATED scene ACK lost");fireEvent.click(document.querySelector('.navigation-sidebar button[data-page-id="02"]')!);await waitFor(()=>expect(window.location.hash).toBe("#page=02"));expect(confirm).not.toHaveBeenCalled();expect(screen.getByText("SIMULATED scene ACK lost")).toBeInTheDocument();});
