import { beforeEach,afterEach,it,expect,vi } from "vitest";
import { webcrypto } from "node:crypto";
import { render,screen,fireEvent,waitFor } from "@testing-library/react";
import { AiAssetPacketPanel } from "../components/AiAssetPacketPanel";
import { assertAiAssetDto,type AiAsset,type AssetContextGrant } from "../api/generated/ai-asset-contract";
import { documentRequestIdentity } from "../presentation/documentRequestIdentity";
const bridge=vi.hoisted(()=>({call:vi.fn()}));vi.mock("../api/core",()=>({coreCommand:bridge.call}));
type J=Record<string,any>;
const doc={document_id:"asset",version:2,content_sha256:"b".repeat(64),source_id:null,source_revision:null,title:"资产",blocks:[],text_projection:"",editor_json:{type:"doc",attrs:{archeaxis_ai_asset:{schema:"archeaxis.ai-asset/v1",kind:"rule",content:"惰性规则",purpose:"",scope:[],provenance:[],state:"adopted",members:[],conflicts:[]}},content:[]}};
const parseAsset=(v:unknown)=>assertAiAssetDto<AiAsset>("AiAsset",v),parseGrant=(v:unknown)=>assertAiAssetDto<AssetContextGrant>("AssetContextGrant",v);
let saved:J|null=null;
beforeEach(()=>{vi.stubGlobal("crypto",webcrypto);saved=null;bridge.call.mockReset();bridge.call.mockImplementation(async(op,p)=>{if(op==="document_create"){saved={...doc,document_id:await documentRequestIdentity(p.body.create_request_id),version:1,title:p.body.title,editor_json:p.body.editor_json};return structuredClone(saved);}if(op==="document_get")return structuredClone(p.document_id==="asset"?doc:saved);throw new Error("unexpected "+op);});});
afterEach(()=>vi.unstubAllGlobals());
async function authorize(){fireEvent.click(screen.getByRole("button",{name:"为当前已采用资产新建授权"}));fireEvent.change(screen.getByLabelText("授权消费端"),{target:{value:"local-machine"}});fireEvent.change(screen.getByLabelText("消费用途"),{target:{value:"真实回答材料"}});fireEvent.change(screen.getByLabelText("消费授权依据"),{target:{value:"本人明确授权"}});fireEvent.click(screen.getByLabelText("独立复测"));fireEvent.click(screen.getByRole("button",{name:"明确授权本地机器"}));await screen.findByText("授权版本已保存并核对；消费仍由 Core 校验版本、时效与权限。");}
it("local-machine use performs strict actual re-read and callback without model/packet execution",async()=>{const use=vi.fn(),packet=vi.fn();render(<AiAssetPacketPanel asset={doc} parseAsset={parseAsset} parseGrant={parseGrant} packetCommand={packet} onUse={use}/>);await authorize();expect(saved!.editor_json.attrs.archeaxis_asset_context_grant.consumer).toBe("local-machine");expect(saved!.editor_json.attrs.archeaxis_asset_context_grant.operations).toEqual(["answer","retest"]);expect(screen.getByRole("button",{name:"准备手工上下文包"})).toBeDisabled();fireEvent.click(screen.getByRole("button",{name:"使用实际资产授权进入回答"}));await waitFor(()=>expect(use).toHaveBeenCalledTimes(1));expect(use.mock.calls[0][0]).toMatchObject({asset:{document_id:"asset",version:2,content_sha256:"b".repeat(64)},grant:{document_id:saved!.document_id,version:1,content_sha256:"b".repeat(64)},consumer:"local-machine",operation:"answer",purpose:"真实回答材料"});expect(packet).not.toHaveBeenCalled();expect(bridge.call.mock.calls.every(x=>["document_create","document_get"].includes(x[0]))).toBe(true);});
it("grant current-version mismatch cannot become a use handoff",async()=>{const use=vi.fn();render(<AiAssetPacketPanel asset={doc} parseAsset={parseAsset} parseGrant={parseGrant} packetCommand={vi.fn()} onUse={use}/>);await authorize();saved!.version=2;fireEvent.click(screen.getByRole("button",{name:"使用实际资产授权进入回答"}));await screen.findByRole("alert");expect(use).not.toHaveBeenCalled();});
it("handoff releases its dirty owner before the host navigation guard runs",async()=>{
 const owners=new Map<string,boolean>();const listen=(e:Event)=>{const d=(e as CustomEvent).detail;owners.set(d.owner,d.dirty);};window.addEventListener("archeaxis-draft-dirty",listen);
 try{const use=vi.fn(()=>expect([...owners.values()].some(Boolean)).toBe(false));render(<AiAssetPacketPanel asset={doc} parseAsset={parseAsset} parseGrant={parseGrant} packetCommand={vi.fn()} onUse={use}/>);await authorize();fireEvent.click(screen.getByRole("button",{name:"使用实际资产授权进入回答"}));await waitFor(()=>expect(use).toHaveBeenCalledTimes(1));}finally{window.removeEventListener("archeaxis-draft-dirty",listen);}
});
