import { useState } from "react";
import { beforeEach, expect, it, vi } from "vitest";
import { render, screen, waitFor, within, fireEvent } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { CanonicalTeachingSpace } from "../spaces/CanonicalTeachingSpace";
const bridge=vi.hoisted(()=>({call:vi.fn()}));
vi.mock("../api/core",()=>({coreCommand:bridge.call}));
vi.mock("../spaces/CanonicalLearningSpace",()=>({CanonicalLearningSpace:({initialItemKey}:{initialItemKey:string})=><div>真实练习入口 {initialItemKey}</div>}));
type Json=Record<string,any>;
let records:Json[], creates:Json[], withdrawn:Set<string>;
function view(record:Json){return {record,content_sha256:"a".repeat(64),withdrawn:withdrawn.has(record.record_id),scoring_status:"not_scored"};}
function record(id:string,kind="requirement",parent_id:string|null=null){return {schema:"archeaxis.teaching-record/v2",record_id:id,kind,knowledge_id:"knowledge_actual_v1",knowledge_version:"knowledge_actual_v1",course_id:null,parent_id,purpose:`目的 ${id}`,scope:"personal",privacy:"local_only",content:`正文 ${id}`,feedback_class:null,assessment_id:null,rubric_version:null,assisted:false,producer_kind:"human_authored"};}
function Harness({initial="08"}:{initial?:string}){const [page,setPage]=useState(initial);return <CanonicalTeachingSpace pageId={page} onOpenPage={setPage}/>;}
beforeEach(()=>{records=[];creates=[];withdrawn=new Set();bridge.call.mockReset();bridge.call.mockImplementation(async(op:string,p:Json={})=>{
 if(op==="teaching_list")return {items:records.map(view),next_cursor:null};
 if(op==="search")return {items:[{knowledge_id:"knowledge_actual_v1",head:"实际来源知识"}]};
 if(op==="knowledge_get")return {knowledge_id:"knowledge_actual_v1",status:"accepted"};
 if(op==="course_list")return {items:[],next_cursor:null};
 if(op==="teaching_create"){creates.push(p.body);const existing=records.find(row=>row.record_id===p.body.record_id);if(!existing)records.push(p.body);return {item:view(existing??p.body),duplicate:!!existing};}
 if(op==="teaching_get"){const found=records.find(row=>row.record_id===p.record_id);if(!found)throw new Error("not found");return view(found);}
 if(op==="teaching_withdraw"){withdrawn.add(p.body.record_id);return {withdrawal_id:p.body.withdrawal_id,record_id:p.body.record_id,duplicate:false,affected_record_ids:[p.body.record_id]};}
 if(op==="teaching_import_preview")return {valid:true,record_count:p.body.records.length,duplicate_count:0,package_sha256:p.body.package_sha256};
 if(op==="teaching_import"){records.push(...p.body.records);return {items:p.body.records.map(view),duplicate_count:0,package_sha256:p.body.package_sha256};}
 if(op==="document_create")return {document_id:"preparation_real_id",version:1};
 if(op==="document_get")return {document_id:p.document_id,version:1};
 throw new Error(op);
});});
async function chooseSource(user:ReturnType<typeof userEvent.setup>){await user.click(screen.getByRole("button",{name:"搜索来源知识"}));await user.click(await screen.findByRole("button",{name:"实际来源知识"}));await screen.findByText(/已核对接受状态/);}
async function fill(user:ReturnType<typeof userEvent.setup>,purpose:string){await user.type(screen.getByRole("textbox",{name:"用途"}),purpose);await user.type(screen.getByRole("textbox",{name:"内容"}),`内容 ${purpose}`);}
async function save(user:ReturnType<typeof userEvent.setup>){await user.click(screen.getByRole("button",{name:"登记版本化记录"}));await screen.findByText("教学记录已保存；仍为不计分的人工作业记录。");}
it("SIMULATED complete requirement/proposal/delivery/teachback/feedback/revision/redelivery sends the actual parent IDs",async()=>{
 const user=userEvent.setup();render(<Harness/>);await chooseSource(user);await user.selectOptions(screen.getByLabelText("记录类型"),"requirement");await fill(user,"初始需求");await save(user);
 const requirement=creates[0];expect(requirement.parent_id).toBeNull();
 const stages=[{page:"表达方案",kind:"proposal",label:"方案"},{page:"交付与版本",kind:"delivery",label:"交付"},{page:"练习 / Teach-back",kind:"teach_back",label:"独立复述"},{page:"反馈与修订",kind:"feedback",label:"反馈"},{page:"反馈与修订",kind:"revision",label:"修订"},{page:"交付与版本",kind:"delivery",label:"再次交付"}];
 let delivery:Json|undefined, feedback:Json|undefined, previous=requirement;
 for(const stage of stages){await user.click(screen.getByRole("button",{name:stage.page}));await user.selectOptions(screen.getByLabelText("记录类型"),stage.kind);const parent=stage.kind==="feedback"?delivery!:stage.kind==="revision"?feedback!:previous;await user.selectOptions(screen.getByLabelText("父记录"),parent.record_id);await fill(user,stage.label);if(stage.kind==="feedback")await user.selectOptions(screen.getByLabelText("反馈分类"),"expression_fit");if(stage.kind==="teach_back")await user.click(screen.getByLabelText("使用了辅助（不自动判定行为者）"));await save(user);const saved=creates.at(-1)!;expect(saved.parent_id).toBe(parent.record_id);expect(saved.knowledge_id).toBe("knowledge_actual_v1");expect(saved.knowledge_version).toBe("knowledge_actual_v1");if(stage.kind==="delivery")delivery=saved;if(stage.kind==="feedback")feedback=saved;if(stage.kind==="teach_back"){expect(saved.assisted).toBe(true);expect(saved.assessment_id).toBeNull();}previous=saved;}
 expect(new Set(creates.map(row=>row.record_id)).size).toBe(7);expect(creates.every(row=>/^teaching_[A-Za-z0-9-]+$/.test(row.record_id))).toBe(true);expect(within(screen.getByRole("article",{name:"已保存教学记录"})).getByText(/not_scored/)).toBeInTheDocument();expect(bridge.call).not.toHaveBeenCalledWith("learning_review",expect.anything());
},15000);
it("persists incomplete preparation body without knowledge then keeps formal registration separate",async()=>{const user=userEvent.setup();render(<Harness/>);await user.type(screen.getByRole("textbox",{name:"内容"}),"只有不完整准备正文");await user.click(screen.getByRole("button",{name:"保存准备正文草稿"}));await screen.findByText(/准备正文已保存并读回/);expect(bridge.call).toHaveBeenCalledWith("document_create",{body:{create_request_id:expect.stringMatching(/^preparation_[A-Za-z0-9_-]+$/),title:"教学准备草稿",editor_json:{type:"doc",content:[{type:"paragraph",content:[{type:"text",text:"只有不完整准备正文"}]}]}}});expect(bridge.call).toHaveBeenCalledWith("document_get",{document_id:"preparation_real_id"});expect(creates).toHaveLength(0);await user.click(screen.getByRole("button",{name:"登记版本化记录"}));await screen.findByText(/操作未确认完成/);expect(creates).toHaveLength(0);});
it("uncertain create retries the identical client record and frozen content",async()=>{const original=bridge.call.getMockImplementation()!;let first=true;bridge.call.mockImplementation(async(op:string,p:Json)=>{if(op==="teaching_create"&&first){first=false;creates.push(p.body);records.push(p.body);throw new Error("reply lost after persistence");}return original(op,p);});const user=userEvent.setup();render(<Harness/>);await chooseSource(user);await user.selectOptions(screen.getByLabelText("记录类型"),"requirement");await fill(user,"不确定保存");await user.click(screen.getByRole("button",{name:"登记版本化记录"}));await screen.findByText(/上次写入尚未确认/);expect(screen.getByRole("textbox",{name:"内容"})).toBeDisabled();await user.click(screen.getByRole("button",{name:"重试同一记录"}));await screen.findByText("已读回同一客户端记录，未重复创建。");expect(creates).toHaveLength(2);expect(creates[0]).toEqual(creates[1]);expect(records).toHaveLength(1);});
it("cannot derive from a withdrawn parent or substitute arbitrary parent IDs",async()=>{records=[record("withdrawn_requirement")];withdrawn.add(records[0].record_id);const user=userEvent.setup();render(<Harness initial="09"/>);await screen.findByText(/本页尚无已保存记录/);expect(screen.queryByRole("option",{name:"需求 · 目的 withdrawn_requirement"})).not.toBeInTheDocument();await chooseSource(user);await fill(user,"无父方案");await user.click(screen.getByRole("button",{name:"登记版本化记录"}));await screen.findByText(/操作未确认完成/);expect(creates).toHaveLength(0);});
it("failed list remains a failure and is never empty success",async()=>{bridge.call.mockRejectedValue(new Error("Core refused actor"));render(<Harness/>);await screen.findByText("教学记录读取失败；不会把失败显示为空列表。");expect(screen.queryByText(/本页尚无已保存记录/)).not.toBeInTheDocument();});
it("refresh failure hides a previous empty-success statement instead of labeling the failed read empty",async()=>{const user=userEvent.setup();render(<Harness/>);await screen.findByText(/本页尚无已保存记录/);bridge.call.mockRejectedValue(new Error("Core unavailable on refresh"));await user.click(screen.getByRole("button",{name:"刷新教学记录"}));await screen.findByText("教学记录读取失败；不会把失败显示为空列表。");expect(screen.queryByText(/本页尚无已保存记录/)).not.toBeInTheDocument();});
it("withdraw cancellation writes nothing; confirmation uses the actual selected ID and reads back withdrawn",async()=>{records=[record("req_live")];const user=userEvent.setup();render(<Harness/>);await user.click(await screen.findByRole("button",{name:"需求 · 目的 req_live"}));await user.click(screen.getByRole("button",{name:"审阅撤回记录"}));await user.click(screen.getByRole("button",{name:"取消撤回"}));expect(bridge.call).not.toHaveBeenCalledWith("teaching_withdraw",expect.anything());await user.click(screen.getByRole("button",{name:"审阅撤回记录"}));await user.type(screen.getByLabelText("撤回原因"),"人工审阅后撤回");await user.click(screen.getByRole("button",{name:"确认撤回"}));await screen.findByText(/撤回已读回/);const args=bridge.call.mock.calls.find(([op])=>op==="teaching_withdraw")![1];expect(args.body.record_id).toBe("req_live");expect(args.body.reason).toBe("人工审阅后撤回");expect(withdrawn.has("req_live")).toBe(true);});
it("file JSON requires Core preview and separate confirmation, imports exact selected bundle without running material",async()=>{const user=userEvent.setup();render(<Harness initial="16"/>);const bundle={schema:"archeaxis.teaching-exchange/v2",records:[{...record("external_record"),producer_kind:"external_material"}],package_sha256:"b".repeat(64)};const file=new File([JSON.stringify(bundle)],"manual.json",{type:"application/json"});Object.defineProperty(file,"text",{value:async()=>JSON.stringify(bundle)});await user.upload(screen.getByLabelText("选择人工交换 JSON"),file);await screen.findByText(/已读取用户选择的JSON/);await user.click(screen.getByRole("button",{name:"Core 预检交换包"}));await screen.findByRole("alertdialog",{name:"确认人工交换导入"});expect(bridge.call).not.toHaveBeenCalledWith("teaching_import",expect.anything());await user.click(screen.getByRole("button",{name:"确认人工导入"}));await screen.findByText(/人工导入已读回 1 条/);expect(bridge.call).toHaveBeenCalledWith("teaching_import_preview",{body:bundle});expect(bridge.call).toHaveBeenCalledWith("teaching_import",{body:bundle});expect(bridge.call.mock.calls.some(([op])=>["job_execute","learning_review","assessment_create"].includes(op))).toBe(false);});
it("new file invalidates an old delayed preview and cannot import the wrong bundle",async()=>{let resolvePreview:(v:unknown)=>void=()=>{};const original=bridge.call.getMockImplementation()!;bridge.call.mockImplementation((op:string,p:Json)=>op==="teaching_import_preview"?new Promise(resolve=>{resolvePreview=resolve;}):original(op,p));const user=userEvent.setup();render(<Harness initial="16"/>);const bundle={schema:"archeaxis.teaching-exchange/v2",records:[record("external_record")],package_sha256:"c".repeat(64)};const file=new File([JSON.stringify(bundle)],"manual.json",{type:"application/json"});Object.defineProperty(file,"text",{value:async()=>JSON.stringify(bundle)});await user.upload(screen.getByLabelText("选择人工交换 JSON"),file);await user.click(screen.getByRole("button",{name:"Core 预检交换包"}));expect(screen.getByLabelText("选择人工交换 JSON")).toBeDisabled();resolvePreview({valid:true,record_count:1,duplicate_count:0,package_sha256:bundle.package_sha256});await screen.findByRole("alertdialog",{name:"确认人工交换导入"});const second={...bundle,package_sha256:"d".repeat(64),records:[record("second_external")]};const other=new File([JSON.stringify(second)],"second.json",{type:"application/json"});Object.defineProperty(other,"text",{value:async()=>JSON.stringify(second)});fireEvent.change(screen.getByLabelText("选择人工交换 JSON"),{target:{files:[other]}});await waitFor(()=>expect(screen.queryByRole("alertdialog",{name:"确认人工交换导入"})).not.toBeInTheDocument());expect(bridge.call).not.toHaveBeenCalledWith("teaching_import",expect.anything());});
it("corrupt JSON never reaches import or preview",async()=>{const user=userEvent.setup();render(<Harness initial="16"/>);const bad=new File(["{"],"bad.json",{type:"application/json"});Object.defineProperty(bad,"text",{value:async()=>"{"});await user.upload(screen.getByLabelText("选择人工交换 JSON"),bad);await screen.findByText("交换JSON读取失败；未导入。");expect(screen.getByRole("button",{name:"Core 预检交换包"})).toBeDisabled();expect(bridge.call).not.toHaveBeenCalledWith("teaching_import_preview",expect.anything());});
it("binds Teach-back to the real parent course/knowledge assessment without inventing a score",async()=>{records=[{...record("delivery_assessed","delivery","proposal_actual"),course_id:"course_actual"}];const original=bridge.call.getMockImplementation()!;bridge.call.mockImplementation((op:string,p:Json)=>{
 if(op==="course_get")return Promise.resolve({stale:false,manifest:{manifest_id:"course_actual",artifacts:[{artifact_id:"lesson_actual",artifact_type:"lesson",renderer:"native-lesson"}]},bindings:[{knowledge_id:"knowledge_actual_v1",knowledge_version:"knowledge_actual_v1"}]});
 if(op==="assessment_get")return Promise.resolve({assessment_id:"assessment_actual",knowledge_id:"knowledge_actual_v1",knowledge_version:"knowledge_actual_v1",item_key:"course:course_actual:artifact:lesson_actual"});return original(op,p);
 });const user=userEvent.setup();render(<Harness initial="11"/>);await waitFor(()=>expect(screen.getByRole("option",{name:"交付 · 目的 delivery_assessed"})).toBeInTheDocument());await user.selectOptions(screen.getByLabelText("父记录"),"delivery_assessed");await user.click(screen.getByRole("button",{name:"核对父课程并读取练习入口"}));await user.click(screen.getByRole("button",{name:"读取绑定的真实学习问题"}));await screen.findByText(/已读取真实学习问题身份/);await user.click(screen.getByRole("button",{name:"打开真实练习队列"}));expect(screen.getByText("真实练习入口 course:course_actual:artifact:lesson_actual")).toBeInTheDocument();await fill(user,"有真实问题的复述");await save(user);expect(creates[0]).toMatchObject({parent_id:"delivery_assessed",course_id:"course_actual",knowledge_id:"knowledge_actual_v1",assessment_id:"assessment_actual",assisted:false});expect(bridge.call).toHaveBeenCalledWith("assessment_get",{item_key:"course:course_actual:artifact:lesson_actual"});expect(bridge.call).not.toHaveBeenCalledWith("learning_review",expect.anything());
});
it("cannot attach an assessment whose immutable knowledge differs",async()=>{records=[{...record("delivery_assessed","delivery","proposal_actual"),course_id:"course_actual"}];const original=bridge.call.getMockImplementation()!;bridge.call.mockImplementation((op:string,p:Json)=>op==="course_get"?Promise.resolve({stale:false,manifest:{manifest_id:"course_actual",artifacts:[{artifact_id:"lesson_actual",artifact_type:"lesson",renderer:"native-lesson"}]},bindings:[{knowledge_id:"knowledge_actual_v1",knowledge_version:"knowledge_actual_v1"}]}):op==="assessment_get"?Promise.resolve({assessment_id:"wrong_assessment",knowledge_id:"other",knowledge_version:"other"}):original(op,p));const user=userEvent.setup();render(<Harness initial="11"/>);await waitFor(()=>expect(screen.getByRole("option",{name:"交付 · 目的 delivery_assessed"})).toBeInTheDocument());await user.selectOptions(screen.getByLabelText("父记录"),"delivery_assessed");await user.click(screen.getByRole("button",{name:"核对父课程并读取练习入口"}));await user.click(screen.getByRole("button",{name:"读取绑定的真实学习问题"}));await screen.findByText(/操作未确认完成/);expect(screen.queryByText(/wrong_assessment/)).not.toBeInTheDocument();});
it("late source response cannot replace state after an external semantic page change",async()=>{let resolve:(value:unknown)=>void=()=>{};const original=bridge.call.getMockImplementation()!;bridge.call.mockImplementation((op:string,p:Json)=>op==="search"?new Promise(done=>{resolve=done;}):original(op,p));const user=userEvent.setup();const host=render(<CanonicalTeachingSpace pageId="08"/>);await user.click(screen.getByRole("button",{name:"搜索来源知识"}));host.rerender(<CanonicalTeachingSpace pageId="09"/>);resolve({items:[{knowledge_id:"late_id",head:"过期来源响应"}]});await waitFor(()=>expect(screen.getByRole("button",{name:"搜索来源知识"})).toBeEnabled());expect(screen.queryByRole("button",{name:"过期来源响应"})).not.toBeInTheDocument();});
it("Core actor refusal keeps the exact uncertain record for retry and never shows persisted success",async()=>{const original=bridge.call.getMockImplementation()!;bridge.call.mockImplementation((op:string,p:Json)=>op==="teaching_create"?Promise.reject(new Error("human actor permission refused")):original(op,p));const user=userEvent.setup();render(<Harness/>);await chooseSource(user);await user.selectOptions(screen.getByLabelText("记录类型"),"requirement");await fill(user,"权限拒绝记录");await user.click(screen.getByRole("button",{name:"登记版本化记录"}));await screen.findByText(/上次写入尚未确认/);expect(screen.queryByText("教学记录已保存；仍为不计分的人工作业记录。")).not.toBeInTheDocument();expect(records).toHaveLength(0);expect(screen.getByRole("button",{name:"重试同一记录"})).toBeEnabled();});
it("conflicting package refused by Core preview never enables confirmation",async()=>{const original=bridge.call.getMockImplementation()!;bridge.call.mockImplementation((op:string,p:Json)=>op==="teaching_import_preview"?Promise.reject(new Error("record identity conflict")):original(op,p));const user=userEvent.setup();render(<Harness initial="16"/>);const bundle={schema:"archeaxis.teaching-exchange/v2",records:[record("conflicting_id")],package_sha256:"e".repeat(64)};const file=new File([JSON.stringify(bundle)],"conflict.json",{type:"application/json"});Object.defineProperty(file,"text",{value:async()=>JSON.stringify(bundle)});await user.upload(screen.getByLabelText("选择人工交换 JSON"),file);await user.click(screen.getByRole("button",{name:"Core 预检交换包"}));await screen.findByText(/操作未确认完成/);expect(screen.queryByRole("button",{name:"确认人工导入"})).not.toBeInTheDocument();expect(bridge.call).not.toHaveBeenCalledWith("teaching_import",expect.anything());});
it("duplicate import displays Core's duplicate receipt rather than pretending a second new record",async()=>{const external=record("duplicate_external");records=[external];const original=bridge.call.getMockImplementation()!;bridge.call.mockImplementation((op:string,p:Json)=>op==="teaching_import_preview"?Promise.resolve({valid:true,record_count:1,duplicate_count:1,package_sha256:p.body.package_sha256}):op==="teaching_import"?Promise.resolve({items:[view(external)],duplicate_count:1,package_sha256:p.body.package_sha256}):original(op,p));const user=userEvent.setup();render(<Harness initial="16"/>);const bundle={schema:"archeaxis.teaching-exchange/v2",records:[external],package_sha256:"f".repeat(64)};const file=new File([JSON.stringify(bundle)],"duplicate.json",{type:"application/json"});Object.defineProperty(file,"text",{value:async()=>JSON.stringify(bundle)});await user.upload(screen.getByLabelText("选择人工交换 JSON"),file);await user.click(screen.getByRole("button",{name:"Core 预检交换包"}));await user.click(screen.getByRole("button",{name:"确认人工导入"}));await screen.findByText(/人工导入已读回 1 条，重复 1 条/);expect(records).toHaveLength(1);});

it("preparation lost create ack retries stable request and original snapshot without duplicate documents",async()=>{
 const original=bridge.call.getMockImplementation()!;let first=true;const attempts:Json[]=[];const persisted=new Map<string,Json>();
 bridge.call.mockImplementation(async(op:string,p:Json)=>{if(op==="document_create"){attempts.push(p.body);const key=p.body.create_request_id;if(!persisted.has(key))persisted.set(key,{document_id:"one-persisted-preparation",version:1});if(first){first=false;throw new Error("lost ack after commit");}return persisted.get(key);}return original(op,p);});
 const user=userEvent.setup();render(<Harness/>);await user.type(screen.getByRole("textbox",{name:"内容"}),"保存原文");await user.click(screen.getByRole("button",{name:"保存准备正文草稿"}));await screen.findByText(/操作未确认完成/);
 await user.type(screen.getByRole("textbox",{name:"内容"})," 新编辑仍未保存");await user.click(screen.getByRole("button",{name:"保存准备正文草稿"}));await screen.findByText(/准备正文已保存并读回/);expect(attempts).toHaveLength(2);expect(attempts[0]).toEqual(attempts[1]);expect(persisted.size).toBe(1);expect(screen.getByRole("textbox",{name:"内容"})).toHaveValue("保存原文 新编辑仍未保存");
});
it("preparation lost readback reuses exact create identity",async()=>{
 const original=bridge.call.getMockImplementation()!;let first=true;const attempts:Json[]=[];bridge.call.mockImplementation(async(op:string,p:Json)=>{if(op==="document_create"){attempts.push(p.body);return {document_id:"preparation_real_id",version:1};}if(op==="document_get"&&first){first=false;throw new Error("readback lost");}return original(op,p);});const user=userEvent.setup();render(<Harness/>);await user.type(screen.getByRole("textbox",{name:"内容"}),"保留正文");await user.click(screen.getByRole("button",{name:"保存准备正文草稿"}));await screen.findByText(/操作未确认完成/);await user.click(screen.getByRole("button",{name:"保存准备正文草稿"}));await screen.findByText(/准备正文已保存并读回/);expect(attempts[0]).toEqual(attempts[1]);
});
it("withdrawal dialog traps Tab and Escape restores trigger without mutation",async()=>{
 records=[record("withdraw-me")];const user=userEvent.setup();render(<Harness/>);await user.click(await screen.findByRole("button",{name:"需求 · 目的 withdraw-me"}));const trigger=screen.getByRole("button",{name:"审阅撤回记录"});await user.click(trigger);const dialog=await screen.findByRole("alertdialog",{name:"确认撤回教学记录"});expect(dialog).toContainElement(document.activeElement as HTMLElement);await user.click(within(dialog).getByRole("button",{name:"取消撤回"}));await waitFor(()=>expect(trigger).toHaveFocus());await user.click(trigger);const cancel=screen.getByRole("button",{name:"取消撤回"});cancel.focus();await user.tab();expect(screen.getByRole("textbox",{name:"撤回原因"})).toHaveFocus();await user.keyboard("{Escape}");await waitFor(()=>expect(trigger).toHaveFocus());expect(bridge.call).not.toHaveBeenCalledWith("teaching_withdraw",expect.anything());
});
it("exchange dialog Escape and cancel return to preview trigger without import",async()=>{
 const user=userEvent.setup();render(<Harness initial="16"/>);const b={schema:"archeaxis.teaching-exchange/v2",records:[record("external")],package_sha256:"e".repeat(64)};const f=new File([JSON.stringify(b)],"manual.json",{type:"application/json"});Object.defineProperty(f,"text",{value:async()=>JSON.stringify(b)});await user.upload(screen.getByLabelText("选择人工交换 JSON"),f);const trigger=screen.getByRole("button",{name:"Core 预检交换包"});await user.click(trigger);const d=await screen.findByRole("alertdialog",{name:"确认人工交换导入"});expect(d).toContainElement(document.activeElement as HTMLElement);screen.getByRole("button",{name:"取消导入"}).focus();await user.tab();expect(screen.getByRole("button",{name:"确认人工导入"})).toHaveFocus();await user.keyboard("{Escape}");await waitFor(()=>expect(trigger).toHaveFocus());await user.click(trigger);await user.click(await screen.findByRole("button",{name:"取消导入"}));await waitFor(()=>expect(trigger).toHaveFocus());expect(bridge.call).not.toHaveBeenCalledWith("teaching_import",expect.anything());
});
it.each(["{bad JSON",JSON.stringify({schema:"future.exchange/v99",extra:{unknown:"完整😀"}})])("downloads exact original rejected File without canonical import: %s",async(raw)=>{
 const make=vi.fn(()=>"blob:raw-file"),revoke=vi.fn(),click=vi.spyOn(HTMLAnchorElement.prototype,"click").mockImplementation(()=>{});Object.defineProperty(URL,"createObjectURL",{configurable:true,value:make});Object.defineProperty(URL,"revokeObjectURL",{configurable:true,value:revoke});const user=userEvent.setup();render(<Harness initial="16"/>);const f=new File([raw],"unknown-original.json",{type:"application/json"});Object.defineProperty(f,"text",{value:async()=>raw});await user.upload(screen.getByLabelText("选择人工交换 JSON"),f);await screen.findByText("交换JSON读取失败；未导入。");await user.click(screen.getByRole("button",{name:"下载所选原始交换文件"}));expect(make).toHaveBeenCalledWith(f);expect(click).toHaveBeenCalledTimes(1);expect(revoke).toHaveBeenCalledWith("blob:raw-file");expect(bridge.call.mock.calls.some(([op])=>["teaching_import","teaching_import_preview","document_create","source_import"].includes(op))).toBe(false);click.mockRestore();
});
