import { webcrypto } from "node:crypto";
import { beforeEach, expect, it, vi } from "vitest";
import { render, screen, fireEvent, waitFor, act } from "@testing-library/react";
import { CanonicalRelationSpace } from "../spaces/CanonicalRelationSpace";
const bridge = vi.hoisted(() => ({ call: vi.fn() }));
vi.mock("../api/core", () => ({ coreCommand: bridge.call }));
vi.mock("../design-system/AaosPrimitives", () => ({ AaosDialog: ({ open, children, title }: any) => open ? <div role="dialog" aria-label={title}>{children}</div> : null }));
type J = Record<string, any>;
let docs: Map<string, J>, writes: J[], incomplete: boolean;
function doc(id: string, version = 1): J { return { document_id: id, title: id, version, source_id: null, source_revision: null, content_sha256: "a".repeat(64), blocks: [], text_projection: "body", editor_json: { type: "doc", attrs: { unknown: { retained: [1, 2] }, archeaxis_relations: { schema: "archeaxis.relations/v1", relations: [] } }, content: [{ type: "future_node", attrs: { block_id: "stable_body", unknown: true }, opaque: "retain" }] } }; }
const target = { kind: "document", document_id: "doc_b", version: 3, block_id: "old_block" };
function projection(d: J): J { return { schema: "archeaxis.relation-projection/v1", snapshot_sha256: "b".repeat(64), center: { document_id: d.document_id, version: d.version, content_sha256: d.content_sha256 }, scope: "current_source_versions_to_pinned_center", derived_only: true, nodes: [{ key: "a", reference: { kind: "document", document_id: d.document_id, version: d.version }, status: "resolved", object: {} }, { key: "b", reference: target, status: "resolved", object: {} }], edges: [{ id: "edge", from: "a", to: "b", direction: "outgoing", relation: { id: "relation_existing", kind: "supports", label: "证据支持", target }, source_snapshot: { document_id: d.document_id, version: d.version, content_sha256: d.content_sha256 } }], unsupported_sources: [], scan: { scanned: 20, next_cursor: incomplete ? "source20" : null, complete: !incomplete } }; }
beforeEach(() => { vi.stubGlobal("crypto", webcrypto); docs = new Map([['doc_a', doc('doc_a')], ['doc_b', doc('doc_b', 5)]]); writes = []; incomplete = false; bridge.call.mockReset(); bridge.call.mockImplementation(async (op: string, p: J = {}) => {
  if (op === 'documents_list') return { documents: [...docs.values()], snapshot_count: docs.size, next_cursor: null };
  if (op === 'document_get') return structuredClone(docs.get(p.document_id));
  if (op === 'document_version') return doc(p.document_id, p.version);
  if (op === 'document_graph') return projection(doc(p.document_id, p.version));
  if (op === 'document_create') { writes.push(structuredClone(p)); const bytes = await webcrypto.subtle.digest('SHA-256', new TextEncoder().encode(p.body.create_request_id)); const id = 'doc_req_' + Array.from(new Uint8Array(bytes)).map(x => x.toString(16).padStart(2,'0')).join(''); let d = docs.get(id); if (!d) { d = { ...doc(id), title:p.body.title, editor_json: structuredClone(p.body.editor_json) }; docs.set(d.document_id, d); } return structuredClone(d); }
  if (op === 'document_draft') { writes.push(structuredClone(p)); const d = docs.get(p.document_id)!; if (d.version !== p.body.expected_version) throw new Error('409'); const next = { ...d, version: d.version + 1, editor_json: structuredClone(p.body.editor_json) }; docs.set(p.document_id, next); return structuredClone(next); }
  throw new Error(op);
}); });
async function open(id = 'doc_a') { fireEvent.click(await screen.findByRole('button', { name: new RegExp('^' + id + ' ·') })); await screen.findByText(/关系投影已读取/); }
function add(label = 'NEW') { fireEvent.change(screen.getByLabelText('关系说明'), { target: { value: label } }); fireEvent.change(screen.getByLabelText('目标对象ID'), { target: { value: 'doc_b' } }); fireEvent.change(screen.getByLabelText('固定目标版本'), { target: { value: '3' } }); fireEvent.click(screen.getByRole('button', { name: '加入关系草稿' })); }
it('graph and fallback list retain exact pinned target despite current target version5', async () => { const jump = vi.fn(); render(<CanonicalRelationSpace onOpenDocument={jump}/>); await open(); fireEvent.click(screen.getByRole('button', { name: '图形不可用，切换列表' })); expect(screen.queryByLabelText('同版本关系图')).toBeNull(); fireEvent.click(screen.getByRole('button', { name: /打开固定对象 doc_b/ })); expect(jump).toHaveBeenCalledWith('doc_b', 3, 'old_block'); expect(bridge.call).toHaveBeenCalledWith('document_graph', { document_id: 'doc_a', version: 1 }); });
it('incomplete scans cannot become a claim that the whole library has no relations', async () => { incomplete = true; const call = bridge.call.getMockImplementation()!; bridge.call.mockImplementation(async (op: string, p: J) => { const r = await call(op, p); if (op === 'document_graph') r.edges = []; return r; }); render(<CanonicalRelationSpace onOpenDocument={vi.fn()}/>); await open(); expect(screen.getByText(/扫描尚未完成，不能断言全库无关系/)).toBeVisible(); expect(screen.getByText('此页没有关系记录；仅限上述扫描范围。')).toBeVisible(); fireEvent.click(screen.getByRole('button', { name: '读取下一页反链' })); await waitFor(() => expect(bridge.call).toHaveBeenCalledWith('document_graph', { document_id: 'doc_a', version: 1, cursor: 'source20' })); });
it('preserves unknown envelope, body and stable block IDs on relation-only save', async () => { const prior = structuredClone(docs.get('doc_a')!.editor_json); render(<CanonicalRelationSpace onOpenDocument={vi.fn()}/>); await open(); add(); fireEvent.click(screen.getByRole('button', { name: '保存关系草稿' })); await screen.findByText('关系已保存并读回核对。'); expect(writes[0].body.expected_version).toBe(1); expect(writes[0].body.editor_json.content).toEqual(prior.content); expect(writes[0].body.editor_json.attrs.unknown).toEqual(prior.attrs.unknown); expect(writes[0].body.editor_json.attrs.archeaxis_relations.relations[0].target).toEqual({ kind: 'document', document_id: 'doc_b', version: 3 }); });
it('first-create lost acknowledgement retries frozen key/payload and preserves later editing', async () => { const call = bridge.call.getMockImplementation()!; let lost = true; bridge.call.mockImplementation(async (op: string, p: J) => { const r = await call(op, p); if (op === 'document_create' && lost) { lost = false; throw new Error('response lost'); } return r; }); render(<CanonicalRelationSpace onOpenDocument={vi.fn()}/>); add('FIRST'); fireEvent.click(screen.getByRole('button', { name: '保存关系草稿' })); await screen.findByRole('alert'); add('LATER'); fireEvent.click(screen.getByRole('button', { name: '重试冻结保存' })); await screen.findByText('已保存发送时的版本；随后编辑仍是未保存草稿。'); expect(writes).toHaveLength(2); expect(writes[0]).toEqual(writes[1]); expect(docs.size).toBe(3); expect(screen.getByLabelText('关系草稿')).toHaveTextContent('LATER'); });
it('409 preserves draft and fixed expected version while showing latest read-only comparison', async () => { render(<CanonicalRelationSpace onOpenDocument={vi.fn()}/>); await open(); add('UNSAVED'); docs.set('doc_a', doc('doc_a', 2)); fireEvent.click(screen.getByRole('button', { name: '保存关系草稿' })); await screen.findByRole('alert'); fireEvent.click(screen.getByRole('button', { name: '核对最新版本（保留草稿）' })); await screen.findByText(/最新版本不同，仅只读比较/); fireEvent.click(screen.getByRole('button', { name: '返回当前草稿' })); expect(screen.getByLabelText('关系草稿')).toHaveTextContent('UNSAVED'); expect(writes[0].body.expected_version).toBe(1); });
it('cancelling switch and rerendering a theme retains relation draft', async () => { const v = render(<CanonicalRelationSpace onOpenDocument={vi.fn()}/>); await open(); add('DRAFT'); fireEvent.click(screen.getByRole('button', { name: /^doc_b ·/ })); fireEvent.click(screen.getByRole('button', { name: '取消切换' })); document.documentElement.dataset.aaosTheme = 'white'; v.rerender(<CanonicalRelationSpace onOpenDocument={vi.fn()}/>); expect(screen.getByLabelText('关系草稿')).toHaveTextContent('DRAFT'); });
it('unknown relation schema is preserved read-only without write conversion', async () => { docs.get('doc_a')!.editor_json.attrs.archeaxis_relations = { schema: 'archeaxis.relations/v99', opaque: [1, 2] }; render(<CanonicalRelationSpace onOpenDocument={vi.fn()}/>); await open(); expect(screen.getByRole('button', { name: '保存关系草稿' })).toBeDisabled(); expect(screen.getByText(/保留的原始文档/)).toBeVisible(); expect(writes).toHaveLength(0); });
it('graph failure is an error and not an empty-data success', async () => { const call = bridge.call.getMockImplementation()!; bridge.call.mockImplementation((op: string, p: J) => op === 'document_graph' ? Promise.reject(new Error('503')) : call(op, p)); render(<CanonicalRelationSpace onOpenDocument={vi.fn()}/>); fireEvent.click(await screen.findByRole('button', { name: /^doc_a ·/ })); expect(await screen.findByRole('alert')).toHaveTextContent('未报告无关系'); expect(screen.queryByText('此页没有关系记录；仅限上述扫描范围。')).toBeNull(); });

it('unified reference callback passes exact source snapshot and pinned block without current-library fallback', async () => { const jump = vi.fn(); render(<CanonicalRelationSpace onOpenReference={jump}/>); await open(); fireEvent.click(screen.getByRole('button', { name: 'doc_a v1' })); expect(jump).toHaveBeenCalledWith({ kind: 'document', document_id: 'doc_a', version: 1 }); fireEvent.click(screen.getByRole('button', { name: /打开固定对象 doc_b/ })); expect(jump).toHaveBeenLastCalledWith(target); });

it('history loaded after a new relation edit cannot hide the working draft behind read-only UI', async () => { let resolve!: (d: J) => void; const call=bridge.call.getMockImplementation()!; bridge.call.mockImplementation((op:string,p:J)=>op==='document_version'?new Promise(r=>{resolve=r;}):call(op,p)); render(<CanonicalRelationSpace onOpenReference={vi.fn()}/>); await open(); fireEvent.click(screen.getByRole('button',{name:'读取历史关系（只读）'})); add('EDIT AFTER REQUEST'); await act(async()=>{resolve(doc('doc_a',1));}); expect(screen.queryByText(/只读比较 v1/)).toBeNull(); expect(screen.getByLabelText('关系草稿')).toHaveTextContent('EDIT AFTER REQUEST'); expect(screen.getByLabelText('目标对象ID')).toBeEnabled(); });
it('a pending collection edit prevents entering a historical view', async () => { render(<CanonicalRelationSpace onOpenReference={vi.fn()} renderCollection={(_d,_e,_change,onPending)=><button onClick={()=>onPending(true)}>Pending collection input</button>}/>); await open(); fireEvent.click(screen.getByRole('button',{name:'Pending collection input'})); fireEvent.click(screen.getByRole('button',{name:'读取历史关系（只读）'})); expect(bridge.call.mock.calls.filter(x=>x[0]==='document_version')).toHaveLength(0); expect(screen.getByRole('alert')).toHaveTextContent('当前输入保留'); });
it('a stale history failure cannot replace the status of a newly opened object', async () => { let reject!: (e:Error)=>void; const call=bridge.call.getMockImplementation()!; bridge.call.mockImplementation((op:string,p:J)=>op==='document_version'?new Promise((_r,j)=>{reject=j;}):call(op,p)); render(<CanonicalRelationSpace onOpenReference={vi.fn()}/>); await open(); fireEvent.click(screen.getByRole('button',{name:'读取历史关系（只读）'})); await open('doc_b'); await act(async()=>{reject(new Error('old history unavailable'));}); expect(screen.queryByRole('alert')).toBeNull(); expect(screen.getByRole('status')).toHaveTextContent('关系投影已读取'); });
it('returning to draft cancels an in-flight replacement history request', async () => { render(<CanonicalRelationSpace onOpenReference={vi.fn()}/>); await open(); fireEvent.click(screen.getByRole('button',{name:'读取历史关系（只读）'})); await screen.findByText(/只读比较 v1/); let resolve!:(d:J)=>void; const call=bridge.call.getMockImplementation()!; bridge.call.mockImplementation((op:string,p:J)=>op==='document_version'?new Promise(r=>{resolve=r;}):call(op,p)); fireEvent.change(screen.getByLabelText('历史版本'),{target:{value:'2'}}); fireEvent.click(screen.getByRole('button',{name:'读取历史关系（只读）'})); fireEvent.click(screen.getByRole('button',{name:'返回当前草稿'})); await act(async()=>{resolve(doc('doc_a',2));}); expect(screen.queryByText(/只读比较 v2/)).toBeNull(); expect(screen.getByLabelText('目标对象ID')).toBeEnabled(); });
for (const corrupt of ['id','title','source'] as const) it(`create ${corrupt} mismatch with identical body/version cannot be accepted`, async()=>{const call=bridge.call.getMockImplementation()!;bridge.call.mockImplementation(async(op:string,p:J)=>{const r=await call(op,p);if(op==='document_create'){if(corrupt==='id'){r.document_id='wrong_identity';docs.set('wrong_identity',structuredClone(r));}if(corrupt==='title')r.title='wrong title';if(corrupt==='source')r.source_id='wrong source';}return r;});render(<CanonicalRelationSpace onOpenReference={vi.fn()}/>);add('CREATE');fireEvent.click(screen.getByRole('button',{name:'保存关系草稿'}));expect(await screen.findByRole('alert')).toHaveTextContent('保存未确认');expect(screen.getByRole('button',{name:'重试冻结保存'})).toBeEnabled();expect(screen.getByLabelText('关系草稿')).toHaveTextContent('CREATE');});
