import { beforeEach, afterEach, expect, it, vi } from "vitest";
import { webcrypto } from "node:crypto";
import { documentRequestIdentity } from "../presentation/documentRequestIdentity";
import { act, fireEvent, render, screen, waitFor, within } from "@testing-library/react";
import { CanonicalResearchSpace, parseResearch, type ResearchValue } from "../spaces/CanonicalResearchSpace";
import type { DocumentDto } from "../api/generated/core-contract";
const bridge=vi.hoisted(()=>({call:vi.fn()}));vi.mock("../api/core",()=>({coreCommand:bridge.call}));
type J=Record<string,any>;
const value=(question:string):ResearchValue=>({schema:"archeaxis.research/v1",question,materials:[],hypotheses:[],methods:[],experiments:[],counterevidence:[],conclusions:[],unresolved:[]});
function dto(id:string,question:string,version=1):DocumentDto{return {document_id:id,title:id,version,content_sha256:"a".repeat(64),source_id:null,source_revision:null,text_projection:question,blocks:[{block_id:`block_${id}`,kind:"paragraph",ordinal:0,node_json:{type:"paragraph"},text_projection:"body",codec_status:"known"}],editor_json:{type:"doc",attrs:{ownerUnknown:{raw:"未修改的外层载荷"},archeaxis_research:value(question)},content:[{type:"ownerUnknown",attrs:{block_id:`block_${id}`},payload:{raw:"未知块原文\r\n保留 "}}]}};}
let docs:Map<string,DocumentDto>,requests:J[],original:(op:string,p:J)=>Promise<unknown>,events:boolean[];
beforeEach(()=>{vi.stubGlobal("crypto",webcrypto);docs=new Map([["doc_a",dto("doc_a","A")],["doc_b",dto("doc_b","B")]]);requests=[];events=[];bridge.call.mockReset();original=async(op:string,p:J={})=>{
 if(op==="documents_list")return {documents:[...docs.values()],next_cursor:null,snapshot_count:docs.size};
 if(op==="sources_list")return {sources:[{source_id:"source_actual",source_revision:"b".repeat(64),sha256:"b".repeat(64),original_name:"真实来源.txt",imported_at:"fixture"}]};
 if(op==="document_get")return structuredClone(docs.get(p.document_id));
 if(op==="document_version")return dto(p.document_id,"历史原文",p.version);
 if(op==="search")return {items:[],transforms:[],count:0,transform_count:0,documents:[],document_count:0};
 if(op==="document_create"){requests.push(structuredClone(p));const id=await documentRequestIdentity(p.body.create_request_id);let d=docs.get(id);if(!d){d={...dto(id,""),title:p.body.title,editor_json:structuredClone(p.body.editor_json)};docs.set(d.document_id,d);}return structuredClone(d);}
 if(op==="document_draft"){requests.push(structuredClone(p));const old=docs.get(p.document_id)!;if(old.version!==p.body.expected_version)throw new Error("409");const d={...old,version:old.version+1,editor_json:structuredClone(p.body.editor_json)};docs.set(d.document_id,d);return structuredClone(d);}
 throw new Error(`unimplemented fixture operation ${op}`);
};bridge.call.mockImplementation(original);});
afterEach(()=>{vi.restoreAllMocks();vi.unstubAllGlobals();});
async function openA(){fireEvent.click(await screen.findByRole("button",{name:"doc_a · 版本 1"}));await waitFor(()=>expect(screen.getByLabelText("研究问题")).toHaveValue("A"));}
function editQuestion(text:string){fireEvent.change(screen.getByLabelText("研究问题"),{target:{value:text}});}
async function save(){fireEvent.click(screen.getByRole("button",{name:"保存研究草稿"}));await screen.findByText("研究草稿已保存并读回；未变为核验或采用状态。");}
it("stores incomplete counterevidence and unresolved research without question, materials, course or adoption prerequisite",async()=>{
 render(<CanonicalResearchSpace/>);fireEvent.click(screen.getByRole("button",{name:"添加反证"}));fireEvent.change(screen.getByLabelText("反证 1"),{target:{value:"反例\n尚未查证"}});fireEvent.click(screen.getByRole("button",{name:"添加未决"}));fireEvent.change(screen.getByLabelText("未决 1"),{target:{value:"实验未做"}});await save();const stored=requests[0].body.editor_json.attrs.archeaxis_research;expect(stored.question).toBe("");expect(stored.materials).toEqual([]);expect(stored.counterevidence[0]).toMatchObject({text:"反例\n尚未查证",references:[]});expect(stored.unresolved[0].text).toBe("实验未做");expect(bridge.call.mock.calls.map(c=>c[0])).not.toContain("knowledge_review");expect(screen.getByText(/学术检索与 GraphRAG 当前未接通/)).toBeInTheDocument();
});
it("retains Chinese composition and all envelope/body unknown data through research edits and save",async()=>{
 const view=render(<CanonicalResearchSpace/>);await openA();const area=screen.getByLabelText("研究问题");fireEvent.compositionStart(area);editQuestion("中文输入\n第二行 ");fireEvent.keyDown(area,{key:"Enter",isComposing:true});fireEvent.compositionEnd(area);document.documentElement.dataset.aaosTheme="white";view.rerender(<CanonicalResearchSpace/>);expect(area).toHaveValue("中文输入\n第二行 ");await save();expect(requests[0].body.expected_version).toBe(1);expect(requests[0].body.editor_json.attrs.ownerUnknown).toEqual({raw:"未修改的外层载荷"});expect(requests[0].body.editor_json.content).toEqual((dto("doc_a","A").editor_json as J).content);
});
it("lost create acknowledgement retries exact frozen request while later content remains dirty",async()=>{
 let first=true;bridge.call.mockImplementation(async(op:string,p:J)=>{const result=await original(op,p);if(op==="document_create"&&first){first=false;throw new Error("lost ack");}return result;});render(<CanonicalResearchSpace/>);editQuestion("FIRST");fireEvent.click(screen.getByRole("button",{name:"保存研究草稿"}));await screen.findByRole("alert");editQuestion("LATER");fireEvent.click(screen.getByRole("button",{name:"重试冻结研究保存"}));await screen.findByText("发送时的研究版本已读回；随后编辑仍未保存。");expect(requests).toHaveLength(2);expect(requests[0]).toEqual(requests[1]);expect(requests[0].body.create_request_id).toMatch(/^research_/);expect(docs.size).toBe(3);expect(screen.getByLabelText("研究问题")).toHaveValue("LATER");await save();expect(requests[2].body.expected_version).toBe(1);expect(requests[2].body.editor_json.attrs.archeaxis_research.question).toBe("LATER");
});
it("late save receipt never replaces text edited after dispatch",async()=>{
 let resolve!:(value:unknown)=>void;bridge.call.mockImplementation(async(op:string,p:J)=>{const result=await original(op,p);if(op==="document_draft")await new Promise(r=>{resolve=r;});return result;});render(<CanonicalResearchSpace/>);await openA();editQuestion("SENT");fireEvent.click(screen.getByRole("button",{name:"保存研究草稿"}));await waitFor(()=>expect(requests).toHaveLength(1));editQuestion("LATER");await act(async()=>{resolve(null);});await screen.findByText("发送时的研究版本已读回；随后编辑仍未保存。");expect(screen.getByLabelText("研究问题")).toHaveValue("LATER");
});
it("keeps dirty buffers through cancelled and confirmed object switching",async()=>{
 render(<CanonicalResearchSpace/>);await openA();editQuestion("UNSAVED A");fireEvent.click(screen.getByRole("button",{name:"doc_b · 版本 1"}));fireEvent.click(screen.getByRole("button",{name:"取消切换"}));expect(screen.getByLabelText("研究问题")).toHaveValue("UNSAVED A");fireEvent.click(screen.getByRole("button",{name:"doc_b · 版本 1"}));fireEvent.click(screen.getByRole("button",{name:"保留草稿并切换"}));await waitFor(()=>expect(screen.getByLabelText("研究问题")).toHaveValue("B"));fireEvent.click(screen.getByRole("button",{name:"doc_a · 版本 1"}));expect(screen.getByLabelText("研究问题")).toHaveValue("UNSAVED A");
});
it("unknown research envelope remains complete readonly and cannot silently drop unknown fields in a rewrite",async()=>{
 const invalid=dto("doc_bad","original");(invalid.editor_json as J).attrs.archeaxis_research.future={source:"must survive"};docs.set("doc_bad",invalid);render(<CanonicalResearchSpace/>);fireEvent.click(await screen.findByRole("button",{name:"doc_bad · 版本 1"}));await screen.findByText("不支持的metadata保持完整原文，只读不转换。");expect(screen.getByRole("button",{name:"保存研究草稿"})).toBeDisabled();expect(requests).toEqual([]);expect((docs.get("doc_bad")!.editor_json as J).attrs.archeaxis_research.future).toEqual({source:"must survive"});
});
it("pending material input guards save, history and switch; cancellation does not clear existing content dirty",async()=>{
 const listener=(event:Event)=>events.push((event as CustomEvent<boolean>).detail);window.addEventListener("archeaxis-draft-dirty",listener);try{render(<CanonicalResearchSpace/>);await openA();editQuestion("CONTENT DIRTY");const saveButton=screen.getByRole("button",{name:"保存研究草稿"}),historyButton=screen.getByRole("button",{name:"读取研究历史"});fireEvent.click(screen.getByRole("button",{name:"添加材料或待整理说明"}));const dialog=await screen.findByRole("dialog",{name:"选择研究引用"});fireEvent.change(within(dialog).getByLabelText("待整理材料说明"),{target:{value:"未选择出处"}});expect(events.at(-1)).toBe(true);fireEvent.click(saveButton);expect(requests).toHaveLength(0);fireEvent.click(historyButton);expect(bridge.call.mock.calls.map(c=>c[0])).not.toContain("document_version");fireEvent.click(within(dialog).getByRole("button",{name:"取消引用选择"}));expect(events.at(-1)).toBe(true);expect(screen.getByLabelText("研究问题")).toHaveValue("CONTENT DIRTY");}finally{window.removeEventListener("archeaxis-draft-dirty",listener);}
});
it("an unbound material note can be preserved as unresolved draft without fabricating a reference",async()=>{
 render(<CanonicalResearchSpace/>);fireEvent.click(screen.getByRole("button",{name:"添加材料或待整理说明"}));const dialog=await screen.findByRole("dialog",{name:"选择研究引用"});fireEvent.change(within(dialog).getByLabelText("待整理材料说明"),{target:{value:"材料只记了题目，出处待补"}});fireEvent.click(within(dialog).getByRole("button",{name:"无来源说明先保留为未决草稿"}));expect(screen.getByLabelText("未决 1")).toHaveValue("材料只记了题目，出处待补");await save();expect(requests[0].body.editor_json.attrs.archeaxis_research.materials).toEqual([]);expect(requests[0].body.editor_json.attrs.archeaxis_research.unresolved[0].references).toEqual([]);
});
it("pins selected actual document version and block and opens it through exact callback",async()=>{
 const d=docs.get("doc_a")!;const r=(d.editor_json as J).attrs.archeaxis_research as ResearchValue;r.materials=[{id:"material_a",note:"绑定版本",reference:{kind:"document",document_id:"doc_b",version:1,block_id:"block_doc_b"}}];const open=vi.fn();render(<CanonicalResearchSpace onOpenDocument={open}/>);await openA();fireEvent.click(screen.getByRole("button",{name:"打开固定版本"}));expect(open).toHaveBeenCalledWith("doc_b",1,"block_doc_b");expect(bridge.call.mock.calls.map(c=>c[0])).not.toContain("knowledge_review");
});
it("conclusion sources and basis remain separate in UI and frozen payload",async()=>{
 render(<CanonicalResearchSpace/>);fireEvent.click(screen.getByRole("button",{name:"添加结论"}));fireEvent.change(screen.getByLabelText("结论 1"),{target:{value:"仅为作者结论"}});fireEvent.click(screen.getByRole("button",{name:"为结论 1添加来源"}));let dialog=await screen.findByRole("dialog",{name:"选择研究引用"});await waitFor(()=>expect(within(dialog).getByRole("option",{name:/真实来源/})).toBeInTheDocument());fireEvent.change(within(dialog).getByLabelText("引用原件"),{target:{value:"source_actual"}});fireEvent.click(within(dialog).getByRole("button",{name:"添加所选引用"}));fireEvent.click(screen.getByRole("button",{name:"为结论 1添加依据"}));dialog=await screen.findByRole("dialog",{name:"选择研究引用"});fireEvent.change(within(dialog).getByLabelText("引用文档"),{target:{value:"doc_b"}});await within(dialog).findByText(/将绑定 doc_b · 版本 1/);fireEvent.click(within(dialog).getByRole("button",{name:"添加所选引用"}));await save();const c=requests[0].body.editor_json.attrs.archeaxis_research.conclusions[0];expect(c.sources).toEqual([{kind:"source",source_id:"source_actual",sha256:"b".repeat(64)}]);expect(c.basis).toEqual([{kind:"document",document_id:"doc_b",version:1,block_id:null}]);expect(screen.getByRole("region",{name:"结论 1来源"})).toBeInTheDocument();expect(screen.getByRole("region",{name:"结论 1依据"})).toBeInTheDocument();
});
it("409 and list failure remain explicit errors while preserving author content",async()=>{
 bridge.call.mockImplementation(async(op:string,p:J)=>{if(op==="document_draft")throw new Error("409");return original(op,p);});render(<CanonicalResearchSpace/>);await openA();editQuestion("未丢中文");fireEvent.click(screen.getByRole("button",{name:"保存研究草稿"}));await screen.findByRole("alert");expect(screen.getByLabelText("研究问题")).toHaveValue("未丢中文");expect(screen.getByRole("button",{name:"重试冻结研究保存"})).toBeInTheDocument();
});
it("strict research parser rejects unknown fields and bad refs but accepts empty incomplete sections",()=>{
 const v=value("");expect(parseResearch(v)).toBe(v);expect(parseResearch({...v,verified:true})).toBeNull();expect(parseResearch({...v,materials:[{id:"m",note:"note",reference:{kind:"source",source_id:"s",sha256:"bad"}}]})).toBeNull();expect(parseResearch({...v,hypotheses:[{id:"a",text:"candidate",references:[],score:100}]})).toBeNull();expect(parseResearch({...v,conclusions:[{id:"x",text:"draft",sources:[],basis:[]},{id:"x",text:"duplicate",sources:[],basis:[]}]})).toBeNull();
});

it("lost draft acknowledgement reconciles committed exact version without a second write or losing later edits",async()=>{
 let first=true;bridge.call.mockImplementation(async(op:string,p:J)=>{const result=await original(op,p);if(op==="document_draft"&&first){first=false;throw new Error("lost ack");}return result;});render(<CanonicalResearchSpace/>);await openA();editQuestion("SENT V2");fireEvent.click(screen.getByRole("button",{name:"保存研究草稿"}));await screen.findByRole("alert");editQuestion("LATER V3");fireEvent.click(screen.getByRole("button",{name:"核对最新保存版本"}));await screen.findByText("发送时的研究版本已读回；随后编辑仍未保存。");expect(requests).toHaveLength(1);expect(docs.get("doc_a")!.version).toBe(2);expect(screen.getByLabelText("研究问题")).toHaveValue("LATER V3");await save();expect(requests[1].body.expected_version).toBe(2);
});
it("unified pinned reference callback receives source and immutable knowledge identities while preserving dirty research",async()=>{
 const r=(docs.get("doc_a")!.editor_json as J).attrs.archeaxis_research as ResearchValue;r.materials=[{id:"m",note:"原件",reference:{kind:"source",source_id:"source_actual",sha256:"b".repeat(64)}}];r.hypotheses=[{id:"h",text:"待验证",references:[{kind:"knowledge",knowledge_id:"knowledge_version_1"}]}];const open=vi.fn();render(<CanonicalResearchSpace onOpenReference={open}/>);await openA();editQuestion("未保存草稿");fireEvent.click(screen.getByRole("button",{name:"读取校验原件"}));fireEvent.click(screen.getByRole("button",{name:"打开不变知识版本"}));expect(open.mock.calls).toEqual([[{kind:"source",source_id:"source_actual",sha256:"b".repeat(64)}],[{kind:"knowledge",knowledge_id:"knowledge_version_1"}]]);expect(screen.getByLabelText("研究问题")).toHaveValue("未保存草稿");expect(requests).toHaveLength(0);
});

it("parallel local search cannot release document reference pending or add an earlier source selection",async()=>{
 let completeSearch!:(v:unknown)=>void,completeDocument!:(v:unknown)=>void;bridge.call.mockImplementation((op:string,p:J)=>op==="search"?new Promise(resolve=>{completeSearch=resolve;}):op==="document_get"&&p.document_id==="doc_b"?new Promise(resolve=>{completeDocument=resolve;}):original(op,p));render(<CanonicalResearchSpace/>);await openA();fireEvent.click(screen.getByRole("button",{name:"添加材料或待整理说明"}));const dialog=await screen.findByRole("dialog",{name:"选择研究引用"});await within(dialog).findByRole("option",{name:/真实来源/});fireEvent.change(within(dialog).getByLabelText("引用原件"),{target:{value:"source_actual"}});fireEvent.click(within(dialog).getByRole("button",{name:"检索本地知识"}));fireEvent.change(within(dialog).getByLabelText("引用文档"),{target:{value:"doc_b"}});await act(async()=>{completeSearch({items:[],transforms:[],count:0,transform_count:0});});expect(within(dialog).getByRole("button",{name:"添加所选引用"})).toBeDisabled();expect(within(dialog).queryByText(/将绑定 source_actual/)).not.toBeInTheDocument();await act(async()=>{completeDocument(dto("doc_b","B"));});await within(dialog).findByText(/将绑定 doc_b · 版本 1/);fireEvent.click(within(dialog).getByRole("button",{name:"添加所选引用"}));await save();expect(requests[0].body.editor_json.attrs.archeaxis_research.materials[0].reference).toEqual({kind:"document",document_id:"doc_b",version:1,block_id:null});
});
it("out of order historical reads keep the most recently requested version readonly",async()=>{
 docs.set("doc_a",dto("doc_a","A",2));const replies=new Map<number,(v:unknown)=>void>();bridge.call.mockImplementation((op:string,p:J)=>op==="document_version"?new Promise(resolve=>{replies.set(p.version,resolve);}):original(op,p));render(<CanonicalResearchSpace/>);fireEvent.click(await screen.findByRole("button",{name:"doc_a · 版本 2"}));await waitFor(()=>expect(screen.getByLabelText("研究问题")).toHaveValue("A"));fireEvent.click(screen.getByRole("button",{name:"读取研究历史"}));fireEvent.change(screen.getByLabelText("研究历史版本"),{target:{value:"2"}});fireEvent.click(screen.getByRole("button",{name:"读取研究历史"}));await act(async()=>{replies.get(2)!(dto("doc_a","历史二",2));});await screen.findByRole("heading",{name:"doc_a · 版本 2 · 只读"});await act(async()=>{replies.get(1)!(dto("doc_a","历史一",1));});expect(screen.getByRole("heading",{name:"doc_a · 版本 2 · 只读"})).toBeInTheDocument();expect(screen.queryByRole("heading",{name:"doc_a · 版本 1 · 只读"})).not.toBeInTheDocument();expect(screen.getByLabelText("研究问题")).toHaveValue("A");
});
it("history response arriving after a new edit never changes the draft into a readonly history mode",async()=>{
 let complete!:(v:unknown)=>void;bridge.call.mockImplementation((op:string,p:J)=>op==="document_version"?new Promise(resolve=>{complete=resolve;}):original(op,p));render(<CanonicalResearchSpace/>);await openA();fireEvent.click(screen.getByRole("button",{name:"读取研究历史"}));editQuestion("读取之后的新输入");await act(async()=>{complete(dto("doc_a","迟到历史",1));});expect(screen.queryByRole("complementary",{name:"只读文档"})).not.toBeInTheDocument();expect(screen.getByLabelText("研究问题")).toHaveValue("读取之后的新输入");expect(screen.getByRole("button",{name:"保存研究草稿"})).toBeEnabled();
});
it("late fallback original failures cannot overwrite a later reference picker state",async()=>{
 const r=(docs.get("doc_a")!.editor_json as J).attrs.archeaxis_research as ResearchValue;r.materials=[{id:"m",note:"原件",reference:{kind:"source",source_id:"source_actual",sha256:"b".repeat(64)}}];let rejectOriginal!:(v:unknown)=>void;bridge.call.mockImplementation((op:string,p:J)=>op==="source_original"?new Promise((_,reject)=>{rejectOriginal=reject;}):original(op,p));render(<CanonicalResearchSpace/>);await openA();fireEvent.click(screen.getByRole("button",{name:"读取校验原件"}));fireEvent.click(screen.getByRole("button",{name:"添加材料或待整理说明"}));await screen.findByRole("dialog",{name:"选择研究引用"});await act(async()=>{rejectOriginal(new Error("late original failure"));});expect(screen.queryByText("原件读取或SHA核对失败，未伪造内容。")).not.toBeInTheDocument();
});

it.each(["document_id","title","source_id"])("rejects wrong create ACK %s even when its v1 research envelope exactly matches the frozen request",async(field)=>{
 bridge.call.mockImplementation(async(op:string,p:J)=>{const result=await original(op,p);if(op!=="document_create")return result;return {...result as J,[field]:field==="document_id"?"wrong_identical_document":field==="title"?"wrong title":"source_actual"};});render(<CanonicalResearchSpace/>);editQuestion("必须绑定发送身份");fireEvent.click(screen.getByRole("button",{name:"保存研究草稿"}));await screen.findByRole("alert");expect(screen.getByRole("button",{name:"重试冻结研究保存"})).toBeInTheDocument();expect(screen.getByLabelText("研究问题")).toHaveValue("必须绑定发送身份");expect(requests).toHaveLength(1);expect(bridge.call.mock.calls.filter(c=>c[0]==="document_get")).toHaveLength(0);expect(screen.queryByText("研究草稿已保存并读回；未变为核验或采用状态。")).not.toBeInTheDocument();
});

it("an earlier object open cannot change the active research while current document save is awaiting ACK",async()=>{
 let completeOpen!:(v:unknown)=>void,completeSave!:(v:unknown)=>void;bridge.call.mockImplementation(async(op:string,p:J)=>{if(op==="document_get"&&p.document_id==="doc_b")return new Promise(resolve=>{completeOpen=resolve;});const result=await original(op,p);if(op==="document_draft")await new Promise(resolve=>{completeSave=resolve;});return result;});render(<CanonicalResearchSpace/>);await openA();fireEvent.click(screen.getByRole("button",{name:"doc_b · 版本 1"}));fireEvent.click(screen.getByRole("button",{name:"保存研究草稿"}));await waitFor(()=>expect(requests).toHaveLength(1));await act(async()=>{completeOpen(dto("doc_b","B"));});expect(screen.getByLabelText("研究问题")).toHaveValue("A");await act(async()=>{completeSave(null);});await screen.findByText("研究草稿已保存并读回；未变为核验或采用状态。");expect(screen.getByLabelText("研究问题")).toHaveValue("A");expect(docs.get("doc_a")!.version).toBe(2);
});
