import { webcrypto } from 'node:crypto';
import { beforeEach, expect, it, vi } from 'vitest';
import { act, fireEvent, render, screen, waitFor } from '@testing-library/react';
import { CanonicalRelationSpace } from '../spaces/CanonicalRelationSpace';
import { CollectionPanel } from '../components/CollectionPanel';
import { ApiError } from '../api/client';
const bridge=vi.hoisted(()=>({call:vi.fn()}));
vi.mock('../api/core',()=>({coreCommand:bridge.call}));
vi.mock('../design-system/AaosPrimitives',()=>({AaosDialog:({open,children}:any)=>open?<div role="dialog">{children}</div>:null}));
type J=Record<string,any>;
let docs:Map<string,J>, writes:J[];
const c=()=>({schema:'archeaxis.collection/v1',properties:[{property_id:'name',name:'原名',kind:'text'}],records:[],views:[{view_id:'table',name:'表格',kind:'table'}],source_payload:{opaque:{original:'keep'}}});
function d(id='a',version=1):J{return {document_id:id,version,title:id,source_id:null,source_revision:null,content_sha256:'a'.repeat(64),text_projection:'',blocks:[],editor_json:{type:'doc',attrs:{unknown:{keep:[1,2]},archeaxis_relations:{schema:'archeaxis.relations/v1',relations:[]},archeaxis_collection:c()},content:[{type:'future',attrs:{block_id:'stable'},unknown:'retain'}]}};}
const graph=(doc:J)=>({schema:'archeaxis.relation-projection/v1',snapshot_sha256:'b'.repeat(64),center:{document_id:doc.document_id,version:doc.version,content_sha256:doc.content_sha256},scope:'current_source_versions_to_pinned_center',nodes:[],edges:[],unsupported_sources:[],scan:{scanned:1,next_cursor:null,complete:true},derived_only:true});
beforeEach(()=>{vi.stubGlobal('crypto',webcrypto);docs=new Map([['a',d()],['b',d('b')]]);writes=[];bridge.call.mockReset();bridge.call.mockImplementation(async(op:string,p:J={})=>{
 if(op==='documents_list')return {documents:[...docs.values()],snapshot_count:docs.size,next_cursor:null};
 if(op==='document_get')return structuredClone(docs.get(p.document_id));
 if(op==='document_graph')return graph(d(p.document_id,p.version));
 if(op==='document_version')return d(p.document_id,p.version);
 if(op==='document_create'){writes.push(structuredClone(p));const bytes=await webcrypto.subtle.digest('SHA-256',new TextEncoder().encode(p.body.create_request_id));const id='doc_req_'+Array.from(new Uint8Array(bytes)).map(x=>x.toString(16).padStart(2,'0')).join('');let next=docs.get(id);if(!next){next={...d(id),title:p.body.title,editor_json:structuredClone(p.body.editor_json)};docs.set(id,next);}return structuredClone(next);}
 if(op==='document_draft'){writes.push(structuredClone(p));const old=docs.get(p.document_id)!;if(old.version!==p.body.expected_version)throw new ApiError(409,'conflict');if(p.body.editor_json.attrs.archeaxis_collection.views[0].filter?.property_id==='absent')throw new ApiError(400,'unknown property rejected without write');const next={...old,version:old.version+1,editor_json:structuredClone(p.body.editor_json)};docs.set(p.document_id,next);return structuredClone(next);}
 throw new Error(op);
});});
function Host(){return <CanonicalRelationSpace renderCollection={(document,envelope,change,pending,readOnly)=>{const attrs=envelope.attrs as J??{};return <CollectionPanel document={document} value={attrs.archeaxis_collection} onPendingEditChange={pending} readOnly={readOnly} onChange={value=>change({...envelope,attrs:{...attrs,archeaxis_collection:value}})}/>;}}/>;}
async function open(){fireEvent.click(await screen.findByRole('button',{name:'a · v1'}));await screen.findByText(/关系投影已读取/);}
const filter=(raw:string)=>{fireEvent.change(screen.getByLabelText('过滤 table'),{target:{value:raw}});fireEvent.click(screen.getByText('应用 过滤 table'));};
it('real Panel pending invalid JSON blocks save/switch/history and fires Shell dirty; cancel releases',async()=>{const event=vi.fn();window.addEventListener('archeaxis-draft-dirty',event);render(<Host/>);await open();filter('{invalid');expect(screen.getByLabelText('过滤 table')).toHaveValue('{invalid');expect(screen.getByRole('button',{name:'保存关系草稿'})).toBeDisabled();fireEvent.click(screen.getByRole('button',{name:'b · v1'}));fireEvent.click(screen.getByRole('button',{name:'读取历史关系（只读）'}));expect(bridge.call.mock.calls.filter(x=>x[0]==='document_version')).toHaveLength(0);expect(event.mock.calls.some(([e])=>e.detail===true)).toBe(true);expect(screen.getByLabelText('过滤 table')).toHaveValue('{invalid');fireEvent.click(screen.getByText('取消 过滤 table'));expect(event.mock.calls.at(-1)![0].detail).toBe(false);window.removeEventListener('archeaxis-draft-dirty',event);});
it('applied collection save ACK preserves foreign attrs/body and entire source payload',async()=>{render(<Host/>);await open();fireEvent.change(screen.getByLabelText('属性名称 name'),{target:{value:'已改'}});fireEvent.click(screen.getByRole('button',{name:'保存关系草稿'}));await screen.findByText('关系已保存并读回核对。');expect(writes[0].body.expected_version).toBe(1);expect(writes[0].body.editor_json.attrs.archeaxis_collection.properties[0].name).toBe('已改');expect(writes[0].body.editor_json.attrs.unknown).toEqual({keep:[1,2]});expect(writes[0].body.editor_json.content).toEqual(d().editor_json.content);expect(writes[0].body.editor_json.attrs.archeaxis_collection.source_payload).toEqual(c().source_payload);});
it('first-create lost ACK retries exact key/payload and preserves later collection edit',async()=>{let lost=true;const call=bridge.call.getMockImplementation()!;bridge.call.mockImplementation(async(op:string,p:J)=>{const result=await call(op,p);if(op==='document_create'&&lost){lost=false;throw new ApiError(502,'ack lost');}return result;});render(<Host/>);fireEvent.click(screen.getByText('添加集合定义'));fireEvent.click(screen.getByText('添加属性'));const field=screen.getByLabelText(/属性名称 property_/);fireEvent.change(field,{target:{value:'FIRST'}});fireEvent.click(screen.getByRole('button',{name:'保存关系草稿'}));await screen.findByRole('alert');fireEvent.change(field,{target:{value:'LATER'}});fireEvent.click(screen.getByRole('button',{name:'重试冻结保存'}));await screen.findByText('已保存发送时的版本；随后编辑仍是未保存草稿。');expect(writes).toHaveLength(2);expect(writes[0]).toEqual(writes[1]);expect(screen.getByLabelText(/属性名称 property_/)).toHaveValue('LATER');expect(screen.getByRole('button',{name:'保存关系草稿'})).toBeEnabled();});
it('late history response cannot hide newly pending actual Collection JSON',async()=>{let done!:(d:J)=>void;const call=bridge.call.getMockImplementation()!;bridge.call.mockImplementation((op:string,p:J)=>op==='document_version'?new Promise(r=>done=r):call(op,p));render(<Host/>);await open();fireEvent.click(screen.getByRole('button',{name:'读取历史关系（只读）'}));filter('{late');await act(async()=>done(d('a',1)));expect(screen.queryByText(/只读比较 v1/)).toBeNull();expect(screen.getByLabelText('过滤 table')).toHaveValue('{late');});
it('REGRESSION expected: known 400 rejection permits corrected definition on a new attempt',async()=>{render(<Host/>);await open();filter('{"op":"equal","property_id":"absent","value":null}');fireEvent.click(screen.getByRole('button',{name:'保存关系草稿'}));await screen.findByRole('alert');expect(docs.get('a')!.version).toBe(1);filter('null');fireEvent.click(screen.getByRole('button',{name:'保存关系草稿'}));await waitFor(()=>expect(writes).toHaveLength(2));expect(writes[1].body.editor_json.attrs.archeaxis_collection.views[0].filter).toBeNull();expect(docs.get('a')!.version).toBe(2);});
it('REGRESSION expected: reconcile respects pending raw barrier like history does',async()=>{render(<Host/>);await open();filter('{pending');const calls=bridge.call.mock.calls.filter(x=>x[0]==='document_get').length;docs.set('a',d('a',2));fireEvent.click(screen.getByRole('button',{name:'核对最新版本（保留草稿）'}));await act(async()=>{});expect(bridge.call.mock.calls.filter(x=>x[0]==='document_get')).toHaveLength(calls);expect(screen.queryByText(/最新版本不同，仅只读比较/)).toBeNull();expect(screen.getByLabelText('过滤 table')).toHaveValue('{pending');});

it('readback 400 after acknowledged write keeps the exact frozen attempt',async()=>{let written=false;const call=bridge.call.getMockImplementation()!;bridge.call.mockImplementation(async(op:string,p:J)=>{if(op==='document_get'&&written)throw new ApiError(400,'readback rejected');const result=await call(op,p);if(op==='document_draft')written=true;return result;});render(<Host/>);await open();fireEvent.change(screen.getByLabelText('属性名称 name'),{target:{value:'first'}});fireEvent.click(screen.getByRole('button',{name:'保存关系草稿'}));await screen.findByRole('alert');expect(docs.get('a')!.version).toBe(2);expect(screen.getByRole('button',{name:'重试冻结保存'})).toBeEnabled();fireEvent.change(screen.getByLabelText('属性名称 name'),{target:{value:'later'}});fireEvent.click(screen.getByRole('button',{name:'重试冻结保存'}));await waitFor(()=>expect(writes).toHaveLength(2));expect(writes[0]).toEqual(writes[1]);expect(screen.getByLabelText('属性名称 name')).toHaveValue('later');});
it('late reconcile response does not hide new pending actual Collection JSON',async()=>{let done!:(d:J)=>void;const call=bridge.call.getMockImplementation()!;let hold=false;bridge.call.mockImplementation((op:string,p:J)=>op==='document_get'&&hold?new Promise(r=>done=r):call(op,p));render(<Host/>);await open();hold=true;fireEvent.click(screen.getByRole('button',{name:'核对最新版本（保留草稿）'}));filter('{late reconcile');await act(async()=>done(d('a',2)));expect(screen.queryByText(/最新版本不同，仅只读比较/)).toBeNull();expect(screen.getByLabelText('过滤 table')).toHaveValue('{late reconcile');});
