import { describe, expect, it, vi } from "vitest";
import { freezeFolderAttempt, folderCancelAck, folderExecutionAck, folderJobStatus, freshAttemptEligible, pollFolderAttempt } from "../presentation/folderIngestExecution";
import type { BoundedJobCommand } from "../components/BoundedJobPanel";
function receipt(state="failed") { return { job_id:"job1",input_ref:"source1",state,attempt:1,request_id:"request1",error:null,attempts:[{attempt:1,request_id:"request1",state,budget:{deadline_ms:90000,split:false,words:false},continuation:{new_attempt_eligible_state:true}}] }; }
const attempt={job_id:"job1",request_id:"request1",body:{deadline_ms:90000,split:false,words:false}};
describe("batch-specific bounded execution identity",()=>{
  it("freezes separate fresh request IDs and the visible finite budget",()=>{const a=freezeFolderAttempt("job1"),b=freezeFolderAttempt("job1");expect(a.request_id).not.toBe(b.request_id);expect(a.body).toEqual({deadline_ms:90000,split:false,words:false});expect(Object.isFrozen(a)).toBe(true);expect(Object.isFrozen(a.body)).toBe(true);});
  it("strict ACK rejects wrong job/request, missing replay evidence and unknown states",()=>{expect(folderExecutionAck({job_id:"job1",request_id:"request1",state:"running",replayed:false},attempt)).toBe("running");for(const change of [{job_id:"other"},{request_id:"other"},{replayed:undefined},{state:"magic_done"}])expect(()=>folderExecutionAck({job_id:"job1",request_id:"request1",state:"running",replayed:false,...change},attempt)).toThrow();});
  it("202 cancellation is only an identity-checked acknowledgement",()=>{expect(()=>folderCancelAck({job_id:"job1",request_id:"request1",cancel_requested:true},attempt)).not.toThrow();for(const change of [{job_id:"other"},{request_id:"other"},{cancel_requested:"true"},{state:"magic_done"}])expect(()=>folderCancelAck({job_id:"job1",request_id:"request1",cancel_requested:true,...change},attempt)).toThrow();});
  it("status requires source, current attempt identity and unchanged frozen budget",()=>{expect(folderJobStatus(receipt(),"job1","source1",attempt).state).toBe("failed");for(const change of [{input_ref:"other"},{job_id:"other"},{request_id:"other"},{attempt:null},{attempt:0},{state:"unknown"},{error:5}])expect(()=>folderJobStatus({...receipt(),...change},"job1","source1",attempt)).toThrow();const wrong=receipt();wrong.attempts[0].budget.deadline_ms=1;expect(()=>folderJobStatus(wrong,"job1","source1",attempt)).toThrow("预算");});
  it("a fresh attempt is a current Core condition and never means checkpoint resume or rejected retry",()=>{expect(freshAttemptEligible(receipt())).toBe(true);expect(freshAttemptEligible(receipt("cancelled"))).toBe(true);expect(freshAttemptEligible(receipt("rejected"))).toBe(false);const wrong=receipt();wrong.attempts[0].continuation.new_attempt_eligible_state=false;expect(freshAttemptEligible(wrong)).toBe(false);const absent={...receipt(),attempts:[]};expect(freshAttemptEligible(absent)).toBe(false);});
  it("refuses a terminal frozen request without unique current attempt and budget evidence",()=>{
    const valid=receipt("succeeded");
    for(const attempts of [undefined,[],[valid.attempts[0],valid.attempts[0]]]){
      expect(()=>folderJobStatus({...valid,attempts},"job1","source1",attempt)).toThrow();
    }
    expect(()=>folderJobStatus({...valid,attempts:[{...valid.attempts[0],budget:undefined}]},"job1","source1",attempt)).toThrow();
    expect(folderJobStatus(valid,"job1","source1",attempt).state).toBe("succeeded");
  });
  it("polling only reads and preserves running before an actual terminal; exit cannot publish late data",async()=>{const command=vi.fn<BoundedJobCommand>().mockResolvedValueOnce(receipt("running")).mockResolvedValueOnce(receipt("cancelled"));const reads:string[]=[];await expect(pollFolderAttempt(command,attempt,"source1",()=>true,value=>reads.push(value.state),async()=>{},1)).resolves.toMatchObject({state:"cancelled"});expect(reads).toEqual(["running","cancelled"]);expect(command.mock.calls.every(([op])=>op==="job_execution_status")).toBe(true);let current=true;const late=vi.fn<BoundedJobCommand>().mockImplementation(async()=>{current=false;return receipt("succeeded");});const publish=vi.fn();await expect(pollFolderAttempt(late,attempt,"source1",()=>current,publish,async()=>{},1)).rejects.toThrow("页面已退出");expect(publish).not.toHaveBeenCalled();});
});
