import { beforeEach,afterEach,it,expect,vi } from "vitest";
import { createHash,webcrypto } from "node:crypto";
import { fireEvent,render,screen,waitFor } from "@testing-library/react";
import { MachineAnswerPanel } from "../components/MachineAnswerPanel";
import { ApiError } from "../api/client";
import type { AssetPacketRequest } from "../api/generated/ai-asset-contract";
type J=Record<string,any>;
const bridge=vi.hoisted(()=>({call:vi.fn()}));vi.mock("../api/core",()=>({coreCommand:bridge.call}));
const knowledge={document_id:"knowledge_grant",version:1,content_sha256:"a".repeat(64),purpose:"真实知识用途"};
const asset:AssetPacketRequest={request_id:"selection_only",asset:{document_id:"asset",version:2,content_sha256:"b".repeat(64)},grant:{document_id:"asset_grant",version:3,content_sha256:"c".repeat(64)},purpose:"固定资产用途",consumer:"local-machine",operation:"answer"};
const metadata=(b:J,operation="answer")=>({schema:"archeaxis.machine-asset-context/v1",asset:b.asset_context_grant.asset,grant:b.asset_context_grant.grant,consumer:"local-machine",operation,packet_sha256:"d".repeat(64),member_snapshots:[],tool_execution:"NOT_EXECUTED",private_session_access:false});
function answer(b:J){return {schema:"archeaxis.machine-answer/v1",answer_id:"answer_req_"+createHash("sha256").update(b.client_request_id).digest("hex"),client_request_id:b.client_request_id,knowledge_id:b.knowledge_id,question:b.question,answer:{answer:"SIMULATED回答",model:"fixture"},authority:"candidate",request:{schema:"archeaxis.machine-answer-request/v1",knowledge_id:b.knowledge_id,question:b.question,max_tokens:b.max_tokens,timeout_s:b.timeout_s,context_grant:b.context_grant,context_sha256:"e".repeat(64),knowledge_context_sha256:"f".repeat(64),asset_context_grant:structuredClone(b.asset_context_grant),asset_client_request_id:b.client_request_id,asset_context:metadata(b)}};}
const task=(v:J)=>({task_id:v.answer_id,conditions:JSON.stringify(v),scope:"runtime.answer",knowledge_version:v.knowledge_id+"@v1",model_version:v.answer.model,outcome:"unmeasured"});
beforeEach(()=>{vi.stubGlobal("crypto",webcrypto);bridge.call.mockReset();});afterEach(()=>vi.unstubAllGlobals());
it("knowledge grant remains mandatory and selection does not infer",()=>{render(<MachineAnswerPanel knowledgeId="k" scoped assetScoped assetContextGrant={asset}/>);fireEvent.change(screen.getByLabelText("实际问题"),{target:{value:"问题"}});expect(screen.getByRole("button",{name:"执行本地机器回答"})).toBeDisabled();expect(bridge.call).not.toHaveBeenCalled();});
it("UNKNOWN freezes full asset request while later selection/question changes cannot mutate retry",async()=>{let saved:J|null=null;const requests:J[]=[];bridge.call.mockImplementation(async(op,p)=>{if(op==="machine_answer"){requests.push(structuredClone(p.body));saved=answer(p.body);if(requests.length===1)throw new ApiError(502,"lost ack");return saved;}if(op==="machine_task_get")return task(saved!);throw new Error(op);});const view=render(<MachineAnswerPanel knowledgeId="k" scoped contextGrant={knowledge} assetScoped assetContextGrant={asset}/>);fireEvent.change(screen.getByLabelText("实际问题"),{target:{value:"原问题"}});fireEvent.click(screen.getByRole("button",{name:"执行本地机器回答"}));await screen.findByText(/状态 UNKNOWN。请读取历史核对/);view.rerender(<MachineAnswerPanel knowledgeId="k" scoped contextGrant={knowledge} assetScoped assetContextGrant={{...asset,purpose:"后来用途"}}/>);fireEvent.change(screen.getByLabelText("实际问题"),{target:{value:"后来草稿"}});fireEvent.click(screen.getByRole("button",{name:"重试同一回答请求"}));await screen.findByLabelText("真实机器回答");expect(requests[1]).toEqual(requests[0]);expect(requests[0].asset_context_grant.request_id).not.toBe("selection_only");expect(requests[0].asset_context_grant.purpose).toBe("固定资产用途");expect(screen.getByLabelText("实际问题")).toHaveValue("后来草稿");});
it("every new explicit answer gets fresh asset request ID rather than reusing selection",async()=>{let saved:J|null=null;const requests:J[]=[];bridge.call.mockImplementation(async(op,p)=>{if(op==="machine_answer"){requests.push(structuredClone(p.body));return saved=answer(p.body);}if(op==="machine_task_get")return task(saved!);throw new Error(op);});render(<MachineAnswerPanel knowledgeId="k" scoped contextGrant={knowledge} assetScoped assetContextGrant={asset}/>);fireEvent.change(screen.getByLabelText("实际问题"),{target:{value:"问题一"}});fireEvent.click(screen.getByRole("button",{name:"执行本地机器回答"}));await screen.findByLabelText("真实机器回答");fireEvent.change(screen.getByLabelText("实际问题"),{target:{value:"问题二"}});fireEvent.click(screen.getByRole("button",{name:"执行本地机器回答"}));await waitFor(()=>expect(requests).toHaveLength(2));await screen.findByLabelText("真实机器回答");expect(requests[0].asset_context_grant.request_id).not.toBe(requests[1].asset_context_grant.request_id);expect(requests[1].asset_context_grant.asset).toEqual(asset.asset);});
it.each(["grant","operation","private_session_access"])("wrong asset receipt %s cannot publish a model answer",async field=>{bridge.call.mockImplementation(async(op,p)=>{if(op!=="machine_answer")throw new Error("must not trust");const v=answer(p.body);if(field==="grant")v.request.asset_context.grant={...asset.grant,version:99};else (v.request.asset_context as J)[field]=field==="operation"?"retest":true;return v;});render(<MachineAnswerPanel knowledgeId="k" scoped contextGrant={knowledge} assetScoped assetContextGrant={asset}/>);fireEvent.change(screen.getByLabelText("实际问题"),{target:{value:"问题"}});fireEvent.click(screen.getByRole("button",{name:"执行本地机器回答"}));await screen.findByText(/状态 UNKNOWN。请读取历史核对/);expect(screen.queryByLabelText("真实机器回答")).not.toBeInTheDocument();expect(bridge.call).toHaveBeenCalledTimes(1);});
it("withdrawn selection pauses new execution but leaves history controls intact",()=>{const view=render(<MachineAnswerPanel knowledgeId="k" scoped contextGrant={knowledge} assetScoped assetContextGrant={asset}/>);fireEvent.change(screen.getByLabelText("实际问题"),{target:{value:"草稿"}});view.rerender(<MachineAnswerPanel knowledgeId="k" scoped contextGrant={knowledge} assetScoped/>);expect(screen.getByRole("button",{name:"执行本地机器回答"})).toBeDisabled();expect(screen.getByRole("button",{name:"读取机器学习历史"})).toBeEnabled();expect(screen.getByLabelText("实际问题")).toHaveValue("草稿");expect(bridge.call).not.toHaveBeenCalled();});
it.each(["purpose","request_id","asset_client_request_id"])("same pins with wrong raw asset %s cannot acknowledge the frozen answer",async field=>{
 bridge.call.mockImplementation(async(op,p)=>{if(op!=="machine_answer")throw new Error("must not accept");const v=answer(p.body);if(field==="asset_client_request_id")v.request.asset_client_request_id="other_machine";else (v.request.asset_context_grant as J)[field]="changed";return v;});
 render(<MachineAnswerPanel knowledgeId="k" scoped contextGrant={knowledge} assetContextGrant={asset}/>);fireEvent.change(screen.getByLabelText("实际问题"),{target:{value:"问题"}});fireEvent.click(screen.getByRole("button",{name:"执行本地机器回答"}));await screen.findByText(/状态 UNKNOWN。请读取历史核对/);expect(screen.queryByLabelText("真实机器回答")).not.toBeInTheDocument();expect(screen.getByRole("button",{name:"重试同一回答请求"})).toBeEnabled();
});
it.each(["purpose","request_id","asset_client_request_id"])("UNKNOWN history with changed %s leaves the original request frozen",async field=>{
 let original:J|null=null;const requests:J[]=[];let row:J;
 bridge.call.mockImplementation(async(op,p)=>{if(op==="machine_answer"){requests.push(structuredClone(p.body));original=answer(p.body);if(requests.length===1)throw new ApiError(502,"lost ack");return original;}if(op==="machine_tasks_list"){const changed=structuredClone(original!);if(field==="asset_client_request_id")changed.request.asset_client_request_id="other_machine";else changed.request.asset_context_grant[field]="changed";row=task(changed);return {items:[row],next_cursor:null};}if(op==="machine_task_get")return requests.length===1?row:task(original!);throw new Error(op);});
 render(<MachineAnswerPanel knowledgeId="k" scoped contextGrant={knowledge} assetContextGrant={asset}/>);fireEvent.change(screen.getByLabelText("实际问题"),{target:{value:"问题"}});fireEvent.click(screen.getByRole("button",{name:"执行本地机器回答"}));await screen.findByText(/状态 UNKNOWN。请读取历史核对/);fireEvent.click(screen.getByRole("button",{name:"读取机器学习历史"}));fireEvent.click(await screen.findByRole("button",{name:/读取此任务旅程 answer_req_/}));await screen.findByText(/历史身份或读回未确认/);expect(screen.queryByLabelText("真实机器回答")).not.toBeInTheDocument();fireEvent.click(screen.getByRole("button",{name:"重试同一回答请求"}));await screen.findByLabelText("真实机器回答");expect(requests[1]).toEqual(requests[0]);
});
it("frozen request retains strict acknowledgement checks when current asset props disappear",async()=>{
 let calls=0;bridge.call.mockImplementation(async(op,p)=>{if(op!=="machine_answer")throw new Error("must not accept");if(++calls===1)throw new ApiError(502,"lost ack");const v=answer(p.body);v.request.timeout_s=999;return v;});
 const view=render(<MachineAnswerPanel knowledgeId="k" contextGrant={knowledge} assetContextGrant={asset}/>);fireEvent.change(screen.getByLabelText("实际问题"),{target:{value:"问题"}});fireEvent.click(screen.getByRole("button",{name:"执行本地机器回答"}));await screen.findByText(/状态 UNKNOWN。请读取历史核对/);view.rerender(<MachineAnswerPanel knowledgeId="k"/>);fireEvent.click(screen.getByRole("button",{name:"重试同一回答请求"}));await waitFor(()=>expect(calls).toBe(2));await waitFor(()=>expect(screen.getByRole("button",{name:"重试同一回答请求"})).toBeEnabled());expect(screen.queryByLabelText("真实机器回答")).not.toBeInTheDocument();
});
it("executed asset answer withheld is never automatically retried",async()=>{bridge.call.mockRejectedValue(new ApiError(403,"WITHHELD","unavailable",{execution_state:"EXECUTED_BUT_WITHHELD",answer_published:false,audit_status:"RECORDED",audit_task_id:"withheld_"+"a".repeat(64)}));render(<MachineAnswerPanel knowledgeId="k" scoped contextGrant={knowledge} assetScoped assetContextGrant={asset}/>);fireEvent.change(screen.getByLabelText("实际问题"),{target:{value:"原问题"}});fireEvent.click(screen.getByRole("button",{name:"执行本地机器回答"}));await screen.findByRole("button",{name:"结束已执行但未发布的请求，保留草稿"});expect(screen.getByRole("button",{name:"执行本地机器回答"})).toBeDisabled();expect(screen.queryByRole("button",{name:"重试同一回答请求"})).not.toBeInTheDocument();expect(bridge.call).toHaveBeenCalledTimes(1);});
it("source asset answer requires independent retest asset and validates frozen execution budget",async()=>{
 const original={schema:"archeaxis.machine-answer/v1",answer_id:"old",knowledge_id:"k",question:"原问题",answer:{answer:"原回答",model:"fixture"},authority:"candidate",request:{asset_context:metadata({asset_context_grant:asset})}};
 const correction={answer_id:"old",failed_task_id:"evaluation_old",correction_candidate_id:"corrected",corrects_knowledge_id:"k",question:"原问题",machine_answer:"原回答",corrected_answer:"更正内容",error_note:"依据",reviewer:"本人"};
 const evaluation={...original,correction},failed={...task(evaluation),task_id:"evaluation_old",scope:"runtime.evaluation.failed",outcome:"failed"};let result:J|null=null;const requests:J[]=[];
 bridge.call.mockImplementation(async(op,p)=>{if(op==="machine_tasks_list")return {items:[failed],next_cursor:null};if(op==="knowledge_get")return {knowledge_id:"corrected",body:"更正内容",version:"v2",status:"accepted"};if(op==="machine_task_get")return p.task_id==="old"?task(original):p.task_id==="evaluation_old"?failed:{...task(result!),scope:"runtime.retest",retest_of:result!.retest_of};if(op==="machine_retest"){const b=p.body;requests.push(structuredClone(b));const raw={retest_of:b.retest_of,knowledge_id:b.knowledge_id,question:b.question,max_tokens:b.max_tokens,context_grant:b.context_grant,asset_context_grant:b.asset_context_grant};result={schema:"archeaxis.machine-retest/v1",answer_id:"retest",retest_task_id:"retest",retest_of:b.retest_of,knowledge_id:b.knowledge_id,question:b.question,answer:{answer:"SIMULATED复测",model:"fixture"},authority:"candidate",request:raw,execution_request:{schema:"archeaxis.machine-retest-execution/v1",request:raw,timeout_s:requests.length===1?121:120,context_sha256:"e".repeat(64),knowledge_context_sha256:"f".repeat(64),asset_context:metadata(b,"retest")}};return result;}throw new Error(op);});
 const view=render(<MachineAnswerPanel knowledgeId="k" scoped contextGrant={knowledge} retestContextGrant={knowledge}/>);fireEvent.click(screen.getByRole("button",{name:"读取机器学习历史"}));fireEvent.click(await screen.findByRole("button",{name:"读取此任务旅程 evaluation_old"}));await screen.findByLabelText("真实机器回答");expect(screen.getByRole("button",{name:"以已接受纠正知识运行独立复测"})).toBeDisabled();
 view.rerender(<MachineAnswerPanel knowledgeId="k" scoped contextGrant={knowledge} retestContextGrant={knowledge} retestAssetScoped retestAssetContextGrant={{...asset,operation:"retest"}}/>);fireEvent.click(screen.getByRole("button",{name:"以已接受纠正知识运行独立复测"}));await screen.findByText(/复测未完成或持久化读回未确认/);expect(screen.queryByLabelText("独立复测机器回答")).not.toBeInTheDocument();view.rerender(<MachineAnswerPanel knowledgeId="k" scoped contextGrant={knowledge} retestContextGrant={knowledge} retestAssetScoped retestAssetContextGrant={{...asset,operation:"retest",purpose:"变更用途"}}/>);fireEvent.click(screen.getByRole("button",{name:"重试同一冻结复测请求"}));await screen.findByLabelText("独立复测机器回答");expect(requests[0]).toEqual(requests[1]);expect(requests[0].asset_context_grant.operation).toBe("retest");expect(requests[0].asset_context_grant.request_id).not.toBe("selection_only");
});
