import { beforeEach,it,expect,vi } from "vitest";
import { render,screen,fireEvent,waitFor } from "@testing-library/react";
import { ObjectReferencePicker } from "../components/ObjectReferencePicker";
const bridge=vi.hoisted(()=>({call:vi.fn()}));vi.mock("../api/core",()=>({coreCommand:bridge.call}));
const doc={document_id:"document_real",version:4,content_sha256:"a".repeat(64),title:"真实文档",source_id:null,source_revision:null,editor_json:{type:"doc",content:[]},text_projection:"块原文",blocks:[{block_id:"block_real",type:"paragraph",path:[0],text_projection:"块原文",node:{type:"paragraph",text:"块原文"}}]};
beforeEach(()=>{bridge.call.mockReset();bridge.call.mockImplementation(async(op:string)=>{if(op==="documents_list")return {documents:[{document_id:doc.document_id,title:doc.title,version:3,source_id:null,source_revision:null,content_sha256:"b".repeat(64)}],next_cursor:null,snapshot_count:1};if(op==="document_get")return doc;throw new Error("unexpected "+op);});});
it("pins actual document get version and block rather than stale list version",async()=>{const pick=vi.fn();render(<ObjectReferencePicker onPick={pick}/>);fireEvent.click(screen.getByRole("button",{name:"读取文档对象"}));await screen.findByRole("option",{name:"真实文档 · 列表 v3"});fireEvent.change(screen.getByLabelText("选择文档"),{target:{value:"document_real"}});await screen.findByLabelText("固定引用块");fireEvent.change(screen.getByLabelText("固定引用块"),{target:{value:"block_real"}});fireEvent.click(screen.getByRole("button",{name:"加入此固定引用"}));expect(pick).toHaveBeenCalledWith({kind:"document",document_id:"document_real",version:4,block_id:"block_real"});});
it("late read cannot become selectable after picker disabled or session change",async()=>{let resolve!:(v:unknown)=>void;bridge.call.mockImplementation((op:string)=>op==="document_get"?new Promise(r=>resolve=r):Promise.resolve({documents:[doc],next_cursor:null,snapshot_count:1}));const pick=vi.fn(),view=render(<ObjectReferencePicker onPick={pick}/>);fireEvent.click(screen.getByRole("button",{name:"读取文档对象"}));await screen.findByRole("option",{name:"真实文档 · 列表 v4"});fireEvent.change(screen.getByLabelText("选择文档"),{target:{value:"document_real"}});view.rerender(<ObjectReferencePicker onPick={pick} disabled/>);resolve(doc);await waitFor(()=>expect(screen.queryByRole("button",{name:"加入此固定引用"})).not.toBeInTheDocument());expect(pick).not.toHaveBeenCalled();});
it("read errors remain explicit with no synthetic object",async()=>{bridge.call.mockRejectedValue(new Error("Core offline"));render(<ObjectReferencePicker onPick={vi.fn()}/>);fireEvent.click(screen.getByRole("button",{name:"读取文档对象"}));await screen.findByRole("alert");expect(screen.queryByRole("button",{name:"加入此固定引用"})).not.toBeInTheDocument();});
