"""The external-resource index must stay in step with the declaration, and must resolve here.

Two failure modes this guards, both of which actually happened in this repository:

* a declaration that points somewhere the resolver cannot find, so an installed engine is reported
  missing (the worker resolver deliberately refuses to guess on PATH, so the declaration is the only
  route);
* a model that real runs depend on but that no declaration names at all, leaving it discoverable
  only through an environment variable.

The index is generated by `scripts/environment/build_external_resources_index.py`. When the external
root is not present in the environment the resolution half is skipped with an explicit reason, so a
missing root can never read as a clean result.
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[2]
MANIFEST = ROOT / "config" / "environment" / "capability-requirements.yaml"
INDEX = ROOT / "config" / "environment" / "external-resources-index.json"
BUILDER = ROOT / "scripts" / "environment" / "build_external_resources_index.py"
ROOT_ENV = ("ARCHEAXIS_EXTERNAL_ROOT", "OS_EXTERNAL_CONFIG")


def declared_entries() -> list[dict]:
    import yaml

    document = yaml.safe_load(MANIFEST.read_text(encoding="utf-8")) or {}
    found = []
    for category, group in (document.get("capabilities") or {}).items():
        for entry in group or []:
            if isinstance(entry, dict):
                found.append({**entry, "category": category})
    return found


def test_index_covers_exactly_the_declared_entries():
    index = json.loads(INDEX.read_text(encoding="utf-8"))
    assert index["schema"] == "archeaxis/external-resources-index/v1"
    indexed = {(row["category"], row["name"]) for row in index["entries"]}
    expected = {(entry["category"], entry["name"]) for entry in declared_entries()}
    assert indexed == expected, f"index and manifest disagree: {indexed ^ expected}"


def test_every_declared_external_path_is_recorded():
    index = json.loads(INDEX.read_text(encoding="utf-8"))
    declared = {
        (entry["category"], entry["name"]): [p for p in (entry.get("external_paths") or []) if isinstance(p, str)]
        for entry in declared_entries()
    }
    for row in index["entries"]:
        recorded = [item["declared"] for item in row["external_paths"]]
        assert recorded == declared[(row["category"], row["name"])]


@pytest.mark.skipif(
    not any(os.environ.get(name, "").strip() for name in ROOT_ENV),
    reason="no external root in the environment; resolution is skipped rather than assumed clean",
)
def test_declared_paths_resolve_on_this_host():
    # Rebuild with the environment this test was given, stated rather than inherited implicitly,
    # so the assertion is about the current manifest and a known external root.
    environment = {**os.environ}
    subprocess.run([sys.executable, "-B", str(BUILDER)], check=True, capture_output=True,
                   cwd=ROOT, env=environment)
    index = json.loads(INDEX.read_text(encoding="utf-8"))
    assert index["root_present"], "the declared external root is not a directory"
    missing = [
        f"{row['name']}: {item['declared']}"
        for row in index["entries"]
        for item in row["external_paths"]
        if not item["exists"]
    ]
    assert missing == []


def test_the_index_and_the_runtime_resolver_agree_about_every_declared_path() -> None:
    """The artefact that says a resource is findable must agree with the code that finds it.

    This is the failure that actually happened: the index resolved the `../Model library/...` form
    itself and recorded `exists: true` for the ASR weights, while the runtime resolver rejects `..`
    and raised `ToolNotFound` for the same name. A verification artefact that certifies a path no
    runtime can reach is worse than no artefact, because it hides the failure it exists to catch.
    """
    import importlib.util

    root_value = ""
    for name in ROOT_ENV:
        root_value = os.environ.get(name, "").strip()
        if root_value:
            break
    if not root_value:
        pytest.skip("no external root in this environment; resolution cannot be compared")

    index = json.loads(INDEX.read_text(encoding="utf-8"))
    assert index["external_root"], index
    spec = importlib.util.spec_from_file_location(
        "cross_reader_tool_paths", ROOT / "services" / "python-workers" / "tool_paths.py")
    assert spec and spec.loader
    resolver = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(resolver)

    compared = 0
    for entry in index["entries"]:
        for resolution in entry["external_paths"]:
            compared += 1
            try:
                found = resolver.tool_path(entry["name"])
            except Exception as error:  # the resolver's own named failure
                assert not resolution["exists"], (
                    f"the index claims {entry['name']} exists at {resolution['resolved']} "
                    f"but the runtime resolver cannot reach it: {error}")
                continue
            assert resolution["exists"], (
                f"the runtime resolver found {entry['name']} at {found} "
                f"but the index recorded exists=false")
    assert compared, "no declared external path was compared, which would make this test vacuous"


def test_a_traversing_declaration_is_refused_by_both_readers(monkeypatch, tmp_path) -> None:
    """`..` stays refused in `external_paths` by both readers; a shared resource is named instead.

    Allowing the traversal would have made the index agree with reality at the cost of the
    boundary, so the fix had to reach the sibling by declaring it. This falsifies both readers:
    each must refuse a traversal even when the target really exists.
    """
    import importlib.util

    root = tmp_path / "OS External Configuration"
    (root / "inside").mkdir(parents=True)
    outside = tmp_path / "Model library" / "weights"
    outside.mkdir(parents=True)
    monkeypatch.setenv("ARCHEAXIS_EXTERNAL_ROOT", str(root))

    spec = importlib.util.spec_from_file_location(
        "boundary_tool_paths", ROOT / "services" / "python-workers" / "tool_paths.py")
    assert spec and spec.loader
    resolver = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(resolver)

    # The runtime resolver: a traversal reaches nothing, a declared sibling root reaches it.
    traversing = {"capabilities": {"models": [
        {"name": "probe", "external_paths": ["../Model library/weights"]}]}}
    manifest = tmp_path / "traversing.yaml"
    manifest.write_text(json.dumps(traversing), encoding="utf-8")
    assert resolver._candidates("probe", manifest) == []

    declared = {"capabilities": {"models": [
        {"name": "probe", "sibling_root": "model-library",
         "external_paths": ["weights"]}]}, "sibling_roots": {"model-library": "../Model library"}}
    manifest.write_text(json.dumps(declared), encoding="utf-8")
    assert resolver._candidates("probe", manifest) == [outside]

    # The index builder's own resolver: same refusal, same reason.
    spec = importlib.util.spec_from_file_location(
        "boundary_index_builder", BUILDER)
    assert spec and spec.loader
    builder = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(builder)
    assert builder.resolve("../Model library/weights", root) == ("", False)
    assert builder.resolve("inside", root)[1] is True

    # And the manifest this repository actually ships carries no traversal at all.
    paths = [p for entry in declared_entries() for p in (entry.get("external_paths") or [])
             if isinstance(p, str)]
    assert paths, "no declared external path to check"
    assert not [p for p in paths if ".." in Path(p).parts], (
        "a declared external path traverses; use sibling_root instead")


def test_the_index_is_written_with_lf_on_every_host(tmp_path, monkeypatch) -> None:
    """A tracked generated file must not change line endings depending on who regenerated it.

    This host's own test rebuilds the index in place, so platform newlines left the tree modified
    after an otherwise clean run - and a dirty tree makes a development receipt unattributable to
    the change it claims to record.
    """
    import importlib.util

    spec = importlib.util.spec_from_file_location("newline_index_builder", BUILDER)
    assert spec and spec.loader
    builder = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(builder)
    target = tmp_path / "external-resources-index.json"
    monkeypatch.setattr(builder, "INDEX", target)
    assert builder.main() == 0
    written = target.read_bytes()
    assert b"\r" not in written, "the builder wrote platform newlines into a tracked artefact"
    assert json.loads(written.decode("utf-8"))["schema"] == "archeaxis/external-resources-index/v1"
    assert b"\r" not in INDEX.read_bytes(), "the committed index is not the LF form the builder writes"
