"""The external-resource index must stay in step with the declaration, and must resolve here.

Two failure modes this guards, both of which actually happened in this repository:

* a declaration that points somewhere the resolver cannot find, so an installed engine is reported
  missing (the worker resolver deliberately refuses to guess on PATH, so the declaration is the only
  route);
* a model that real runs depend on but that no declaration names at all, leaving it discoverable
  only through an environment variable.

The index is generated by `scripts/environment/build_external_resources_index.py`. When the external
root is not present in the environment the resolution half is skipped with an explicit reason, so a
missing root can never read as a clean result.
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[2]
MANIFEST = ROOT / "config" / "environment" / "capability-requirements.yaml"
INDEX = ROOT / "config" / "environment" / "external-resources-index.json"
BUILDER = ROOT / "scripts" / "environment" / "build_external_resources_index.py"
ROOT_ENV = ("ARCHEAXIS_EXTERNAL_ROOT", "OS_EXTERNAL_CONFIG")


def declared_entries() -> list[dict]:
    import yaml

    document = yaml.safe_load(MANIFEST.read_text(encoding="utf-8")) or {}
    found = []
    for category, group in (document.get("capabilities") or {}).items():
        for entry in group or []:
            if isinstance(entry, dict):
                found.append({**entry, "category": category})
    return found


def test_index_covers_exactly_the_declared_entries():
    index = json.loads(INDEX.read_text(encoding="utf-8"))
    assert index["schema"] == "archeaxis/external-resources-index/v1"
    indexed = {(row["category"], row["name"]) for row in index["entries"]}
    expected = {(entry["category"], entry["name"]) for entry in declared_entries()}
    assert indexed == expected, f"index and manifest disagree: {indexed ^ expected}"


def test_every_declared_external_path_is_recorded():
    index = json.loads(INDEX.read_text(encoding="utf-8"))
    declared = {
        (entry["category"], entry["name"]): [p for p in (entry.get("external_paths") or []) if isinstance(p, str)]
        for entry in declared_entries()
    }
    for row in index["entries"]:
        recorded = [item["declared"] for item in row["external_paths"]]
        assert recorded == declared[(row["category"], row["name"])]


@pytest.mark.skipif(
    not any(os.environ.get(name, "").strip() for name in ROOT_ENV),
    reason="no external root in the environment; resolution is skipped rather than assumed clean",
)
def test_declared_paths_resolve_on_this_host():
    environment = {**os.environ}
    # Rebuild so the assertion is about the current manifest, not a stale artifact.
    subprocess.run([sys.executable, "-B", str(BUILDER)], check=True, capture_output=True, cwd=ROOT)
    index = json.loads(INDEX.read_text(encoding="utf-8"))
    assert index["root_present"], "the declared external root is not a directory"
    missing = [
        f"{row['name']}: {item['declared']}"
        for row in index["entries"]
        for item in row["external_paths"]
        if not item["exists"]
    ]
    assert missing == []
