"""The external-resource index must stay in step with the declaration, and must resolve here.

Three failure modes this guards, all of which actually happened in this repository:

* a declaration that points somewhere the resolver cannot find, so an installed engine is reported
  missing (the worker resolver deliberately refuses to guess on PATH, so the declaration is the only
  route);
* a model that real runs depend on but that no declaration names at all, leaving it discoverable
  only through an environment variable;
* an index that records an availability claim the runtime cannot repeat — including a *version*
  inherited from a wrapper binary, which is how four engines and the CI venv were certified as
  `uv 0.12.23` while `rustc` died and `tesseract --list-langs` aborted.

The index is generated by `scripts/environment/build_external_resources_index.py`, which runs the
probe each entry declares and writes the measured `verification_level`. When the external root is
not present in the environment the resolution and probing half is skipped with an explicit reason,
so a missing root can never read as a clean result — and an index entry is never itself evidence
that a resource is available.
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[2]
MANIFEST = ROOT / "config" / "environment" / "capability-requirements.yaml"
INDEX = ROOT / "config" / "environment" / "external-resources-index.json"
BUILDER = ROOT / "scripts" / "environment" / "build_external_resources_index.py"
ROOT_ENV = ("ARCHEAXIS_EXTERNAL_ROOT", "OS_EXTERNAL_CONFIG")
LEVELS = ("REGISTERED", "FILE_EXISTS", "VERSION_PROBED", "RESULT_VERIFIED")


def declared_entries() -> list[dict]:
    import yaml

    document = yaml.safe_load(MANIFEST.read_text(encoding="utf-8")) or {}
    found = []
    for category, group in (document.get("capabilities") or {}).items():
        for entry in group or []:
            if isinstance(entry, dict):
                found.append({**entry, "category": category})
    return found


def index_document() -> dict:
    return json.loads(INDEX.read_text(encoding="utf-8"))


def test_index_covers_exactly_the_declared_entries():
    index = index_document()
    assert index["schema"] == "archeaxis/external-resources-index/v2"
    indexed = {(row["category"], row["name"]) for row in index["entries"]}
    expected = {(entry["category"], entry["name"]) for entry in declared_entries()}
    assert indexed == expected, f"index and manifest disagree: {indexed ^ expected}"


def test_every_row_carries_the_binding_fields_a_consumer_needs():
    """An index row is a contract, not a path list.

    Without `resource_id` a rename silently orphans a consumer; without the two licences a model's
    weight terms get published under its code licence; without `required_env` a row says "present"
    about an engine that cannot start; without `failure_message`/`fallback` an unavailable resource
    has no defined next step.
    """
    required = ("resource_id", "type", "purpose", "platform", "host_platform",
                 "version_identification", "project_entry", "required_env", "writability",
                 "detection", "verification_level", "available", "binding", "code_license",
                 "asset_license", "fallback", "external_paths")
    problems = []
    for row in index_document()["entries"]:
        for field in required:
            if field not in row:
                problems.append(f"{row['name']}: missing field {field}")
        if not row["resource_id"].startswith("ext."):
            problems.append(f"{row['name']}: resource_id is not stable-prefixed")
        if row["writability"] not in ("shared_read_only", "shared_writable_by_project",
                                      "project_writable"):
            problems.append(f"{row['name']}: writability is not a stated ownership class")
        if not row["available"] and not row["failure_message"]:
            problems.append(f"{row['name']}: unavailable without a failure message")
    assert not problems, "; ".join(problems)


def test_model_asset_terms_are_never_carried_by_the_code_license():
    """Weights and code are two documents; one field cannot hold both claims."""
    unlicenced_assets = [
        row["name"] for row in index_document()["entries"]
        if row["type"] == "model" and not row["asset_license"]
    ]
    assert unlicenced_assets == [], f"model rows without separate asset terms: {unlicenced_assets}"


def test_every_declared_external_path_is_recorded():
    index = index_document()
    declared = {
        (entry["category"], entry["name"]): [p for p in (entry.get("external_paths") or []) if isinstance(p, str)]
        for entry in declared_entries()
    }
    for row in index["entries"]:
        recorded = [item["declared"] for item in row["external_paths"]]
        assert recorded == declared[(row["category"], row["name"])]


def test_no_row_claims_a_level_above_its_own_probe():
    """`probe.reaches` is the ceiling a declaration may assert; the index reports what ran."""
    for entry in declared_entries():
        reaches = (entry.get("probe") or {}).get("reaches")
        if reaches not in LEVELS:
            continue
        row = next(item for item in index_document()["entries"] if item["name"] == entry["name"])
        assert row["ceiling_respected"] is True, (
            f"{row['name']}: measured {row['verification_level']} above declared ceiling {reaches}")


@pytest.mark.skipif(
    not any(os.environ.get(name, "").strip() for name in ROOT_ENV),
    reason="no external root in the environment; resolution is skipped rather than assumed clean",
)
def test_declared_paths_resolve_on_this_host(tmp_path):
    # Rebuild with the environment this test was given, stated rather than inherited implicitly,
    # so the assertion is about the current manifest and a known external root. The rebuild goes
    # to a temporary target: this index records host-specific absolute paths, and regenerating it
    # into the tracked file made every test run leave the tree modified, so a development receipt
    # could no longer be attributed to the change it claimed to record.
    output = tmp_path / "external-resources-index.json"
    environment = {**os.environ, "ARCHEAXIS_INDEX_OUTPUT": str(output)}
    subprocess.run([sys.executable, "-B", str(BUILDER)], check=True, capture_output=True,
                   cwd=ROOT, env=environment)
    index = json.loads(output.read_text(encoding="utf-8"))
    assert index["root_present"], "the declared external root is not a directory"
    missing = [
        f"{row['name']}: {item['declared']}"
        for row in index["entries"]
        for item in row["external_paths"]
        if not item["exists"]
    ]
    assert missing == []


@pytest.mark.skipif(
    not any(os.environ.get(name, "").strip() for name in ROOT_ENV),
    reason="no external root in the environment; the probes cannot be re-run here",
)
def test_a_green_index_cannot_certify_a_row_that_does_not_answer_again():
    """Re-run every RESULT_VERIFIED row through the same entry the index used.

    This is the gate the old suite did not have: nine tests passed in under two seconds while
    `rustc` failed standalone, `tesseract --list-langs` aborted, MSVC recorded an error string as
    its version, and four engines inherited `uv`'s version. A row that claims a result must
    produce it again here, or the run is red.
    """
    sys.path.insert(0, str(ROOT))
    from scripts.workflow import environment_registry

    report = environment_registry.resolve(
        MANIFEST, workdir=Path(os.environ.get("TEMP", ".")) / "archeaxis-resource-recheck")
    rows = {row["id"]: row for row in report["capabilities"]}
    claimed = [item for item in index_document()["entries"]
               if item["verification_level"] == "RESULT_VERIFIED"]
    assert claimed, "no RESULT_VERIFIED row exists, which would make this gate vacuous"
    drift = []
    for item in claimed:
        fresh = rows[f"{item['category']}/{item['name']}"]
        if fresh["verification_level"] != "RESULT_VERIFIED":
            drift.append(f"{item['name']}: index says RESULT_VERIFIED, a re-run gives "
                         f"{fresh['verification_level']} ({fresh['probe_evidence'].get('reason')})")
    assert drift == [], "; ".join(drift)


def test_the_index_and_the_runtime_resolver_agree_about_every_declared_path() -> None:
    """The artefact that says a resource is findable must agree with the code that finds it.

    This is the failure that actually happened: the index resolved the `../Model library/...` form
    itself and recorded `exists: true` for the ASR weights, while the runtime resolver rejects `..`
    and raised `ToolNotFound` for the same name. A verification artefact that certifies a path no
    runtime can reach is worse than no artefact, because it hides the failure it exists to catch.
    """
    import importlib.util

    root_value = ""
    for name in ROOT_ENV:
        root_value = os.environ.get(name, "").strip()
        if root_value:
            break
    if not root_value:
        pytest.skip("no external root in this environment; resolution cannot be compared")

    index = index_document()
    assert index["external_root"], index
    spec = importlib.util.spec_from_file_location(
        "cross_reader_tool_paths", ROOT / "services" / "python-workers" / "tool_paths.py")
    assert spec and spec.loader
    resolver = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(resolver)

    compared = 0
    for entry in index["entries"]:
        for resolution in entry["external_paths"]:
            compared += 1
            try:
                found = resolver.tool_path(entry["name"])
            except Exception as error:  # the resolver's own named failure
                assert not resolution["exists"], (
                    f"the index claims {entry['name']} exists at {resolution['resolved']} "
                    f"but the runtime resolver cannot reach it: {error}")
                continue
            assert resolution["exists"], (
                f"the runtime resolver found {entry['name']} at {found} "
                f"but the index recorded exists=false")
    assert compared, "no declared external path was compared, which would make this test vacuous"


def test_the_index_and_the_runtime_agree_about_required_process_env() -> None:
    """One declaration of RUSTUP_HOME / TESSDATA_PREFIX, read the same way by both readers.

    The index records `required_env` per row; the runtime resolver produces the values a child
    process needs. If those two ever disagree, the launcher exports one thing while the inventory
    certifies another — and the row still reads as available.
    """
    import importlib.util

    root_value = ""
    for name in ROOT_ENV:
        root_value = os.environ.get(name, "").strip()
        if root_value:
            break
    if not root_value:
        pytest.skip("no external root in this environment; nothing to resolve")

    spec = importlib.util.spec_from_file_location(
        "env_agreement_tool_paths", ROOT / "services" / "python-workers" / "tool_paths.py")
    assert spec and spec.loader
    resolver = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(resolver)

    checked = 0
    for row in index_document()["entries"]:
        declared = (next((entry for entry in declared_entries() if entry["name"] == row["name"]),
                         {}) or {}).get("required_env") or {}
        if not declared:
            continue
        runtime = resolver.required_environment(row["name"])
        assert set(runtime) == set(declared), (
            f"{row['name']}: the resolver could not produce every declared variable, "
            f"missing {sorted(set(declared) - set(runtime))}")
        for variable, location in declared.items():
            assert Path(runtime[variable]).name == Path(location).name, (
                f"{row['name']}.{variable}: index says {location}, resolver says {runtime[variable]}")
            assert Path(runtime[variable]).exists(), f"{row['name']}.{variable} does not exist"
        checked += 1
    assert checked >= 2, f"only {checked} rows carry required_env; the agreement check is vacuous"


def test_a_traversing_declaration_is_refused_by_both_readers(monkeypatch, tmp_path) -> None:
    """`..` stays refused in `external_paths` by both readers; a shared resource is named instead.

    Allowing the traversal would have made the index agree with reality at the cost of the
    boundary, so the fix had to reach the sibling by declaring it. This falsifies both readers:
    each must refuse a traversal even when the target really exists.
    """
    import importlib.util

    root = tmp_path / "OS External Configuration"
    (root / "inside").mkdir(parents=True)
    outside = tmp_path / "Model library" / "weights"
    outside.mkdir(parents=True)
    monkeypatch.setenv("ARCHEAXIS_EXTERNAL_ROOT", str(root))

    spec = importlib.util.spec_from_file_location(
        "boundary_tool_paths", ROOT / "services" / "python-workers" / "tool_paths.py")
    assert spec and spec.loader
    resolver = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(resolver)

    # The runtime resolver: a traversal reaches nothing, a declared sibling root reaches it.
    traversing = {"capabilities": {"models": [
        {"name": "probe", "external_paths": ["../Model library/weights"]}]}}
    manifest = tmp_path / "traversing.yaml"
    manifest.write_text(json.dumps(traversing), encoding="utf-8")
    assert resolver._candidates("probe", manifest) == []

    declared = {"capabilities": {"models": [
        {"name": "probe", "sibling_root": "model-library",
         "external_paths": ["weights"]}]}, "sibling_roots": {"model-library": "../Model library"}}
    manifest.write_text(json.dumps(declared), encoding="utf-8")
    assert resolver._candidates("probe", manifest) == [outside]

    # The index builder's own resolver: same refusal, same reason.
    spec = importlib.util.spec_from_file_location(
        "boundary_index_builder", BUILDER)
    assert spec and spec.loader
    builder = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(builder)
    assert builder.resolve("../Model library/weights", root) == ("", False)
    assert builder.resolve("inside", root)[1] is True

    # And the manifest this repository actually ships carries no traversal at all.
    paths = [p for entry in declared_entries() for p in (entry.get("external_paths") or [])
             if isinstance(p, str)]
    assert paths, "no declared external path to check"
    assert not [p for p in paths if ".." in Path(p).parts], (
        "a declared external path traverses; use sibling_root instead")


def test_the_index_is_written_with_lf_on_every_host(tmp_path, monkeypatch) -> None:
    """A tracked generated file must not change line endings depending on who regenerated it.

    This host's own test rebuilds the index in place, so platform newlines left the tree modified
    after an otherwise clean run - and a dirty tree makes a development receipt unattributable to
    the change it claims to record.
    """
    import importlib.util

    spec = importlib.util.spec_from_file_location("newline_index_builder", BUILDER)
    assert spec and spec.loader
    builder = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(builder)
    target = tmp_path / "external-resources-index.json"
    monkeypatch.setattr(builder, "INDEX", target)
    assert builder.main() == 0
    written = target.read_bytes()
    assert b"\r" not in written, "the builder wrote platform newlines into a tracked artefact"
    assert json.loads(written.decode("utf-8"))["schema"] == "archeaxis/external-resources-index/v2"
    assert b"\r" not in INDEX.read_bytes(), "the committed index is not the LF form the builder writes"


def test_an_unavailable_row_states_why_and_never_a_version(tmp_path, monkeypatch) -> None:
    """The unavailable path has to be a named answer, not an empty one.

    A row whose lane is down is recorded as `unavailable` with the observed error and no version;
    a probe that cannot run on this platform is `NOT_RUN` with a reason. Neither may inherit a
    neighbouring row's identity, and neither may be written as a bare `false`.
    """
    import importlib.util

    root = tmp_path / "external"
    (root / "inside").mkdir(parents=True)
    monkeypatch.setenv("ARCHEAXIS_EXTERNAL_ROOT", str(root))
    spec = importlib.util.spec_from_file_location("unavailable_registry",
                                                 ROOT / "scripts" / "workflow" / "environment_registry.py")
    assert spec and spec.loader
    registry = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(registry)

    manifest = tmp_path / "capabilities.yaml"
    manifest.write_text(json.dumps({"capabilities": {"models": [
        {"name": "dead-lane", "endpoint": {"protocol": "openai",
                                           "base_url": "http://127.0.0.1:59999/v1",
                                           "list_path": "/models"},
         "probe": {"kind": "http_get", "expect_status": 200, "reaches": "VERSION_PROBED"}}]}}),
        encoding="utf-8")
    row = registry.resolve(manifest)["capabilities"][0]
    assert row["verification_level"] == "unavailable"
    assert row["version_observed"] is None
    assert "127.0.0.1:59999" in row["probe_evidence"]["url"]
    assert row["unavailable_reason"], "an unavailable row must say why"
