import { useEffect, useRef, useState, type ReactNode } from "react";
import { documentRequestIdentity } from "../presentation/documentRequestIdentity";
import { coreCommand } from "../api/core";
import { ApiError } from "../api/client";
import type { DocumentDto, DocumentSummaryDto, DocumentsListDto, RelationProjectionDto, RelationDto, ObjectReferenceDto, OriginalDto } from "../api/generated/core-contract";
import { AaosDialog } from "../design-system/AaosPrimitives";
import { assertCoreDto, type DocumentRelationsDto } from "../api/generated/core-contract";
type J = Record<string, unknown>;
function nodeTitle(value: object | null, reference: ObjectReferenceDto) { const title = (value as J | null)?.title; return typeof title === "string" ? title : label(reference); }
type Attempt = { operation: "document_create" | "document_draft"; payload: J; editor: J; serial: number; version:number; expectedDocumentId?:string };
type Buffer = { base: DocumentDto | null; envelope: J; relations: RelationDto[]; dirty: boolean; serial: number; attempt?: Attempt; unsupported: boolean };
function object(v: unknown): J { if (!v || typeof v !== "object" || Array.isArray(v)) throw new Error("无效文档结构"); return v as J; }
function canonical(v: unknown): unknown { return Array.isArray(v) ? v.map(canonical) : v && typeof v === "object" ? Object.fromEntries(Object.entries(v).sort(([a], [b]) => a.localeCompare(b)).map(([k, x]) => [k, canonical(x)])) : v; }
function same(a: unknown, b: unknown) { return JSON.stringify(canonical(a)) === JSON.stringify(canonical(b)); }
function fromDoc(d: DocumentDto): Buffer { const envelope = structuredClone(object(d.editor_json)); let relations: RelationDto[] = [], unsupported = false;
  try { const attrs = envelope.attrs ? object(envelope.attrs) : {}, r = attrs.archeaxis_relations;
    if (r !== undefined) { const m = assertCoreDto<DocumentRelationsDto>("DocumentRelationsDto",r);
      relations = structuredClone(m.relations);
    }
  } catch { unsupported = true; }
  return { base: d, envelope, relations, dirty: false, serial: 0, unsupported };
}
function editor(b: Buffer) { return { ...structuredClone(b.envelope), attrs: { ...(b.envelope.attrs ? structuredClone(object(b.envelope.attrs)) : {}), archeaxis_relations: { schema: "archeaxis.relations/v1", relations: structuredClone(b.relations) } } }; }
function label(r: ObjectReferenceDto) { return r.kind === "document" ? `${r.document_id} · v${r.version}${r.block_id ? " · " + r.block_id : ""}` : r.kind === "source" ? `${r.source_id} · ${r.sha256}` : r.knowledge_id; }
export function CanonicalRelationSpace({ onOpenReference, onOpenDocument, renderCollection }: { onOpenReference?: (reference: ObjectReferenceDto) => void; onOpenDocument?: (id: string, version: number, block?: string) => void; renderCollection?: (document: DocumentDto | null, envelope: J, onChange:(envelope:J)=>void, onPendingChange:(pending:boolean)=>void, readOnly:boolean) => ReactNode }) {
  const section = useRef<HTMLElement>(null);
  const buffers = useRef(new Map<string, Buffer>()), active = useRef("new"), mounted = useRef(true), epoch = useRef(0), graphEpoch = useRef(0), locked = useRef(false), listLocked = useRef(false);
  if (!buffers.current.size) buffers.current.set("new", { base: null, envelope: { type: "doc", content: [] }, relations: [], dirty: false, serial: 0, unsupported: false });
  const [, redraw] = useState(0), [rows, setRows] = useState<DocumentSummaryDto[]>([]), [cursor, setCursor] = useState<string | null>(null), [busy, setBusy] = useState(false), [message, setMessage] = useState("读取文档列表…"), [failed, setFailed] = useState(false), [pending, setPending] = useState<string | null>(null);
  const [projection, setProjection] = useState<RelationProjectionDto | null>(null), [graphBusy, setGraphBusy] = useState(false), [listOnly, setListOnly] = useState(false), [history, setHistory] = useState<DocumentDto | null>(null), [version, setVersion] = useState("1"), [original, setOriginal] = useState<OriginalDto | null>(null);
  const [kind, setKind] = useState<RelationDto["kind"]>("related"), [relationLabel, setRelationLabel] = useState(""), [targetKind, setTargetKind] = useState<ObjectReferenceDto["kind"]>("document"), [targetId, setTargetId] = useState(""), [targetVersion, setTargetVersion] = useState("1"), [block, setBlock] = useState(""), [sha, setSha] = useState("");
  const [collectionPending,setCollectionPending]=useState(false);
  const b = buffers.current.get(active.current)!, formDirty = !!(targetId || relationLabel || block || sha) || collectionPending;
  const pendingInput = useRef(false); pendingInput.current = formDirty;
  function note(m: string, error = false) { if (mounted.current) { setMessage(m); setFailed(error); } }
  function publish() { if (!mounted.current) return; window.dispatchEvent(new CustomEvent("archeaxis-draft-dirty", { detail: [...buffers.current.values()].some(x => x.dirty || x.attempt) || locked.current || formDirty })); redraw(x => x + 1); }
  useEffect(() => { mounted.current = true; void list(false); return () => { mounted.current = false; epoch.current++; graphEpoch.current++; window.dispatchEvent(new CustomEvent("archeaxis-draft-dirty", { detail: false })); }; }, []);
  useEffect(() => { publish(); }, [targetId, relationLabel, block, sha, collectionPending]);
  async function list(more: boolean) { if (listLocked.current) return; listLocked.current = true; try { const r = await coreCommand<DocumentsListDto>("documents_list", more && cursor ? { cursor } : {}); if (!mounted.current) return; setRows(old => more ? [...old, ...r.documents.filter(x => !old.some(y => y.document_id === x.document_id))] : r.documents); setCursor(r.next_cursor); note("文档列表已读取；关系绑定实际对象版本。"); } catch { note("文档列表读取失败；未当成空列表。", true); } finally { listLocked.current = false; } }
  async function graph(d: DocumentDto, next?: string) { const token = ++graphEpoch.current; setGraphBusy(true); try { const r = await coreCommand<RelationProjectionDto>("document_graph", { document_id: d.document_id, version: d.version, ...(next ? { cursor: next } : {}) }); if (!mounted.current || token !== graphEpoch.current) return; if (r.center.document_id !== d.document_id || r.center.version !== d.version || r.center.content_sha256 !== d.content_sha256) throw new Error("图投影身份不符"); setProjection(r); note("关系投影已读取；图与列表共用这一页固定版本。"); } catch { if (mounted.current && token === graphEpoch.current) { setProjection(null); note("关系投影读取失败；未报告无关系。", true); } } finally { if (mounted.current && token === graphEpoch.current) setGraphBusy(false); } }
  async function open(key: string) { if (locked.current) return; const token = ++epoch.current, prior = active.current, serial = b.serial; graphEpoch.current++; setPending(null); setHistory(null); setOriginal(null); setProjection(null); setGraphBusy(false);
    if (key === "__new") { const k = `local_${crypto.randomUUID()}`; buffers.current.set(k, { base: null, envelope: { type: "doc", content: [] }, relations: [], dirty: false, serial: 0, unsupported: false }); active.current = k; publish(); return; }
    try { let current = buffers.current.get(key); if (!current) current = fromDoc(await coreCommand<DocumentDto>("document_get", { document_id: key })); if (current.base?.document_id !== key) throw new Error("文档身份不符"); if (!mounted.current || token !== epoch.current) return; if (active.current !== prior || buffers.current.get(prior)?.serial !== serial || pendingInput.current) { note("读取期间新增编辑仍保留；请重新选择对象。"); return; } buffers.current.set(key, current); active.current = key; publish(); if (current.unsupported) note("未知关系结构保留；仅只读，未转换。", true); if (current.base) void graph(current.base); } catch { if (mounted.current && token === epoch.current) note("读取失败；当前草稿保留。", true); }
  }
  function requestOpen(key: string) { if (locked.current) return; if (formDirty) { note("请先添加或取消未提交关系；输入保留。", true); return; } if (b.dirty || b.attempt) setPending(key); else void open(key); }
  function clearForm() { setTargetId(""); setRelationLabel(""); setBlock(""); setSha(""); }
  function change(relations: RelationDto[]) { if (b.unsupported || history) return; b.relations = relations; b.serial++; b.dirty = true; publish(); }
  function add() { try { const id = targetId.trim(); if (!id) throw new Error(); let target: ObjectReferenceDto;
    if (targetKind === "document") { const v = Number(targetVersion); if (!Number.isSafeInteger(v) || v < 1) throw new Error(); target = { kind: "document", document_id: id, version: v, ...(block ? { block_id: block } : {}) }; }
    else if (targetKind === "source") { if (!/^[a-f0-9]{64}$/.test(sha)) throw new Error(); target = { kind: "source", source_id: id, sha256: sha }; }
    else target = { kind: "knowledge", knowledge_id: id };
    change([...b.relations, { id: `relation_${crypto.randomUUID()}`, kind, label: relationLabel, target }]); clearForm(); note("关系已加入草稿；尚未由Core验证或保存。");
  } catch { note("请填写真实目标与正整数版本 / 来源SHA；输入保留。", true); } }
  async function save() { if (locked.current || b.unsupported || history || formDirty) { if (formDirty) note("未提交关系仍保留；请先添加或取消。", true); return; } locked.current = true; setBusy(true); publish(); const current = b; let writeAcknowledged = false;
    try { const attempt: Attempt = current.attempt ?? (() => { const e = editor(current); return { operation: current.base ? "document_draft" as const : "document_create" as const, payload: current.base ? { document_id: current.base.document_id, body: { expected_version: current.base.version, editor_json: e } } : { body: { create_request_id: `relations_${crypto.randomUUID()}`, title: "关系文档", editor_json: e } }, editor: e, serial: current.serial, version:current.base?current.base.version+1:1 }; })(); current.attempt = attempt;
      if (attempt.operation === "document_create" && !attempt.expectedDocumentId) attempt.expectedDocumentId = await documentRequestIdentity(String(object(attempt.payload.body).create_request_id));
      const saved = await coreCommand<DocumentDto>(attempt.operation, attempt.payload); writeAcknowledged = true;
      if (attempt.operation === "document_create" && (saved.document_id !== attempt.expectedDocumentId || saved.title !== object(attempt.payload.body).title || saved.source_id !== null || saved.source_revision !== null)) throw new Error("新建回执身份不符"); if (current.base && saved.document_id !== current.base.document_id) throw new Error("保存身份不符"); const d = await coreCommand<DocumentDto>("document_get", { document_id: saved.document_id }); if ((attempt.operation === "document_create" && (d.document_id !== attempt.expectedDocumentId || d.title !== object(attempt.payload.body).title || d.source_id !== null || d.source_revision !== null)) || d.document_id !== saved.document_id || d.version !== saved.version || d.version !== attempt.version || d.content_sha256 !== saved.content_sha256 || !same(d.editor_json, attempt.editor)) throw new Error("保存读回不一致"); accept(current, d, attempt); note(current.dirty ? "已保存发送时的版本；随后编辑仍是未保存草稿。" : "关系已保存并读回核对。"); void graph(d);
    } catch (error) { if (!writeAcknowledged && error instanceof ApiError && error.status === 400) { current.attempt = undefined; current.dirty = true; note("Core已明确拒绝此请求，未保存；全部草稿保留，可修改后重新保存。", true); } else note("保存未确认；草稿与冻结请求保留。冲突需核对，未报告成功。", true); } finally { locked.current = false; if (mounted.current) { setBusy(false); publish(); } }
  }
  function accept(current: Buffer, d: DocumentDto, attempt: Attempt) { current.base = d; current.attempt = undefined; current.dirty = current.serial !== attempt.serial; if (!current.dirty) { current.envelope = structuredClone(object(d.editor_json)); current.relations = fromDoc(d).relations; } buffers.current.set(d.document_id, current); if (mounted.current) setRows(old => [d, ...old.filter(x => x.document_id !== d.document_id)]); }
  async function reconcile() { if (!b.base || locked.current) return; if (pendingInput.current) { note("请先完成或取消未提交关系／集合输入；当前输入保留。", true); return; } locked.current = true; setBusy(true); const current = b, serial = b.serial, key = active.current, token = epoch.current; try { const d = await coreCommand<DocumentDto>("document_get", { document_id: current.base!.document_id }); if (!mounted.current || active.current !== key || epoch.current !== token) return; if (pendingInput.current || current.serial !== serial) { note("核对期间新增输入保留；未切换版本，请完成输入后重新核对。"); return; } if (d.document_id !== current.base!.document_id) throw new Error(); const a = current.attempt; if (a?.operation === "document_draft" && d.version === current.base!.version + 1 && same(d.editor_json, a.editor)) { accept(current, d, a); note("最新Core版本与冻结保存匹配；随后编辑保留。"); void graph(d); } else if (d.version === current.base!.version) note("Core版本未变化；草稿与冻结请求保留。"); else { setHistory(d); note("最新版本不同，仅只读比较；原草稿和expected_version保留。", true); } } catch { note("核对失败；草稿保留。", true); } finally { locked.current = false; setBusy(false); publish(); } }
  async function readHistory() { if (!b.base || locked.current) return; if (pendingInput.current) { note("请先完成或取消未提交关系／集合输入；未进入历史，当前输入保留。", true); return; } const v = Number(version); if (!Number.isSafeInteger(v) || v < 1) { note("历史版本必须是正整数。", true); return; }
    const token = ++epoch.current, key = active.current, current = b, serial = b.serial, id = b.base.document_id, baseVersion = b.base.version;
    try { const d = await coreCommand<DocumentDto>("document_version", { document_id: id, version: v }); if (!mounted.current || token !== epoch.current || active.current !== key) return; if (current.serial !== serial || current.base?.version !== baseVersion || pendingInput.current || locked.current) { note("历史读取期间新增编辑仍保留；未切换为只读历史，请重新审阅。"); return; } if (d.document_id !== id || d.version !== v) throw new Error(); setHistory(d); void graph(d); note("历史版本只读；当前关系草稿保留。"); }
    catch { if (mounted.current && token === epoch.current && active.current === key && current.serial === serial && current.base?.version === baseVersion) note("历史版本不可用；未替换为最新版本。", true); }
  }
  async function follow(r: ObjectReferenceDto) { if (onOpenReference) { onOpenReference(r); return; } if (r.kind === "document") { if (b.dirty || b.attempt || formDirty) { note("请先保存或留在此页；未跳转，草稿保留。", true); return; } if (onOpenDocument) onOpenDocument(r.document_id, r.version, r.block_id ?? undefined); else note("固定文档详情入口尚未接通；未跳转到最新版本。", true); }
    else if (r.kind === "source") { const token = epoch.current; const key = active.current; try { const o = await coreCommand<OriginalDto>("source_original", { source_id: r.source_id }); if (o.source_id !== r.source_id || o.sha256 !== r.sha256) throw new Error(); const bytes = Uint8Array.from(atob(o.content_base64), c => c.charCodeAt(0)); const digest = Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256", bytes))).map(x => x.toString(16).padStart(2, "0")).join(""); if (digest !== r.sha256) throw new Error(); if (mounted.current && token === epoch.current && key === active.current) { setOriginal(o); note("来源原件身份与实际字节SHA已核对。"); } } catch { if (mounted.current && token === epoch.current && key === active.current) note("原件读取或SHA核对失败；未打开错误原件。", true); } }
    else note(`知识引用 ${r.knowledge_id}：本页未实现知识详情跳转；未伪造文档版本。`);
  }
  const shown = history ? fromDoc(history).relations : b.relations;
  return <section ref={section} tabIndex={-1} aria-label="关系工作区" className="ui-relations-page"><h2>双链与关系工作区</h2><p role={failed ? "alert" : "status"}>{message}</p><p>文档关系由Core保存；图形只是同一版本的投影。学术检索 / GraphRAG：NOT_EXECUTED。</p>
    <button onClick={() => requestOpen("__new")} disabled={busy}>新关系草稿</button><button onClick={() => void list(false)} disabled={busy}>刷新文档</button><button disabled={busy || b.unsupported || !!history || formDirty || (!b.dirty && !b.attempt)} onClick={() => void save()}>{b.attempt ? "重试冻结保存" : "保存关系草稿"}</button><button onClick={() => void reconcile()} disabled={!b.base || busy}>核对最新版本（保留草稿）</button>
    <ul aria-label="已保存文档">{rows.map(d => <li key={d.document_id}><button disabled={busy} onClick={() => requestOpen(d.document_id)}>{d.title} · v{d.version}</button></li>)}</ul>{cursor && <button onClick={() => void list(true)}>加载更多文档</button>}
    <p>{b.base ? `${b.base.document_id} · v${b.base.version}` : "本地未登记草稿"} · {b.dirty ? "未保存编辑" : "无未保存编辑"}</p>
    {b.unsupported && <details><summary>保留的原始文档（只读）</summary><pre style={{ whiteSpace: "pre-wrap", overflowWrap: "anywhere" }}>{JSON.stringify(b.envelope, null, 2)}</pre></details>}
    <fieldset disabled={busy || b.unsupported || !!history}><legend>关系编辑</legend><label>关系类型<select value={kind} onChange={e => setKind(e.target.value as RelationDto["kind"])}>{["related", "supports", "contradicts", "depends_on"].map(x => <option key={x}>{x}</option>)}</select></label><label>关系说明<input value={relationLabel} onChange={e => setRelationLabel(e.target.value)}/></label><label>目标类型<select value={targetKind} onChange={e => setTargetKind(e.target.value as ObjectReferenceDto["kind"])}><option>document</option><option>source</option><option>knowledge</option></select></label><label>目标对象ID<input value={targetId} onChange={e => setTargetId(e.target.value)}/></label>{targetKind === "document" && <><label>固定目标版本<input value={targetVersion} onChange={e => setTargetVersion(e.target.value)}/></label><label>目标Block ID<input value={block} onChange={e => setBlock(e.target.value)}/></label></>}{targetKind === "source" && <label>来源SHA256<input value={sha} onChange={e => setSha(e.target.value)}/></label>}<button onClick={add}>加入关系草稿</button><button onClick={clearForm}>取消未提交关系</button>
      <ul aria-label="关系草稿">{shown.map(r => <li key={r.id}>{r.kind} · {r.label} · {label(r.target)} <button onClick={() => change(b.relations.filter(x => x.id !== r.id))} aria-label={`删除关系 ${r.id}`}>删除</button></li>)}</ul></fieldset>
    {renderCollection?.(history ?? b.base, history ? object(history.editor_json) : b.envelope, next=>{if(b.unsupported || history)return;b.envelope=structuredClone(next);b.serial++;b.dirty=true;publish();},setCollectionPending,busy || b.unsupported || !!history)}
    <label>历史版本<input value={version} onChange={e => setVersion(e.target.value)}/></label><button disabled={!b.base || busy} onClick={() => void readHistory()}>读取历史关系（只读）</button>{history && <><p>只读比较 v{history.version}；未覆盖草稿</p><button onClick={() => { epoch.current++; setHistory(null); if (b.base) void graph(b.base); }}>返回当前草稿</button></>}
    <button disabled={!b.base || graphBusy} onClick={() => b.base && void graph(history ?? b.base)}>刷新关系投影</button><button onClick={() => setListOnly(x => !x)}>{listOnly ? "显示关系图" : "图形不可用，切换列表"}</button>
    {projection && <><p>投影中心 {projection.center.document_id} · v{projection.center.version}；扫描当前来源版本 {projection.scan.scanned} 项；{projection.scan.complete ? "这一范围扫描完成" : "扫描尚未完成，不能断言全库无关系"}；游标 {projection.scan.next_cursor ?? "无"}；不支持的来源 {projection.unsupported_sources.length}</p>{projection.projection_truncated && <p role="alert">这一页达到 1000 条关系的显示上限，另有 {projection.omitted_edges} 条未显示；图与列表均为部分投影。请打开来源固定版本／集合视图查看完整定义。</p>}{projection.scan.next_cursor && <button disabled={graphBusy} onClick={() => void graph(history ?? b.base!, projection.scan.next_cursor!)}>读取下一页反链</button>}
      {!listOnly && <div aria-label="同版本关系图" style={{ overflow: "auto", maxWidth: "100%" }}><svg viewBox={`0 0 880 ${Math.max(320, Math.ceil(projection.nodes.length / 4) * 180 + 40)}`} width="880" height={Math.max(320, Math.ceil(projection.nodes.length / 4) * 180 + 40)} style={{ color: "var(--ax-fg)" }}>
        {projection.edges.map((e, i) => { const ai = projection.nodes.findIndex(n => n.key === e.from), bi = projection.nodes.findIndex(n => n.key === e.to); if (ai < 0 || bi < 0) return null; const a = { x: 110 + (ai % 4) * 220, y: 85 + Math.floor(ai / 4) * 180 }, c = { x: 110 + (bi % 4) * 220, y: 85 + Math.floor(bi / 4) * 180 }; const lane = Math.max(a.y, c.y) + 30 + (i % 3) * 24, labelX = ai === bi ? a.x + 25 : (a.x + c.x) / 2; const path = ai === bi ? `M ${a.x} ${a.y} V ${lane} H ${a.x + 50} V ${a.y} H ${a.x}` : `M ${a.x} ${a.y} V ${lane} H ${c.x} V ${c.y}`; return <g key={e.id + i} data-relation-edge={e.id}><title>{e.direction} · {e.relation.kind} · {e.relation.label}</title><path d={path} fill="none" stroke="var(--ax-control-border)"/><text data-relation-label={e.id} x={labelX} y={lane - 6} textAnchor="middle" fill="currentColor"><title>{e.relation.label || e.relation.kind}</title>{`${i + 1}. ${(e.relation.label || e.relation.kind).slice(0, 20)}`}</text></g>; })}
        {projection.nodes.map((n, i) => <g key={n.key} role="button" aria-label={`图节点 ${label(n.reference)} · ${n.status}`} tabIndex={n.status === "resolved" ? 0 : -1} onClick={() => n.status === "resolved" && void follow(n.reference)} onKeyDown={e => { if ((e.key === "Enter" || e.key === " ") && n.status === "resolved") { e.preventDefault(); void follow(n.reference); } }}><title>{label(n.reference)} · {n.status}</title><rect data-relation-node={n.key} x={10 + (i % 4) * 220} y={25 + Math.floor(i / 4) * 180} width="200" height="60" rx="8" fill="var(--ax-panel)" stroke="var(--ax-border)"/><text x={20 + (i % 4) * 220} y={50 + Math.floor(i / 4) * 180} fill="currentColor">{nodeTitle(n.object, n.reference).slice(0, 24)}</text><text x={20 + (i % 4) * 220} y={73 + Math.floor(i / 4) * 180} fill="currentColor">{n.status === "resolved" ? "固定对象可读" : "目标不可用"}</text></g>)}
      </svg></div>}
      <ul aria-label="同版本关系列表">{projection.edges.map((e, i) => <li key={e.id + i}>{e.direction === "backlink" ? "反链" : "出链"} · {e.relation.kind} · {e.relation.label}{e.origin === "collection_property" ? ` · 集合记录 ${e.record_id}／属性 ${e.property_id}` : ""} · 来源 <button onClick={() => void follow({ kind: "document", document_id: e.source_snapshot.document_id, version: e.source_snapshot.version })}>{e.source_snapshot.document_id} v{e.source_snapshot.version}</button><button onClick={() => void follow(e.direction === "backlink" ? (projection.nodes.find(n => n.key === e.from)?.reference ?? { kind: "document", document_id: e.source_snapshot.document_id, version: e.source_snapshot.version }) : e.relation.target)}>打开固定对象 {e.direction === "backlink" ? label(projection.nodes.find(n => n.key === e.from)?.reference ?? { kind: "document", document_id: e.source_snapshot.document_id, version: e.source_snapshot.version }) : label(e.relation.target)}</button></li>)}</ul>{!projection.edges.length && <p>此页没有关系记录；仅限上述扫描范围。</p>}<ul aria-label="投影节点">{projection.nodes.map(n => <li key={n.key}>{label(n.reference)} · {n.status === "resolved" ? "已解析" : "目标不可用，未替换最新对象"}<button disabled={n.status !== "resolved"} onClick={() => void follow(n.reference)}>打开节点 {n.key}</button></li>)}</ul></>}
    {original && <details open><summary>已核对本地原件</summary><p>{original.name} · {original.media_type} · {original.sha256}；原件字节已读取，不执行附件。</p></details>}
    <AaosDialog onCloseAutoFocus={event => { event.preventDefault(); section.current?.focus(); }} trigger={<button disabled={!pending}>审阅关系对象切换</button>} open={!!pending} title="保留关系草稿后切换" description="未保存草稿保留在当前页；取消返回编辑。" onOpenChange={v => { if (!v) setPending(null); }}><p>当前草稿保留在本页会话；关闭页面后的恢复尚未证明。</p><button onClick={() => setPending(null)}>取消切换</button><button onClick={() => pending && void open(pending)}>保留草稿并切换</button></AaosDialog>
  </section>;
}
