import { useEffect, useRef, useState } from "react";
import { coreCommand } from "../api/core";
import { documentRequestIdentity } from "../presentation/documentRequestIdentity";
import type { DocumentDto, DocumentsListDto, DocumentSummaryDto, SourcesListDto, SourceDto, OriginalDto, SearchDto, DocumentExportDto } from "../api/generated/core-contract";
import { Section } from "../components/RealData";
import { RawReceiptButton } from "../components/DiagnosticConsole";
import { AaosDialog } from "../design-system/AaosPrimitives";
import type { ObjectTrailLevel } from "../components/NavTrail";

import type { ObjectReference, ResearchDocument } from "../api/generated/research-contract";
export type { ResearchEntry, ResearchConclusion } from "../api/generated/research-contract";
export type ResearchReference = ObjectReference;
export type ResearchValue = ResearchDocument;
type EntrySection = "hypotheses" | "methods" | "experiments" | "counterevidence" | "unresolved";
type Target = { kind: "material" } | { kind: EntrySection; id: string } | { kind: "conclusion"; id: string; field: "sources" | "basis" };
type Attempt = { operation: "document_create" | "document_draft"; payload: Record<string, unknown>; editor: Record<string, unknown>; serial: number; version: number; expectedDocumentId?: string };
type Buffer = { value: ResearchValue; envelope: Record<string, unknown>; title: string; base: DocumentDto | null; serial: number; dirty: boolean; attempt?: Attempt };
const sections: [EntrySection, string][] = [["hypotheses", "假设"], ["methods", "方法"], ["experiments", "实验"], ["counterevidence", "反证"], ["unresolved", "未决"]];
const blank = (): ResearchValue => ({ schema: "archeaxis.research/v1", question: "", materials: [], hypotheses: [], methods: [], experiments: [], counterevidence: [], conclusions: [], unresolved: [] });
const bytes = (s: string) => new TextEncoder().encode(s).length;
function object(v: unknown): v is Record<string, unknown> { return !!v && typeof v === "object" && !Array.isArray(v); }
function keys(v: Record<string, unknown>, allowed: string[]) { return Object.keys(v).every(k => allowed.includes(k)); }
function token(v: unknown, max = 256): v is string { return typeof v === "string" && v.length > 0 && v.length <= max && v !== "." && v !== ".." && /^[A-Za-z0-9_.-]+$/.test(v); }
function reference(v: unknown): v is ResearchReference {
  if (!object(v)) return false;
  if (v.kind === "document") return keys(v,["kind","document_id","version","block_id"]) && token(v.document_id) && Number.isSafeInteger(v.version) && Number(v.version) > 0 && (v.block_id == null || token(v.block_id));
  if (v.kind === "source") return keys(v,["kind","source_id","sha256"]) && token(v.source_id) && typeof v.sha256 === "string" && /^[a-f0-9]{64}$/.test(v.sha256);
  return v.kind === "knowledge" && keys(v,["kind","knowledge_id"]) && token(v.knowledge_id);
}
export function parseResearch(v: unknown): ResearchDocument | null {
  const fields = ["schema","question","materials","hypotheses","methods","experiments","counterevidence","conclusions","unresolved"];
  if (!object(v) || !keys(v,fields) || v.schema !== "archeaxis.research/v1" || typeof v.question !== "string" || bytes(v.question) > 16384 || !fields.slice(2).every(k=>Array.isArray(v[k]))) return null;
  const ids = new Set<string>(); let refCount = 0; let count = 0;
  function id(item: Record<string, unknown>) { count++; if (!token(item.id,128) || !/^[A-Za-z0-9_-]+$/.test(item.id) || ids.has(item.id)) return false; ids.add(item.id); return true; }
  function refs(value: unknown) { if (!Array.isArray(value)) return false; refCount += value.length; return value.every(reference); }
  for (const item of v.materials as unknown[]) if (!object(item) || !keys(item,["id","note","reference"]) || !id(item) || typeof item.note !== "string" || bytes(item.note)>16384 || !refs([item.reference])) return null;
  for (const [section] of sections) for (const item of v[section] as unknown[]) if (!object(item) || !keys(item,["id","text","references"]) || !id(item) || typeof item.text !== "string" || bytes(item.text)>16384 || !refs(item.references)) return null;
  for (const item of v.conclusions as unknown[]) if (!object(item) || !keys(item,["id","text","sources","basis"]) || !id(item) || typeof item.text !== "string" || bytes(item.text)>16384 || !refs(item.sources) || !refs(item.basis)) return null;
  return count<=256 && refCount<=256 ? v as unknown as ResearchDocument : null;
}
function decode(doc: DocumentDto) { if (!object(doc.editor_json) || !object(doc.editor_json.attrs)) return null; return parseResearch(doc.editor_json.attrs.archeaxis_research); }
function encode(buffer: Buffer) { const e = structuredClone(buffer.envelope); return { ...e, attrs: { ...(object(e.attrs) ? e.attrs : {}), archeaxis_research: structuredClone(buffer.value) } }; }
function canonical(v: unknown): unknown { return Array.isArray(v) ? v.map(canonical) : object(v) ? Object.fromEntries(Object.keys(v).sort().map(k=>[k,canonical(v[k])])) : v; }
function same(a: unknown,b: unknown) { return JSON.stringify(canonical(a)) === JSON.stringify(canonical(b)); }
// Core may assign stable block IDs; all sent fields and unknown body data must still survive.
function preserved(sent: unknown, received: unknown): boolean { return Array.isArray(sent) ? Array.isArray(received) && sent.length===received.length && sent.every((v,i)=>preserved(v,received[i])) : object(sent) ? object(received) && Object.keys(sent).every(k=>preserved(sent[k],received[k])) : sent===received; }
function refName(ref: ResearchReference) { return ref.kind === "document" ? `${ref.document_id} · 版本 ${ref.version}${ref.block_id ? ` · 块 ${ref.block_id}` : ""}` : ref.kind === "source" ? `${ref.source_id} · 原件 SHA ${ref.sha256}` : `${ref.knowledge_id} · 不变知识版本ID`; }

export function CanonicalResearchSpace({ onOpenReference, onOpenDocument, onTrail }: { onOpenReference?: (reference: ObjectReference) => void; onOpenDocument?: (id: string, version: number, block?: string) => void; onTrail?: (levels: readonly ObjectTrailLevel[]) => void }) {
  const buffers = useRef(new Map<string,Buffer>()); if (!buffers.current.size) buffers.current.set("new",{value:blank(),envelope:{type:"doc",content:[]},title:"研究草稿",base:null,serial:0,dirty:false});
  const active=useRef("new"), epoch=useRef(0), mounted=useRef(true), saving=useRef(false), listLock=useRef(false);
  const [, redraw]=useState(0); const [rows,setRows]=useState<DocumentSummaryDto[]>([]),[cursor,setCursor]=useState<string|null>(null),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false);
  const [message,setMessage]=useState("读取研究文档…"),[error,setError]=useState(false),[switchTo,setSwitchTo]=useState<string|null>(null),[history,setHistory]=useState<DocumentDto|null>(null),[unsupported,setUnsupported]=useState<DocumentDto|null>(null),[historyVersion,setHistoryVersion]=useState("1");
  const [target,setTarget]=useState<Target|null>(null),[materialNote,setMaterialNote]=useState(""),[picked,setPicked]=useState<ResearchReference|null>(null),[pickedDoc,setPickedDoc]=useState<DocumentDto|null>(null),[documentBusy,setDocumentBusy]=useState(false),[searchBusy,setSearchBusy]=useState(false),[sources,setSources]=useState<SourceDto[]>([]),[query,setQuery]=useState(""),[knowledgeRows,setKnowledgeRows]=useState<SearchDto["items"]>([]),[sourceRead,setSourceRead]=useState<{ref:ResearchReference;name:string;sha256:string;length:number;text?:string}|null>(null);
  const pickerBusy=documentBusy||searchBusy;
  const historyGeneration=useRef(0);
  const pickerSession=useRef(0), referenceRequest=useRef(0), searchRequest=useRef(0), sourceRequest=useRef(0);
  const pending=useRef(false); pending.current=target!==null || pickerBusy;
  const b=buffers.current.get(active.current)!;
  function publish() { if (!mounted.current) return; window.dispatchEvent(new CustomEvent("archeaxis-draft-dirty",{detail:[...buffers.current.values()].some(v=>v.dirty||!!v.attempt)||saving.current||pending.current})); redraw(n=>n+1); }
  function note(text:string, failed=false) { if(mounted.current){setMessage(text);setError(failed);} }
  useEffect(()=>{ mounted.current=true;void list(false);return()=>{mounted.current=false;epoch.current++;window.dispatchEvent(new CustomEvent("archeaxis-draft-dirty",{detail:false}));};},[]);
  useEffect(()=>{publish();},[target,pickerBusy]);
  useEffect(()=>{onTrail?.([{id:"page:05",label:"研究空间",region:"research"},...(b.base?[{id:b.base.document_id,label:b.base.title,detail:`版本 ${b.base.version}`,region:"research"}]:[])]);},[b.base?.document_id,b.base?.version,onTrail]);
  async function list(more:boolean) {
    if(listLock.current)return;listLock.current=true;setLoading(true);
    try{const page=await coreCommand<DocumentsListDto>("documents_list",more&&cursor?{cursor}:{});if(!Array.isArray(page.documents)||!Number.isSafeInteger(page.snapshot_count)||!(page.next_cursor===null||typeof page.next_cursor==="string"))throw new Error("list shape");if(mounted.current){setRows(old=>more?[...old,...page.documents.filter(d=>!old.some(o=>o.document_id===d.document_id))]:page.documents);setCursor(page.next_cursor);note("已读取真实文档；打开时核对研究格式。");}}
    catch{note("文档列表读取失败；未当成空研究列表。",true);}finally{listLock.current=false;if(mounted.current)setLoading(false);}
  }
  function edit(next:ResearchValue){if(!parseResearch(next)){note("研究结构超出条目／引用／文字限制；当前内容保留。",true);return;}const cur=buffers.current.get(active.current)!;cur.value=structuredClone(next);cur.serial++;cur.dirty=true;historyGeneration.current++;setHistory(null);publish();}
  function changeText(change:()=>ResearchValue,text:string){if(bytes(text)>16384){note("文字超过 16384 UTF-8 字节；未截断或覆盖原文。",true);return;}edit(change());}
  function addEntry(section:EntrySection){edit({...b.value,[section]:[...b.value[section],{id:crypto.randomUUID(),text:"",references:[]}]});}
  async function open(key:string){historyGeneration.current++;sourceRequest.current++;const request=++epoch.current;const old=active.current,serial=buffers.current.get(old)!.serial;setSwitchTo(null);setHistory(null);setUnsupported(null);setSourceRead(null);
    if(key==="__new"){const id=`local_${crypto.randomUUID()}`;buffers.current.set(id,{value:blank(),envelope:{type:"doc",content:[]},title:"研究草稿",base:null,serial:0,dirty:false});active.current=id;publish();return;}
    if(buffers.current.has(key)){active.current=key;publish();return;}
    let received:DocumentDto|null=null;
    try{const doc=await coreCommand<DocumentDto>("document_get",{document_id:key});received=doc;if(doc.document_id!==key)throw new Error("identity");const value=decode(doc);if(!value)throw new Error("unsupported");if(request!==epoch.current||!mounted.current)return;if(active.current!==old||buffers.current.get(old)?.serial!==serial||saving.current){note("读取期间新增编辑保留；请重新选择文档。",true);return;}buffers.current.set(key,{value:structuredClone(value),envelope:structuredClone(doc.editor_json as Record<string,unknown>),title:doc.title,base:doc,serial:0,dirty:false});active.current=key;publish();note("研究对象已读取；内容是作者记录，尚未采用为已核验知识。");}
    catch{if(request===epoch.current&&mounted.current){if(received&&active.current===old&&buffers.current.get(old)?.serial===serial)setUnsupported(received);note("研究读取失败或格式不支持；当前草稿与原始完整文档保留，不转换或覆盖。",true);}}
  }
  function requestOpen(key:string){if(pending.current){note("先完成或取消引用选择；当前临时输入保留。",true);return;}if(saving.current){note("保存尚未确认，当前对象不切换。",true);return;}if(b.dirty||b.attempt){setSwitchTo(key);return;}void open(key);}
  function makeAttempt(cur:Buffer):Attempt{const editor=encode(cur);return {operation:cur.base?"document_draft":"document_create",payload:cur.base?{document_id:cur.base.document_id,body:{expected_version:cur.base.version,editor_json:editor}}:{body:{create_request_id:`research_${crypto.randomUUID()}`,title:cur.title,editor_json:editor}},editor,serial:cur.serial,version:cur.base?cur.base.version+1:1};}
  function accept(cur:Buffer,attempt:Attempt,doc:DocumentDto){const expectedMetadata=object(attempt.editor.attrs)?attempt.editor.attrs.archeaxis_research:null;if(!decode(doc)||doc.version!==attempt.version||!same(decode(doc),expectedMetadata)||!preserved(attempt.editor,doc.editor_json))throw new Error("readback content");cur.base=doc;cur.envelope=structuredClone(doc.editor_json as Record<string,unknown>);cur.attempt=undefined;cur.dirty=cur.serial!==attempt.serial;if(!cur.dirty)cur.value=structuredClone(decode(doc)!);buffers.current.set(doc.document_id,cur);if(mounted.current)setRows(old=>[doc,...old.filter(r=>r.document_id!==doc.document_id)]);note(cur.dirty?"发送时的研究版本已读回；随后编辑仍未保存。":"研究草稿已保存并读回；未变为核验或采用状态。");}
  async function save(){if(saving.current)return;if(pending.current){note("先完成或取消引用选择；保存未发送，临时输入保留。",true);return;}if(unsupported||history){note("原始或历史文档只读；返回当前草稿后保存。",true);return;}historyGeneration.current++;const cur=buffers.current.get(active.current)!;const attempt=cur.attempt??makeAttempt(cur);cur.attempt=attempt;saving.current=true;setBusy(true);publish();
    try{const createBody=attempt.operation==="document_create"?attempt.payload.body as {create_request_id:string;title:string}:null;if(createBody&&!attempt.expectedDocumentId)attempt.expectedDocumentId=await documentRequestIdentity(createBody.create_request_id);const expectedId=attempt.expectedDocumentId??cur.base!.document_id;const matchesIdentity=(doc:DocumentDto)=>doc.document_id===expectedId&&doc.version===attempt.version&&(!createBody||(doc.title===createBody.title&&doc.source_id===null&&doc.source_revision===null));const result=await coreCommand<DocumentDto>(attempt.operation,structuredClone(attempt.payload));if(!matchesIdentity(result))throw new Error("save identity");const read=await coreCommand<DocumentDto>("document_get",{document_id:expectedId});if(!matchesIdentity(read)||read.content_sha256!==result.content_sha256||!same(read.editor_json,result.editor_json))throw new Error("readback identity");accept(cur,attempt,read);}
    catch{note("保存未确认（可能冲突或回执丢失）；草稿和原冻结请求保留。重试相同请求，不另建研究对象。",true);}finally{saving.current=false;if(mounted.current){setBusy(false);publish();}}
  }
  async function reconcile(){if(!b.base||saving.current||pending.current)return;const cur=buffers.current.get(active.current)!;saving.current=true;setBusy(true);publish();try{const read=await coreCommand<DocumentDto>("document_get",{document_id:cur.base!.document_id});if(read.document_id!==cur.base!.document_id)throw new Error("identity");if(cur.attempt&&read.version===cur.attempt.version&&preserved(cur.attempt.editor,read.editor_json))accept(cur,cur.attempt,read);else if(read.version===cur.base!.version)note("Core版本未变化；草稿及冻结请求仍保留，可重试。");else{setUnsupported(read);note("Core版本已不同；最新文档只读，当前草稿与 expected_version 不自动覆盖。",true);}}catch{note("核对最新版本失败；当前草稿保留。",true);}finally{saving.current=false;if(mounted.current){setBusy(false);publish();}}}
  async function readHistory(){if(pending.current||saving.current){note("先完成或取消引用选择／保存；历史未改变临时输入。",true);return;}if(!b.base)return;const id=b.base.document_id,v=Number(historyVersion),request=epoch.current,key=active.current,serial=b.serial,generation=++historyGeneration.current;if(!Number.isSafeInteger(v)||v<1||v>b.base.version){note("请输入已有的正整数历史版本。",true);return;}const current=()=>generation===historyGeneration.current&&request===epoch.current&&active.current===key&&buffers.current.get(key)?.serial===serial&&mounted.current;try{const doc=await coreCommand<DocumentDto>("document_version",{document_id:id,version:v});if(doc.document_id!==id||doc.version!==v)throw new Error("history identity");if(current()){setHistory(doc);note("历史只读，当前草稿未替换。");}}catch{if(current())note("历史读取失败；当前草稿保留。",true);}}
  async function beginPick(next:Target){if(saving.current)return;const session=++pickerSession.current;sourceRequest.current++;setDocumentBusy(false);setSearchBusy(false);setTarget(next);setPicked(null);setPickedDoc(null);setMaterialNote("");setSourceRead(null);const request=epoch.current;try{const result=await coreCommand<SourcesListDto>("sources_list");if(request===epoch.current&&session===pickerSession.current&&mounted.current){if(!Array.isArray(result.sources))throw new Error("sources shape");setSources(result.sources);}}catch{note("来源列表读取失败；引用选择未伪造来源。",true);}}
  async function pickDocument(id:string){const request=epoch.current,cur=active.current,session=pickerSession.current,serial=++referenceRequest.current;setPicked(null);setPickedDoc(null);setDocumentBusy(true);try{const doc=await coreCommand<DocumentDto>("document_get",{document_id:id});if(doc.document_id!==id||!Number.isSafeInteger(doc.version)||doc.version<1)throw new Error("reference identity");if(request===epoch.current&&session===pickerSession.current&&serial===referenceRequest.current&&active.current===cur&&mounted.current){setPickedDoc(doc);setPicked({kind:"document",document_id:id,version:doc.version,block_id:null});}}catch{if(session===pickerSession.current&&serial===referenceRequest.current)note("材料文档读取失败；未猜测引用版本。",true);}finally{if(mounted.current&&session===pickerSession.current&&serial===referenceRequest.current)setDocumentBusy(false);}}
  async function searchKnowledge(){const request=epoch.current,session=pickerSession.current,serial=++searchRequest.current;setSearchBusy(true);try{const result=await coreCommand<SearchDto>("search",{q:query,active_only:false});if(!Array.isArray(result.items))throw new Error("search shape");if(request===epoch.current&&session===pickerSession.current&&serial===searchRequest.current&&mounted.current)setKnowledgeRows(result.items);}catch{if(session===pickerSession.current&&serial===searchRequest.current)note("本地检索失败；未显示虚构结果或空结果。",true);}finally{if(mounted.current&&session===pickerSession.current&&serial===searchRequest.current)setSearchBusy(false);}}
  function cancelPick(){pickerSession.current++;referenceRequest.current++;searchRequest.current++;setTarget(null);setPicked(null);setPickedDoc(null);setMaterialNote("");setDocumentBusy(false);setSearchBusy(false);}
  function addPicked(){if(!target||!picked||pickerBusy)return;const next=structuredClone(b.value);if(target.kind==="material")next.materials.push({id:crypto.randomUUID(),note:materialNote,reference:picked});else if(target.kind==="conclusion"){const item=next.conclusions.find(v=>v.id===target.id);if(item)item[target.field].push(picked);}else{const item=next[target.kind].find(v=>v.id===target.id);if(item)item.references.push(picked);}if(!parseResearch(next)){note("研究条目或引用超过Core合同限制；临时选择保留。",true);return;}edit(next);cancelPick();}
  function keepUnboundMaterial(){if(!target||target.kind!=="material")return;const next=structuredClone(b.value);next.unresolved.push({id:crypto.randomUUID(),text:materialNote,references:[]});if(!parseResearch(next)){note("待整理材料说明超过限制，原输入保留。",true);return;}edit(next);cancelPick();note("说明已保留为未决草稿；未伪造材料来源。");}
  async function readSource(ref:Extract<ResearchReference,{kind:"source"}>){const request=epoch.current,serial=++sourceRequest.current;setSourceRead(null);try{const original=await coreCommand<OriginalDto>("source_original",{source_id:ref.source_id});if(original.source_id!==ref.source_id||original.sha256!==ref.sha256)throw new Error("CAS identity");const raw=Uint8Array.from(atob(original.content_base64),c=>c.charCodeAt(0));const hash=Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",raw))).map(n=>n.toString(16).padStart(2,"0")).join("");if(hash!==ref.sha256)throw new Error("CAS bytes");if(request===epoch.current&&serial===sourceRequest.current&&mounted.current)setSourceRead({ref,name:original.name,sha256:hash,length:raw.length,...(original.media_type.startsWith("text/")?{text:new TextDecoder().decode(raw)}:{})});}catch{if(request===epoch.current&&serial===sourceRequest.current)note("原件读取或SHA核对失败，未伪造内容。",true);}}
  async function exportSaved(){if(!b.base||saving.current)return;const base=b.base;saving.current=true;setBusy(true);publish();try{const result=await coreCommand<DocumentExportDto>("document_export",{document_id:base.document_id,format:"markdown"});if(result.document_id!==base.document_id||result.version!==base.version)throw new Error("export version");const artifact={schema:"archeaxis.authored-research-snapshot/v1",document:base,projection:result,role:"authored_not_verified"};const url=URL.createObjectURL(new Blob([JSON.stringify(artifact,null,2)],{type:"application/json"}));const a=document.createElement("a");a.href=url;a.download=`research-${base.document_id}-v${base.version}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),0);note("已导出Core保存版本与引用；未保存草稿不在此快照，未打包原件或传给外部检索。");}catch{note("导出失败或版本已变化；没有报告导出成功。",true);}finally{saving.current=false;if(mounted.current){setBusy(false);publish();}}}
  function navigateRef(ref:ResearchReference){if(pending.current){note("先完成或取消引用选择，当前输入保留。",true);return;}if(onOpenReference){onOpenReference(structuredClone(ref));return;}if(ref.kind==="source"){void readSource(ref);return;}if(b.dirty||b.attempt){note("当前研究未保存；请先保存或保留草稿再打开引用。",true);return;}if(ref.kind==="document")onOpenDocument?.(ref.document_id,ref.version,ref.block_id??undefined);}
  function showRefs(refs:ResearchReference[],remove?:(index:number)=>void){return <ul>{refs.map((ref,i)=><li key={`${refName(ref)}-${i}`}><span>{refName(ref)}</span>{ref.kind!=="knowledge"||onOpenReference?<button type="button" onClick={()=>navigateRef(ref)}>{ref.kind==="source"?"读取校验原件":ref.kind==="knowledge"?"打开不变知识版本":"打开固定版本"}</button>:<span>作者引用；不表示知识已接受或AI资格</span>}{remove?<button type="button" onClick={()=>remove(i)} aria-label={`删除引用 ${i+1}`}>删除引用</button>:null}</li>)}</ul>;}
  const readonly=!!history||!!unsupported;const shown=history??unsupported;const shownValue=shown?decode(shown):null;
  return <Section title="研究空间"><div style={{minWidth:0,maxWidth:"100%"}} data-section="research">
    <p>作者研究记录：问题、假设、方法、实验、反证与结论可非线性编辑。保存不代表核验、专业采用或 AI 资格；学术检索与 GraphRAG 当前未接通。</p>
    <div><button type="button" disabled={busy} onClick={()=>requestOpen("__new")}>新建研究草稿</button><button type="button" disabled={loading} onClick={()=>void list(false)}>刷新文档列表</button></div>
    <ul aria-label="研究文档列表">{rows.map(row=><li key={row.document_id}><button type="button" onClick={()=>requestOpen(row.document_id)}>{row.title} · 版本 {row.version}</button></li>)}</ul>{cursor?<button type="button" disabled={loading} onClick={()=>void list(true)}>更多文档</button>:null}
    <p role={error?"alert":"status"}>{message}</p>
    {shown?<aside aria-label="只读文档"><h3>{shown.title} · 版本 {shown.version} · 只读</h3>{shownValue?<><p style={{whiteSpace:"pre-wrap"}}>问题：{shownValue.question}</p><h4>材料</h4>{shownValue.materials.map(m=><article key={m.id}><p style={{whiteSpace:"pre-wrap"}}>{m.note}</p>{showRefs([m.reference])}</article>)}{sections.map(([key,label])=><section key={key} aria-label={`历史${label}`}><h4>{label}</h4>{shownValue[key].map(e=><article key={e.id}><p style={{whiteSpace:"pre-wrap"}}>{e.text}</p>{showRefs(e.references)}</article>)}</section>)}<h4>结论（作者记录）</h4>{shownValue.conclusions.map(c=><div key={c.id}><p style={{whiteSpace:"pre-wrap"}}>{c.text}</p><h4>来源</h4>{showRefs(c.sources)}<h4>依据</h4>{showRefs(c.basis)}</div>)}</>:<p>不支持的metadata保持完整原文，只读不转换。</p>}<RawReceiptButton label="完整原文与未知载荷" payload={shown.editor_json}/><button type="button" onClick={()=>{historyGeneration.current++;setHistory(null);setUnsupported(null);}}>返回当前研究草稿</button></aside>:null}
    <fieldset disabled={readonly} style={{minWidth:0}}><legend>{b.base?`${b.base.title} · 当前基准版本 ${b.base.version}`:"尚未持久化研究草稿"}</legend>{!b.base?<label>研究标题<input aria-label="研究标题" value={b.title} disabled={busy||!!b.attempt} onChange={event=>{b.title=event.target.value;b.serial++;b.dirty=true;publish();}}/></label>:null}
    <label>研究问题<textarea aria-label="研究问题" value={b.value.question} style={{width:"100%",boxSizing:"border-box"}} onChange={event=>changeText(()=>({...b.value,question:event.target.value}),event.target.value)}/></label>
    <h3>材料与原文</h3><button type="button" onClick={()=>void beginPick({kind:"material"})}>添加材料或待整理说明</button><ul>{b.value.materials.map((m,i)=><li key={m.id}><label>材料说明 {i+1}<textarea aria-label={`材料说明 ${i+1}`} value={m.note} onChange={e=>changeText(()=>({...b.value,materials:b.value.materials.map(v=>v.id===m.id?{...v,note:e.target.value}:v)}),e.target.value)}/></label>{showRefs([m.reference])}<button type="button" onClick={()=>edit({...b.value,materials:b.value.materials.filter(v=>v.id!==m.id)})}>删除材料 {i+1}</button></li>)}</ul>
    {sections.map(([key,label])=><section key={key} aria-label={label}><h3>{label}</h3><button type="button" onClick={()=>addEntry(key)}>添加{label}</button>{b.value[key].map((entry,i)=><article key={entry.id}><label>{label} {i+1}<textarea aria-label={`${label} ${i+1}`} value={entry.text} style={{width:"100%",boxSizing:"border-box"}} onChange={e=>changeText(()=>({...b.value,[key]:b.value[key].map(v=>v.id===entry.id?{...v,text:e.target.value}:v)}),e.target.value)}/></label>{showRefs(entry.references,index=>edit({...b.value,[key]:b.value[key].map(v=>v.id===entry.id?{...v,references:v.references.filter((_,i)=>i!==index)}:v)}))}<button type="button" onClick={()=>void beginPick({kind:key,id:entry.id})}>为{label} {i+1}添加引用</button><button type="button" onClick={()=>edit({...b.value,[key]:b.value[key].filter(v=>v.id!==entry.id)})}>删除{label} {i+1}</button></article>)}</section>)}
    <section aria-label="结论"><h3>结论 · 作者记录</h3><button type="button" onClick={()=>edit({...b.value,conclusions:[...b.value.conclusions,{id:crypto.randomUUID(),text:"",sources:[],basis:[]}]})}>添加结论</button>{b.value.conclusions.map((c,i)=><article key={c.id}><label>结论 {i+1}<textarea aria-label={`结论 ${i+1}`} value={c.text} style={{width:"100%",boxSizing:"border-box"}} onChange={e=>changeText(()=>({...b.value,conclusions:b.value.conclusions.map(v=>v.id===c.id?{...v,text:e.target.value}:v)}),e.target.value)}/></label>{(["sources","basis"] as const).map(field=><section key={field} aria-label={`结论 ${i+1}${field==="sources"?"来源":"依据"}`}><h4>{field==="sources"?"来源／原文":"依据／论证引用"}</h4>{showRefs(c[field],index=>edit({...b.value,conclusions:b.value.conclusions.map(v=>v.id===c.id?{...v,[field]:v[field].filter((_,i)=>i!==index)}:v)}))}<button type="button" onClick={()=>void beginPick({kind:"conclusion",id:c.id,field})}>为结论 {i+1}添加{field==="sources"?"来源":"依据"}</button></section>)}<button type="button" onClick={()=>edit({...b.value,conclusions:b.value.conclusions.filter(v=>v.id!==c.id)})}>删除结论 {i+1}</button></article>)}</section>
    </fieldset>
    <button type="button" disabled={busy||readonly} onClick={()=>void save()}>{b.attempt?"重试冻结研究保存":"保存研究草稿"}</button>{b.base?<><button type="button" disabled={busy} onClick={()=>void exportSaved()}>导出已存研究快照</button><button type="button" disabled={busy} onClick={()=>void reconcile()}>核对最新保存版本</button><label>历史版本<input aria-label="研究历史版本" value={historyVersion} onChange={e=>setHistoryVersion(e.target.value)}/></label><button type="button" onClick={()=>void readHistory()}>读取研究历史</button></>:null}
    {sourceRead?<section aria-label="已实际读取并SHA校验的原件"><h3>已实际读取并SHA校验的原件</h3><p>{sourceRead.name} · {sourceRead.length} 字节 · {sourceRead.sha256}</p>{sourceRead.text?<p style={{whiteSpace:"pre-wrap"}}>{sourceRead.text}</p>:<p>保留二进制原件，当前不执行或伪造正文。</p>}</section>:null}
    <AaosDialog title="选择研究引用" description="只使用本地已有对象和固定版本；取消不改变研究草稿。" open={target!==null} onOpenChange={open=>{if(!open)cancelPick();}} trigger={<button disabled={!target}>审阅引用选择</button>}>
      {target?.kind==="material"?<label>待整理材料说明<textarea aria-label="待整理材料说明" value={materialNote} onChange={e=>setMaterialNote(e.target.value)}/></label>:null}
      <label>真实文档<select aria-label="引用文档" value={picked?.kind==="document"?picked.document_id:""} onChange={e=>{if(e.target.value)void pickDocument(e.target.value);}}><option value="">选择实际文档</option>{rows.map(row=><option key={row.document_id} value={row.document_id}>{row.title} · {row.document_id}</option>)}</select></label>
      {pickedDoc?<label>固定版本中的块<select aria-label="引用块" value={picked?.kind==="document"?picked.block_id??"":""} onChange={e=>setPicked({kind:"document",document_id:pickedDoc.document_id,version:pickedDoc.version,block_id:e.target.value||null})}><option value="">整个固定版本</option>{pickedDoc.blocks.map(block=><option key={block.block_id} value={block.block_id}>{block.block_id} · {block.text_projection}</option>)}</select></label>:null}
      <label>原件来源<select aria-label="引用原件" value={picked?.kind==="source"?picked.source_id:""} onChange={e=>{const src=sources.find(v=>v.source_id===e.target.value);if(src){referenceRequest.current++;setDocumentBusy(false);setPickedDoc(null);setPicked({kind:"source",source_id:src.source_id,sha256:src.sha256});}}}><option value="">选择实际来源</option>{sources.map(src=><option key={src.source_id} value={src.source_id}>{src.original_name} · {src.source_id}</option>)}</select></label>
      <label>本地知识检索<input aria-label="研究本地知识检索" value={query} onChange={e=>setQuery(e.target.value)}/></label><button type="button" disabled={pickerBusy} onClick={()=>void searchKnowledge()}>检索本地知识</button><ul>{knowledgeRows.map(item=><li key={item.knowledge_id}><button type="button" onClick={()=>{referenceRequest.current++;setDocumentBusy(false);setPickedDoc(null);setPicked({kind:"knowledge",knowledge_id:item.knowledge_id});}}>{item.head} · {item.knowledge_id}</button></li>)}</ul>
      {picked?<p>将绑定 {refName(picked)}</p>:<p>未选择真实引用；不填充虚构来源。</p>}<button type="button" disabled={!picked||pickerBusy} onClick={addPicked}>添加所选引用</button>{target?.kind==="material"?<button type="button" disabled={pickerBusy} onClick={keepUnboundMaterial}>无来源说明先保留为未决草稿</button>:null}<button type="button" onClick={cancelPick}>取消引用选择</button>
    </AaosDialog>
    <AaosDialog title="保留研究草稿并切换" description="取消保留当前输入；确认切换仍在本页保存对象草稿缓冲，不报告已存Core。" open={switchTo!==null} onOpenChange={open=>{if(!open)setSwitchTo(null);}} trigger={<button disabled={!switchTo}>审阅研究对象切换</button>}><button type="button" onClick={()=>setSwitchTo(null)}>取消切换</button><button type="button" onClick={()=>{const next=switchTo;setSwitchTo(null);if(next)void open(next);}}>保留草稿并切换</button></AaosDialog>
  </div></Section>;
}
