import { useEffect, useId, useRef, useState } from "react";
import { coreCommand } from "../api/core";
import { ApiError } from "../api/client";
import { assertCoreDto, type DocumentDto, type MachineDocumentsPageDto, type MachineDocumentSummaryDto, type MachineRubricDto } from "../api/generated/core-contract";
import type { AiAsset, AssetSnapshot, AssetReview, AssetContextGrant, AssetPacketRequest, AssetPacketResponse } from "../api/generated/ai-asset-contract";
import type { ObjectReference } from "../api/generated/research-contract";
import { documentRequestIdentity } from "../presentation/documentRequestIdentity";
import { failureMessage } from "../presentation/labels";
import { RawReceiptButton } from "../components/DiagnosticConsole";
import { ObjectReferencePicker } from "../components/ObjectReferencePicker";
import { AiAssetPacketPanel } from "../components/AiAssetPacketPanel";

type Obj=Record<string,unknown>;
type Draft={value:AiAsset;envelope:Obj;base:DocumentDto|null;serial:number;dirty:boolean};
type Attempt={operation:"document_create"|"document_draft";payload:Obj;id:string;version:number;title:string;serial:number;value:AiAsset;source_id:string|null;source_revision:string|null};
const object=(v:unknown):Obj=>{if(!v||typeof v!=="object"||Array.isArray(v))throw new Error("不兼容的资产对象");return v as Obj;};
const ordered=(v:unknown):unknown=>Array.isArray(v)?v.map(ordered):v&&typeof v==="object"?Object.fromEntries(Object.entries(v).sort(([a],[b])=>a.localeCompare(b)).map(([k,x])=>[k,ordered(x)])):v;
const equal=(a:unknown,b:unknown)=>JSON.stringify(ordered(a))===JSON.stringify(ordered(b));
const snapshot=(d:DocumentDto):AssetSnapshot=>({document_id:d.document_id,version:d.version,content_sha256:d.content_sha256});
const blank=():Draft=>({value:{schema:"archeaxis.ai-asset/v1",kind:"memory",content:"",purpose:"",scope:[],provenance:[],expires_at:null,state:"candidate",members:[],conflicts:[],revises:null,review:null,source_payload:null},envelope:{type:"doc",content:[]},base:null,serial:0,dirty:false});
/** Parser supplied by the generated-contract integration. Never strip unsupported fields. */
export function CanonicalAiAssetsSpace({parseAsset,onOpenReference,parseGrant,packetCommand,onUseAsset}: {
  parseAsset:(value:unknown)=>AiAsset|null;onOpenReference?:(reference:ObjectReference)=>void;
  parseGrant:(value:unknown)=>AssetContextGrant|null;packetCommand:(request:AssetPacketRequest)=>Promise<AssetPacketResponse>;onUseAsset?:(request:AssetPacketRequest)=>void;
}) {
  const draft=useRef<Draft>(blank()),attempt=useRef<Attempt|null>(null),saving=useRef(false),mounted=useRef(true),epoch=useRef(0),listEpoch=useRef(0),historyEpoch=useRef(0),owner=useId();
  const [,redraw]=useState(0),[rows,setRows]=useState<MachineDocumentSummaryDto[]>([]),[cursor,setCursor]=useState<string|null>(null),[loaded,setLoaded]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[message,setMessage]=useState("");
  const [unsupported,setUnsupported]=useState<DocumentDto|null>(null),[history,setHistory]=useState<DocumentDto|null>(null),[historyVersion,setHistoryVersion]=useState("1");
  const [picker,setPicker]=useState<"scope"|"provenance"|"members"|"conflicts"|"revises"|"rubric"|null>(null),pickerRef=useRef<typeof picker>(null);
  const [raw,setRaw]=useState<string|null>(null),rawRef=useRef<string|null>(null),[expiry,setExpiry]=useState<string|null>(null),expiryRef=useRef<string|null>(null),[rubric,setRubric]=useState<MachineRubricDto|null>(null),[review,setReview]=useState<AssetReview|null>(null);
  const reviewPending=useRef(false);
  useEffect(()=>{reviewPending.current=review!==null;publish();},[review]);
  function publish(){if(!mounted.current)return;redraw(x=>x+1);window.dispatchEvent(new CustomEvent("archeaxis-draft-dirty",{detail:{owner,dirty:draft.current.dirty||!!attempt.current||saving.current||!!pickerRef.current||rawRef.current!==null||expiryRef.current!==null||reviewPending.current}}));}
  function selectPicker(v:typeof picker){pickerRef.current=v;setPicker(v);publish();}
  function transient(content:string|null){rawRef.current=content;setRaw(content);publish();}
  function edit(change:Partial<AiAsset>){if(saving.current||unsupported||draft.current.value.state==="withdrawn")return;historyEpoch.current++;draft.current={...draft.current,value:{...draft.current.value,...change,state:"candidate",review:null},serial:draft.current.serial+1,dirty:true};setReview(null);setRubric(null);publish();}
  const blocked=()=>{if(saving.current||draft.current.dirty||attempt.current||pickerRef.current||rawRef.current!==null||expiryRef.current!==null||reviewPending.current){setMessage("当前草稿或未确认请求保留，请先完成保存或取消临时输入。");return true;}return false;};
  function readAsset(d:DocumentDto){const asset=parseAsset(object(object(d.editor_json).attrs).archeaxis_ai_asset);if(!asset)throw new Error("资产元数据不兼容；完整原文只读");return asset;}
  async function list(next?:string){const seq=++listEpoch.current;try{const page=await coreCommand<MachineDocumentsPageDto>("ai_assets_list",next?{cursor:next}:{});if(seq===listEpoch.current&&mounted.current){setRows(old=>next?[...old,...page.items.filter(x=>!old.some(y=>x.document_id===y.document_id))]:page.items);setCursor(page.next_cursor);setLoaded(true);}}catch(e){if(seq===listEpoch.current&&mounted.current)setError(failureMessage(e));}}
  useEffect(()=>{mounted.current=true;void list();return()=>{mounted.current=false;epoch.current++;listEpoch.current++;historyEpoch.current++;window.dispatchEvent(new CustomEvent("archeaxis-draft-dirty",{detail:{owner,dirty:false}}));};},[]);
  async function open(id:string){if(blocked())return;const seq=++epoch.current,serial=draft.current.serial;setBusy(true);setError(null);try{const doc=await coreCommand<DocumentDto>("document_get",{document_id:id});if(seq!==epoch.current||!mounted.current)return;if(doc.document_id!==id)throw new Error("资产身份不符");if(serial!==draft.current.serial||draft.current.dirty){setMessage("读取期间编辑已保留。");return;}let value:AiAsset;try{value=readAsset(doc);}catch{setUnsupported(doc);return;}draft.current={value:structuredClone(value),envelope:structuredClone(object(doc.editor_json)),base:doc,serial:0,dirty:false};setUnsupported(null);setHistory(null);setReview(null);setRubric(null);publish();}catch(e){if(seq===epoch.current&&mounted.current)setError(failureMessage(e));}finally{if(seq===epoch.current&&mounted.current)setBusy(false);}}
  function verify(d:DocumentDto,f:Attempt){return d.document_id===f.id&&d.version===f.version&&d.title===f.title&&d.source_id===f.source_id&&d.source_revision===f.source_revision&&equal(d.editor_json,object(f.payload.body).editor_json)&&equal(readAsset(d),f.value);}
  async function save(state?:AiAsset["state"]){if(saving.current||unsupported)return;if(pickerRef.current||rawRef.current!==null||expiryRef.current!==null){setMessage("先提交或取消临时输入。");return;}const current=draft.current;
    if(state&&attempt.current){setMessage("先核对冻结请求，再更改状态。");return;}
    if(state==="adopted"&&(!current.base||current.dirty||!review||review.outcome!=="passed"||!equal(review.asset,snapshot(current.base)))){setMessage("先保存候选，再完成对应版本的人工逐项评审。");return;}
    saving.current=true;setBusy(true);setError(null);publish();let ack=false;
    try{if(!attempt.current){const value=structuredClone({...current.value,...(state?{state,review:state==="adopted"?review:current.value.review}:{})});const editor={...current.envelope,attrs:{...(current.envelope.attrs?object(current.envelope.attrs):{}),archeaxis_ai_asset:value}},requestId=`asset_${crypto.randomUUID()}`;
      attempt.current=current.base?{operation:"document_draft",payload:{document_id:current.base.document_id,body:{expected_version:current.base.version,editor_json:editor}},id:current.base.document_id,version:current.base.version+1,title:current.base.title,serial:current.serial,value,source_id:current.base.source_id,source_revision:current.base.source_revision}:{operation:"document_create",payload:{body:{create_request_id:requestId,title:value.purpose.trim()||"AI 资产候选",editor_json:editor}},id:await documentRequestIdentity(requestId),version:1,title:value.purpose.trim()||"AI 资产候选",serial:current.serial,value,source_id:null,source_revision:null};}
      const f=attempt.current,written=await coreCommand<DocumentDto>(f.operation,structuredClone(f.payload));ack=true;const read=await coreCommand<DocumentDto>("document_get",{document_id:f.id});if(!verify(written,f)||!verify(read,f)||written.content_sha256!==read.content_sha256)throw new Error("资产保存回读不一致");current.base=read;current.envelope=structuredClone(object(read.editor_json));if(current.serial===f.serial)current.value=structuredClone(f.value);current.dirty=current.serial!==f.serial;attempt.current=null;setReview(null);setRubric(null);setMessage(current.dirty?"发送版本已确认；后续草稿仍保留。":"资产版本已保存并读回；保存及采用均不授予 AI 资格。");void list();
    }catch(e){if(!ack&&e instanceof ApiError&&[400,403,422].includes(e.status))attempt.current=null;setError(failureMessage(e));setMessage("UNKNOWN：草稿与冻结请求保留，不自动重试。");}finally{saving.current=false;if(mounted.current){setBusy(false);publish();}}}
  async function reconcile(){const f=attempt.current;if(!f||saving.current)return;saving.current=true;publish();try{const read=await coreCommand<DocumentDto>("document_get",{document_id:f.id});if(!verify(read,f))throw new Error("冻结请求与 Core 版本不同；当前草稿未改变");const current=draft.current;current.base=read;current.envelope=structuredClone(object(read.editor_json));if(current.serial===f.serial)current.value=structuredClone(f.value);current.dirty=current.serial!==f.serial;attempt.current=null;setMessage("冻结请求已确认；后续草稿保留。");void list();}catch(e){setError(failureMessage(e));}finally{saving.current=false;publish();}}
  async function readHistory(){if(!draft.current.base||saving.current||pickerRef.current||rawRef.current!==null||expiryRef.current!==null)return;const base=draft.current.base,version=Number(historyVersion),generation=++historyEpoch.current,seq=epoch.current,serial=draft.current.serial;if(!Number.isSafeInteger(version)||version<1||version>base.version){setError("请输入已有版本。");return;}try{const doc=await coreCommand<DocumentDto>("document_version",{document_id:base.document_id,version});if(doc.document_id!==base.document_id||doc.version!==version)throw new Error("历史身份不符");if(mounted.current&&generation===historyEpoch.current&&seq===epoch.current&&serial===draft.current.serial)setHistory(doc);}catch(e){if(mounted.current&&generation===historyEpoch.current)setError(failureMessage(e));}}
  function reference(ref:ObjectReference){const target=pickerRef.current;if(target!=="scope"&&target!=="provenance")return;edit({[target]:[...draft.current.value[target],ref]});selectPicker(null);}
  function picked(s:AssetSnapshot,doc:DocumentDto){const target=pickerRef.current;if(target==="rubric"){if(!draft.current.base||draft.current.dirty)return;try{const value=assertCoreDto<MachineRubricDto>("MachineRubricDto",object(object(doc.editor_json).attrs).archeaxis_machine_rubric);setRubric(value);setReview({asset:snapshot(draft.current.base),rubric:s,reviewer:"",basis:"",judgments:value.criteria.map(c=>({criterion_id:c.criterion_id,outcome:"unmeasured",basis:""})),outcome:"unmeasured"});}catch(e){setError(failureMessage(e));}}else if(target==="members"||target==="conflicts")edit({[target]:[...draft.current.value[target],s]});else if(target==="revises")edit({revises:s});selectPicker(null);}
  const current=draft.current,v=current.value,readonly=busy||v.state==="withdrawn"||!!unsupported;
  return <section aria-label="AI 基础资产" className="ui-content-main-side"><div><h2>AI 基础资产</h2><p>记忆、知识包、规则、技能与经验保存为惰性内容。候选可不完整，不执行规则或技能，不接入私人会话。</p><button disabled={busy} onClick={()=>void list()}>刷新资产</button><button disabled={busy} onClick={()=>{if(!blocked()){epoch.current++;historyEpoch.current++;draft.current=blank();setUnsupported(null);setHistory(null);setReview(null);setRubric(null);publish();}}}>新建资产候选</button>{loaded&&!rows.length&&!error?<p>尚无资产。</p>:null}<ul>{rows.map(r=><li key={r.document_id}><button onClick={()=>void open(r.document_id)}>{r.title} · v{r.version}</button></li>)}</ul>{cursor?<button onClick={()=>void list(cursor)}>更多资产</button>:null}</div>
  <div className="semantic-panel">{unsupported?<><h3>不兼容资产只读</h3><RawReceiptButton label="完整资产原文" payload={unsupported}/><button onClick={()=>setUnsupported(null)}>返回保留草稿</button></>:<><h3>{current.base?`资产版本 ${current.base.version}`:"资产候选草稿"}</h3><p>状态：{v.state}；{current.dirty?"未保存":"已读回或空白草稿"}</p>
  <label>资产类型<select disabled={readonly} value={v.kind} onChange={e=>edit({kind:e.target.value as AiAsset["kind"],members:[]})}><option value="memory">记忆</option><option value="knowledge_package">知识包</option><option value="rule">规则</option><option value="skill">技能</option><option value="experience">经验</option></select></label>
  {typeof v.content==="string"&&raw===null?<label>资产内容<textarea disabled={readonly} value={v.content} onChange={e=>edit({content:e.target.value})}/></label>:null}<button disabled={readonly||raw!==null} onClick={()=>transient(JSON.stringify(v.content,null,2))}>编辑惰性 JSON 内容</button>{raw!==null?<><label>JSON 内容草稿<textarea value={raw} onChange={e=>transient(e.target.value)}/></label><button onClick={()=>{try{edit({content:JSON.parse(raw)});transient(null);}catch{setError("JSON 不完整，原资产未改变。");}}}>提交 JSON 内容</button><button onClick={()=>transient(null)}>取消 JSON 编辑</button></>:null}
  <label>资产用途<textarea disabled={readonly} value={v.purpose} onChange={e=>edit({purpose:e.target.value})}/></label><label>到期 Unix 秒（空白为无期限）<input disabled={readonly} value={expiry??(v.expires_at===null?"":String(v.expires_at))} onChange={e=>{expiryRef.current=e.target.value;setExpiry(e.target.value);publish();}}/></label>{expiry!==null?<><button onClick={()=>{const n=expiry===""?null:Number(expiry);if(n!==null&&(!Number.isSafeInteger(n)||n<0)){setError("时效必须为非负整数秒。");return;}edit({expires_at:n});expiryRef.current=null;setExpiry(null);publish();}}>提交时效</button><button onClick={()=>{expiryRef.current=null;setExpiry(null);publish();}}>取消时效编辑</button></>:null}
  {(["provenance","scope"] as const).map(key=><fieldset key={key}><legend>{key==="provenance"?"实际来源":"适用范围"}</legend><button disabled={readonly} onClick={()=>selectPicker(key)}>添加{key==="provenance"?"来源":"范围"}</button>{v[key].map((r,i)=><div key={i}><button onClick={()=>onOpenReference?.(r)}>查看固定引用 {i+1}</button><button disabled={readonly} onClick={()=>edit({[key]:v[key].filter((_,j)=>j!==i)})}>移除{key} {i+1}</button></div>)}</fieldset>)}
  {(["members","conflicts"] as const).map(key=><fieldset key={key}><legend>{key==="members"?"知识包成员版本":"冲突版本"}</legend><button disabled={readonly||(key==="members"&&v.kind!=="knowledge_package")} onClick={()=>selectPicker(key)}>添加{key==="members"?"成员":"冲突"}版本</button>{v[key].map((s,i)=><div key={i}><button onClick={()=>onOpenReference?.({kind:"document",document_id:s.document_id,version:s.version,block_id:null})}>{s.document_id} · v{s.version}</button><button disabled={readonly} onClick={()=>edit({[key]:v[key].filter((_,j)=>j!==i)})}>移除{key} {i+1}</button></div>)}</fieldset>)}
  <button disabled={readonly} onClick={()=>selectPicker("revises")}>选择修订原版本</button>{v.revises?<><button onClick={()=>onOpenReference?.({kind:"document",document_id:v.revises!.document_id,version:v.revises!.version,block_id:null})}>查看被修订版本 {v.revises.version}</button><button disabled={readonly} onClick={()=>edit({revises:null})}>取消修订关联</button></>:null}
  {picker?<><ObjectReferencePicker disabled={busy} onPick={picker==="scope"||picker==="provenance"?reference:undefined} onSnapshot={picker!=="scope"&&picker!=="provenance"?picked:undefined} onOpenReference={onOpenReference}/><button onClick={()=>selectPicker(null)}>取消对象选择</button></>:null}
  <button disabled={readonly||v.state!=="candidate"||current.dirty||!current.base||!!attempt.current} onClick={()=>selectPicker("rubric")}>选择实际评审 rubric</button>{review&&rubric?<fieldset disabled={readonly||current.dirty}><legend>人工评审当前候选版本</legend><p>{rubric.title} · v{review.rubric.version}；评审仅用于该资产采用。</p><label>评审人<input value={review.reviewer} onChange={e=>setReview({...review,outcome:"unmeasured",reviewer:e.target.value})}/></label><label>评审依据<textarea value={review.basis} onChange={e=>setReview({...review,outcome:"unmeasured",basis:e.target.value})}/></label>{rubric.criteria.map((c,i)=><div key={c.criterion_id}><p>{c.label}：{c.expectation}</p><label>判定 {c.label}<select value={review.judgments[i].outcome} onChange={e=>setReview({...review,outcome:"unmeasured",judgments:review.judgments.map((j,n)=>n===i?{...j,outcome:e.target.value as typeof j.outcome}:j)})}><option value="unmeasured">未测量</option><option value="passed">通过</option><option value="failed">未通过</option></select></label><label>依据 {c.label}<textarea value={review.judgments[i].basis} onChange={e=>setReview({...review,outcome:"unmeasured",judgments:review.judgments.map((j,n)=>n===i?{...j,basis:e.target.value}:j)})}/></label></div>)}<button disabled={!review.reviewer.trim()||!review.basis.trim()||review.judgments.some(j=>j.outcome!=="passed"||!j.basis.trim())} onClick={()=>setReview({...review,outcome:"passed"})}>确认全部人工评审通过</button><button onClick={()=>{setReview(null);setRubric(null);}}>取消未提交评审</button></fieldset>:null}
  {v.review?<RawReceiptButton label="已保存资产评审" payload={v.review}/>:null}<button disabled={readonly||!!attempt.current} onClick={()=>void save()}>保存资产候选</button><button disabled={readonly||!!attempt.current||current.dirty||review?.outcome!=="passed"} onClick={()=>void save("adopted")}>明确采用此评审版本</button><button disabled={readonly||!!attempt.current||!current.base||current.dirty} onClick={()=>void save("withdrawn")}>撤回资产</button>{attempt.current?<><button disabled={busy} onClick={()=>void save()}>重试冻结资产请求</button><button disabled={busy} onClick={()=>void reconcile()}>核对冻结资产请求</button></>:null}
  <label>历史版本<input value={historyVersion} onChange={e=>{historyEpoch.current++;setHistoryVersion(e.target.value);}}/></label><button disabled={!current.base||busy} onClick={()=>void readHistory()}>读取资产历史</button>{history?<><p>历史 v{history.version} 只读，当前草稿未替换。</p><RawReceiptButton label="完整资产历史" payload={history}/></>:null}{v.source_payload!==null?<RawReceiptButton label="保全来源载荷" payload={v.source_payload}/>:null}</>}<AiAssetPacketPanel asset={current.dirty||attempt.current?null:current.base} parseAsset={parseAsset} parseGrant={parseGrant} packetCommand={packetCommand} onUse={onUseAsset}/>{message?<p role="status">{message}</p>:null}{error?<p role="alert">{error}</p>:null}</div></section>;
}
