"""Reasoning memory — absorbed from ReasoningBank (google-research) patterns.

An agent (and a human) learns from BOTH successful and failed trajectories.
This module stores trajectories, distills them into reusable principles, and
retrieves the right principle for the next task:

    save_trajectory  →  reflect (extract principle)  →  retrieve_principles
                                                     →  record_application

Principles are generated by a deterministic local extractor first (always
available); an optional LLM reflector (LiteLLM) can enrich the statement,
but local extraction never depends on it.

Governance:
    * failure patterns become "avoid …" principles; success patterns become "do …"
    * a principle is only a candidate until it accumulates applications
"""

from __future__ import annotations

import json
import re
import sqlite3
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Literal

_SCHEMA = """
CREATE TABLE IF NOT EXISTS trajectories (
    trajectory_id TEXT PRIMARY KEY,
    goal TEXT NOT NULL,
    steps_json TEXT NOT NULL,
    outcome TEXT NOT NULL,             -- success | failure
    error_pattern TEXT,
    importance REAL NOT NULL DEFAULT 0.5,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS reasoning_principles (
    principle_id TEXT PRIMARY KEY,
    statement TEXT NOT NULL,
    category TEXT NOT NULL,            -- success_pattern | failure_pattern | strategy
    source_trajectory_ids_json TEXT NOT NULL,
    confidence REAL NOT NULL DEFAULT 0.5,
    usage_count INTEGER NOT NULL DEFAULT 0,
    last_applied TEXT,
    status TEXT NOT NULL DEFAULT 'candidate',  -- candidate | established
    created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_rp_category ON reasoning_principles(category);
"""


class ReasoningMemoryError(ValueError):
    """Raised when a reasoning-memory operation is invalid."""


@dataclass(frozen=True)
class Trajectory:
    trajectory_id: str
    goal: str
    steps: list[str]
    outcome: Literal["success", "failure"]
    error_pattern: str | None
    importance: float
    created_at: str


@dataclass(frozen=True)
class ReasoningPrinciple:
    principle_id: str
    statement: str
    category: Literal["success_pattern", "failure_pattern", "strategy"]
    source_trajectory_ids: list[str]
    confidence: float
    usage_count: int
    status: str
    created_at: str


def _connect(db: str | Path) -> sqlite3.Connection:
    conn = sqlite3.connect(Path(db))
    conn.row_factory = sqlite3.Row
    conn.executescript(_SCHEMA)
    return conn


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _stable_id(prefix: str, *parts: str) -> str:
    from hashlib import sha256

    payload = "\0".join(parts).encode("utf-8")
    return f"{prefix}_{sha256(payload).hexdigest()[:24]}"


# ── trajectories ────────────────────────────────────────────────────

def save_trajectory(
    db: str | Path,
    *,
    goal: str,
    steps: list[str],
    outcome: Literal["success", "failure"],
    error_pattern: str | None = None,
    importance: float = 0.5,
    trajectory_id: str | None = None,
) -> Trajectory:
    """Store one executed trajectory (append-only)."""
    if not goal.strip() or not steps:
        raise ReasoningMemoryError("goal and steps are required")
    if outcome not in {"success", "failure"}:
        raise ReasoningMemoryError(f"invalid outcome: {outcome}")
    if outcome == "failure" and not error_pattern:
        raise ReasoningMemoryError("failure trajectories require an error_pattern")
    if not 0.0 <= importance <= 1.0:
        raise ReasoningMemoryError("importance must be in [0,1]")
    tid = trajectory_id or _stable_id("traj", goal, _now())
    created_at = _now()
    with _connect(db) as conn:
        conn.execute(
            "INSERT INTO trajectories (trajectory_id, goal, steps_json, outcome, error_pattern, importance, created_at) "
            "VALUES (?, ?, ?, ?, ?, ?, ?)",
            (tid, goal.strip(), json.dumps(steps, ensure_ascii=False), outcome,
             error_pattern, importance, created_at),
        )
    return Trajectory(trajectory_id=tid, goal=goal.strip(), steps=list(steps),
                      outcome=outcome, error_pattern=error_pattern,
                      importance=importance, created_at=created_at)


# ── local reflection (deterministic) ────────────────────────────────

_STRATEGY_MARKERS = re.compile(
    r"(verify|validate|check|test|review|compare|first|before|after|always|never|"
    r"必须|先|后|验证|检查|测试|对比|总是|绝不|优先)", re.IGNORECASE
)


def _local_reflection(trajectory: Trajectory) -> ReasoningPrinciple:
    """Deterministic principle extraction from one trajectory."""
    if trajectory.outcome == "failure":
        statement = f"避免：{trajectory.error_pattern or '重复已知失败路径'}"
        category = "failure_pattern"
    else:
        steps_preview = "；".join(trajectory.steps[:3])
        statement = f"做法：{trajectory.goal}（步骤：{steps_preview}）"
        category = "success_pattern"
    if _STRATEGY_MARKERS.search(trajectory.goal + " ".join(trajectory.steps)):
        category = "strategy"
    return ReasoningPrinciple(
        principle_id=_stable_id("principle", trajectory.trajectory_id, statement),
        statement=statement, category=category,  # type: ignore[arg-type]
        source_trajectory_ids=[trajectory.trajectory_id],
        confidence=0.4 + 0.2 * trajectory.importance,
        usage_count=0, status="candidate", created_at=_now(),
    )


def reflect(
    db: str | Path,
    trajectory_id: str,
    *,
    llm_reflection: str | None = None,
) -> ReasoningPrinciple:
    """Distill one trajectory into a principle (local extractor + optional LLM hint)."""
    with _connect(db) as conn:
        row = conn.execute("SELECT * FROM trajectories WHERE trajectory_id=?", (trajectory_id,)).fetchone()
        if row is None:
            raise ReasoningMemoryError(f"trajectory not found: {trajectory_id}")
    trajectory = Trajectory(
        trajectory_id=row["trajectory_id"], goal=row["goal"],
        steps=json.loads(row["steps_json"]), outcome=row["outcome"],
        error_pattern=row["error_pattern"], importance=row["importance"],
        created_at=row["created_at"],
    )
    principle = _local_reflection(trajectory)
    if llm_reflection and llm_reflection.strip():
        principle = ReasoningPrinciple(
            principle_id=principle.principle_id, statement=llm_reflection.strip(),
            category=principle.category, source_trajectory_ids=principle.source_trajectory_ids,
            confidence=round(min(1.0, principle.confidence + 0.1), 3),
            usage_count=0, status="candidate", created_at=principle.created_at,
        )
    with _connect(db) as conn:
        conn.execute(
            "INSERT OR IGNORE INTO reasoning_principles "
            "(principle_id, statement, category, source_trajectory_ids_json, confidence, usage_count, last_applied, status, created_at) "
            "VALUES (?, ?, ?, ?, ?, 0, NULL, 'candidate', ?)",
            (principle.principle_id, principle.statement, principle.category,
             json.dumps(principle.source_trajectory_ids), principle.confidence,
             principle.created_at),
        )
    return principle


# ── retrieval ───────────────────────────────────────────────────────

def _terms(text: str) -> set[str]:
    words = re.findall(r"[\w\u4e00-\u9fff]+", text.lower())
    return {w for w in words if w.strip() and len(w) > 1}


def retrieve_principles(db: str | Path, query: str, *, top_k: int = 5) -> list[dict[str, Any]]:
    """Rank principles by query-term overlap, confidence and usage."""
    if top_k < 1:
        raise ReasoningMemoryError("top_k must be >= 1")
    query_terms = _terms(query)
    with _connect(db) as conn:
        rows = conn.execute("SELECT * FROM reasoning_principles").fetchall()
    scored: list[tuple[float, dict[str, Any]]] = []
    for r in rows:
        terms = _terms(r["statement"])
        # CJK has no spaces: "字体" must match the token "字体嵌入" (substring
        # both ways, since English word tokens are already space-delimited).
        hits = sum(1 for qt in query_terms
                   if any(qt in st or st in qt for st in terms))
        overlap = hits / max(len(query_terms), 1)
        score = round(0.6 * overlap + 0.25 * r["confidence"] + 0.15 * min(r["usage_count"] / 5.0, 1.0), 3)
        scored.append((score, {
            "principle_id": r["principle_id"], "statement": r["statement"],
            "category": r["category"], "confidence": r["confidence"],
            "usage_count": r["usage_count"], "status": r["status"], "score": score,
        }))
    scored.sort(key=lambda item: item[0], reverse=True)
    return [item[1] for item in scored[:top_k]]


def record_application(db: str | Path, principle_id: str, *, outcome: Literal["success", "failure"]) -> float:
    """Bump usage; confidence rises with success, falls with failure."""
    with _connect(db) as conn:
        row = conn.execute("SELECT * FROM reasoning_principles WHERE principle_id=?", (principle_id,)).fetchone()
        if row is None:
            raise ReasoningMemoryError(f"principle not found: {principle_id}")
        usage = row["usage_count"] + 1
        confidence = row["confidence"]
        if outcome == "success":
            confidence = round(min(1.0, confidence + 0.05), 3)
        else:
            confidence = round(max(0.1, confidence - 0.05), 3)
        status = "established" if usage >= 3 and confidence >= 0.6 else "candidate"
        conn.execute(
            "UPDATE reasoning_principles SET usage_count=?, confidence=?, last_applied=?, status=? "
            "WHERE principle_id=?",
            (usage, confidence, _now(), status, principle_id),
        )
        return confidence
