"""Repository naming and text-encoding convention checks."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import subprocess
import sys
import unicodedata
from collections import defaultdict
from dataclasses import asdict, dataclass
from pathlib import Path, PurePosixPath

import yaml

_REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
if str(_REPOSITORY_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPOSITORY_ROOT))

from shared.naming import NamingRegistry, NamingRegistryError  # noqa: E402

_BINARY_SUFFIXES = {
    ".7z",
    ".avi",
    ".db",
    ".dll",
    ".doc",
    ".docx",
    ".exe",
    ".gif",
    ".gz",
    ".ico",
    ".jpeg",
    ".jpg",
    ".mkv",
    ".mov",
    ".mp3",
    ".mp4",
    ".pdf",
    ".png",
    ".ppt",
    ".pptx",
    ".pyc",
    ".sqlite",
    ".tar",
    ".wav",
    ".webm",
    ".webp",
    ".xls",
    ".xlsx",
    ".zip",
}
_RESERVED_WINDOWS_NAMES = {
    "aux",
    "con",
    "nul",
    "prn",
    *(f"com{number}" for number in range(1, 10)),
    *(f"lpt{number}" for number in range(1, 10)),
}
_ZERO_WIDTH = {"\u200b", "\u200c", "\u200d", "\u2060"}
_WINDOWS_EOL_SUFFIXES = {".bat", ".cmd", ".ps1"}
# Pinned Tauri generator uses JSON serialization without a terminal LF. Only
# these exact current generated bytes may omit it; encoding/whitespace checks
# still apply, and different generated content must be reviewed again.
_GENERATED_NO_FINAL_LF = {
    "src-tauri/gen/schemas/acl-manifests.json": "b8665c2471bd4c59d570c77e226f37410ce396da52525383a15b5cbbff9d786e",
    "src-tauri/gen/schemas/capabilities.json": "44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a",
    "src-tauri/gen/schemas/desktop-schema.json": "f68a9c570ecff07ac6826145d33b966d6fc02f7d680967f44437268b08a6ba78",
    "src-tauri/gen/schemas/windows-schema.json": "f68a9c570ecff07ac6826145d33b966d6fc02f7d680967f44437268b08a6ba78",
}
# Original R3.1 bytes at c06b234, R5 bytes verified against the source ZIP, and the pinned
# recovery exports: preserve history instead of editing manifest-bound files to satisfy a
# later formatting convention. A06's hash is registered outside this repository, so those
# bytes may not be rewritten here at all. No directory exemption: only these exact pinned
# bytes may omit their final newline or carry a markdown hard break, and any other byte of a
# pinned file still fails as frozen-original-mismatch.
_FROZEN_ORIGINALS = {
    "docs/authority/taskpack-0910-r3/MANIFEST.json":
        "a4b91455ce3b626939118897f18eab7800b76fc644c4345d440368f0f62f6a55",
    "docs/authority/taskpack-0910-r3/TASKS.json":
        "954d02f655bdf1d5fe7b339629534bee55051a67fa26139adef5340c555dcb37",
    "docs/authority/taskpack-0912-r5/frozen-r4/research-v15/学科数据.json":
        "f675fe774dc4cb75b290edf3b82cd1cc938d97a67023bb37e415753a3ce344b1",
    "docs/authority/taskpack-0912-r5/frozen-r4/research-v15/方法数据.json":
        "084e013a6e8dca1da9db3569430d0f999bec81a81e7ea4c08fd24bfbf0d23911",
    "docs/authority/taskpack-0912-r5/frozen-r4/research-v15/研究数据.json":
        "05b28103ac82dd531c8a669d0240b59efadd06679bba609aa50b7f26642df347",
    "docs/authority/taskpack-0912-r5/frozen-r4/research-v15/资源数据.json":
        "4e95adebb9a275be790aa2b05f161a127faef27a661f4bf1dc41987031a8f9ef",
    "docs/authority/taskpack-0912-r5/research-v15/学科数据.json":
        "f675fe774dc4cb75b290edf3b82cd1cc938d97a67023bb37e415753a3ce344b1",
    "docs/authority/taskpack-0912-r5/research-v15/方法数据.json":
        "084e013a6e8dca1da9db3569430d0f999bec81a81e7ea4c08fd24bfbf0d23911",
    "docs/authority/taskpack-0912-r5/research-v15/研究数据.json":
        "05b28103ac82dd531c8a669d0240b59efadd06679bba609aa50b7f26642df347",
    "docs/authority/taskpack-0912-r5/research-v15/资源数据.json":
        "4e95adebb9a275be790aa2b05f161a127faef27a661f4bf1dc41987031a8f9ef",
    "docs/history/aaos-appendix-sources-20261007/QODER_AAOS_RECOVERY_20261007/sources/AAOS_快速重构与多格式闭环_完整方案_20261004.md":
        "7ecda3e3f9d22834d65df663ba4f42a3ac62e31d215ab5e7c59c08bfaf08441e",
    "docs/history/aaos-appendix-sources-20261007/QODER_AAOS_RECOVERY_20261007/sources/AAOS_未来延展与可持续架构_完整方案_20261004.md":
        "771b189740e94dfeaf65e363b919745c2a69bb795d461e2b2fbcc9c95b15e1e1",
    "docs/history/aaos-appendix-sources-20261007/QODER_AAOS_RECOVERY_20261007/sources/CONTENT-COPY-V2.md":
        "7d475862fd307be46371ceeaead3407d6bbe939b429c37df1c28c4c6760fbeb2",
    "docs/history/aaos-appendix-sources-20261007/QODER_AAOS_RECOVERY_20261007/records/U01_2026-10-06_最新保存_证据_双学习规则_RECOVERED.md":
        "71219c25a1dd133f6aa3070f85b46f7918f420be6d64c1e84bef3375ec1669fe",
    "docs/history/aaos-appendix-sources-20261007/QODER_AAOS_RECOVERY_20261007/records/U02_2026-10-06_AAOS图谱_双链研究增量_RECOVERED.md":
        "a3d94956c5b2cc0a011943ba4b2dc6638bdbfc925211cfad60a843939005bc8f",
}

# Byte-exact inputs that intentionally exercise BOM, CRLF, missing-final-newline
# and non-UTF-8 worker behavior. A changed fixture must be reviewed and repinned;
# these are not general path exemptions.
_PRESERVED_FIXTURE_HASHES = {
    "frontend/src/__tests__/fixtures/ui-capability-details-original.json":
        "fc55ef3c996287f13bf6eb3711159ded1a228e2d27e928eb879d71dd24e4cf4f",
    "tests/fixtures/aaos-ui-mother/index.html":
        "1da1fe0d1feb55db98fba5e28cdbaf2e261e7ec4f562d3410cc9b7e74b3149f1",
    "tests/fixtures/f01-quality/controlled.md": "70aff728005d7580260391e6754f30209ec5fbecd9803f30a31e48d72eb7b176",
    "tests/fixtures/f01-quality/capped-lines.md": "71c0029230e042d72e9ec8db74f9a28196b37fdfb29f7df7d68e3b425af38928",
    "tests/fixtures/f01-quality/fallback-gbk.txt": "8ba7ed5cd0f33c11b7bb447337b0ce852b0a4f52c5ee854b6107943408b2b215",
    "tests/fixtures/p1-quality/bom-then-non-utf8.txt": "7b8e66f5da41888eb5cdd9ba9e142df708b548040f70aa7c6e417287ca4af188",
    "tests/fixtures/p1-quality/capped-crlf.txt": "9a9af8502c625be793d85c664d7b2c728dc5052b4f60b73e059416118c6a310a",
    "tests/fixtures/p1-quality/fallback-gbk-markdown.md": "8b593c1ffc2e113962d12485f54b381af29c4ae029b8c2e98c762d686138e6b7",
    "tests/fixtures/p1-quality/one-long-line.txt": "d9785ad494215a183ceaf55c11aeed1433227e88469f61159f2daf27e6929100",
}

# Byte-preserved members of the owner-supplied Sept29 historical package.
# Each exact member hash was checked against the preserved ZIP; this is not
# a directory exemption or permission to treat history as current authority.
_PRESERVED_PACKAGE_MEMBER_HASHES = {
    "docs/history/planning-blueprint-absorption/2026-09-29/package-unpacked/AAOS_完整历史规划蓝图吸收池与当前状态总报告_2026-09-29.docx":
        "d8ed1c2afdb92dcb87e6a5f7b6b46512af4e408ba0efe1cbe446f0d23bd9ca4f",
    "docs/history/planning-blueprint-absorption/2026-09-29/package-unpacked/AAOS_完整历史规划蓝图吸收池与当前状态总报告_2026-09-29.md":
        "3839646bb60b811c5cc1ab3417625a69e71b70f5983b6b24ec796a664fa28ffb",
    "docs/history/planning-blueprint-absorption/2026-09-29/package-unpacked/AAOS_CAPABILITY_ATLAS_CURRENT_MAPPING_2026-09-29.csv":
        "555b6463e6171783cb8aaa2374ca7f557c19cf7548136fdddf4dcce3a399dd68",
    "docs/history/planning-blueprint-absorption/2026-09-29/package-unpacked/AAOS_CODEX_DSH_HERMES_HANDOFF_2026-09-29.txt":
        "0c50f593d70d3927b83619084e242c84890bbc316302521851c4f5d89d25eb36",
    "docs/history/planning-blueprint-absorption/2026-09-29/package-unpacked/AAOS_CURRENT_CAPABILITY_ABSORPTION_11_2026-09-29.csv":
        "11c515ac6c5885d1fadd2f304c496d429b205a4b2cbdf88e036d6b373ea80733",
    "docs/history/planning-blueprint-absorption/2026-09-29/package-unpacked/AAOS_CURRENT_SUPPLY_CHAIN_47_2026-09-29.csv":
        "e70afc6bf2d7004f9d798c63bc1e4af4443135a921bf80bd69729488399c2376",
    "docs/history/planning-blueprint-absorption/2026-09-29/package-unpacked/AAOS_HISTORY_TO_CURRENT_MAPPING_2026-09-29.csv":
        "7cd147af95717f7c22672a21752f9ba7361fdd5c31abaaf5cfca3b510b52433c",
    "docs/history/planning-blueprint-absorption/2026-09-29/package-unpacked/AAOS_MASTER_ATLAS_2026-09-29.json":
        "7f58c4e033a88fd16b80c831085a25fd0042b2182b1047afe5d4ffcd86351d8c",
    "docs/history/planning-blueprint-absorption/2026-09-29/package-unpacked/AAOS_OSS_RESEARCH_POOL_369_2026-08-11.csv":
        "7a9e032739cefa6c8db1acc7be83a64d80740691409928c9eed2294565fb942f",
    "docs/history/planning-blueprint-absorption/2026-09-29/package-unpacked/AAOS_R6_M0_STATUS_2026-09-29.csv":
        "f010a587996cb704a66f8d29523e106811af9f88ec4ce24844cb3acfe8ede9d5",
    "docs/history/planning-blueprint-absorption/2026-09-29/package-unpacked/AAOS_REQUIREMENT_TRACE_2026-09-29.csv":
        "14d240b1234f886f770caa694afda8b76b54b8594605d5ac905b0ad07d30ce63",
    "docs/history/planning-blueprint-absorption/2026-09-29/package-unpacked/AAOS_SOURCE_BASELINE_97_2026-09-04.csv":
        "b278a5950e59bfc47bf924061f350c1bc061c56aeec8e94465cf3c423ba92e7f",
    "docs/history/planning-blueprint-absorption/2026-09-29/package-unpacked/README_文档包.md":
        "d22e4dc7425518202cee9425f0b203f0ec4dad0654febfedfeef52fb8aec7b08",
    "docs/history/planning-blueprint-absorption/2026-09-29/package-unpacked/SHA256SUMS.txt":
        "514a23a3bc2132fe7d04fa6751ab745f116f2001f52029cd3680fa2457879fd1",
}

# Owner-supplied Oct09/10 inputs and pre-repair snapshots: exact manifest
# hashes, including original BOM/CRLF and Markdown hard breaks. No wildcard.
_PRESERVED_PACKAGE_MEMBER_HASHES.update({
    'docs/history/authority-repair-20261010/AAOS-AGENT-HANDOFF-before-repair.md':
        '8291e3d85152e8d60f39d1f7c6bd7120c54a94e88f15531e7a36a51e60bc5d3d',
    'docs/history/authority-repair-20261010/SYSTEM_BOUNDARY-before-repair.md':
        '8567446c4a9e99e887f511b26f18a489e49314b965825eea3b8725fcda1ba1c7',
    'docs/history/conversation-summary-20261010/sources/AAOS_Conversation_Summary_20261010.md':
        '053e16b2b895c4d8549a90610c81cc95e8024e5648419bffbcb2a21949fac6d4',
    'docs/history/ui-design-increment-20261009/sources/zip-members/02_旧22页新入口与职责映射.csv':
        'fa372415464e8978b973a64d7f7268cc9bbe694cc90feac3d6d80a599cafc71c',
    'docs/history/ui-design-increment-20261009/sources/zip-members/03_核心操作流程.csv':
        '8e2fbaae24b3fdd9240cb6dda466e53fe8a1e3bd036b99e902af6a1936e10c68',
    'docs/history/ui-design-increment-20261009/sources/zip-members/04_公共组件状态规格.csv':
        '09311565c47c2f08fd9f5048b931e778bc65159682d240b13def28a7c2d93c69',
    'docs/history/ui-design-increment-20261009/sources/zip-members/05_按钮动作与真实接线清单.csv':
        '8aff9b2bc924b0e38ee70b5fcacde5a87de37d132ddd3d2b9ceb68d933ffd15b',
    'docs/history/ui-design-increment-20261009/sources/zip-members/06_成熟度验收场景.csv':
        '3a5458d8f5af3ef037f9e60aa2a08af204b54d8a45cd716a4c71e12430ae416d',
    'docs/taskpacks/aaos-ui-first-20261009/DESIGN-DETAIL-CROSSWALK.csv':
        '30be5090b0184b1de2e1da3cd53f0c18df7e8283cd9aec3b834b71ab70bce243',
    'docs/taskpacks/aaos-ui-first-20261009/OLD-TASK-DISPOSITION.csv':
        '88a31e57e6b24b8ee909ef31d3a626806a213be2ab0a096bdfe15858312de2b1',
    'docs/taskpacks/aaos-ui-first-20261009/ORIGINAL-CONTRACT-DEPENDENCIES.csv':
        '393fba675d732bf2ff04150a52bbe75258d069a6e8d9c19404edb7760272fe94',
    'docs/taskpacks/aaos-ui-first-20261009/PAGE-PLAN.csv':
        '4a56d60e33db3e0fe6843b88fad15cb88c3ad97e495703c4815bdf42578c7304',
    'docs/taskpacks/aaos-ui-first-20261009/REQUIREMENT-CROSSWALK.csv':
        'f1b0d6ff2659d4f1dead214049978c20f310426f782ac910840d65055125d835',
})

# This DP audit intentionally quotes a superseded product name as branch
# evidence. Pin the exact report bytes so it remains evidence, not a wildcard
# naming exemption.
_PRESERVED_HISTORICAL_REPORT_HASHES = {
    "docs/current/dsh-review/branch-batch-03.md": "def1136dd39c48db9a04cf149fccee2a6744d64a5053ef3ffb498b50eeb1d959",
    "docs/current/dsh-review/branch-batch-03.json": "1d3d6ba80319d4445c771f54802cb46c4c6ed74bdcd662338e74324078d6ff53",
}

# Generated branch/lineage audit receipts quote historical commit subjects and
# paths verbatim, so retired product names appear inside them by design. They
# are evidence, not present-day naming surfaces: rewriting them would falsify
# the audit. Recognised by their own schema identifier rather than by pinned
# per-file hashes, so a future receipt of the same class is covered too.
_AUDIT_RECEIPT_SCHEMA_PREFIXES = (
    "aaos-branch-commit-path-audit/",
    "aaos-branch-disposition-review/",
    "aaos-untracked-lineage-metadata/",
    "aaos-frozen-donor-hash-audit/",
    "aaos-history-path-disposition/",
    "aaos-local-repository-lineage-readback/",
)


def _is_audit_receipt(text: str) -> bool:
    head = text[:600]
    if '"schema_version"' not in head:
        return False
    return any(f'"{prefix}' in head for prefix in _AUDIT_RECEIPT_SCHEMA_PREFIXES)


@dataclass(frozen=True, order=True)
class ConventionIssue:
    code: str
    path: str
    detail: str


def _is_declared_binary(path: str, content: bytes) -> bool:
    return PurePosixPath(path).suffix.casefold() in _BINARY_SUFFIXES or b"\0" in content


def normalize_text_bytes(path: str, content: bytes) -> bytes:
    """Normalize a UTF-8 text file without changing words or path identity."""
    if _is_declared_binary(path, content):
        return content
    text = content.decode("utf-8-sig")
    text = unicodedata.normalize("NFC", text.replace("\r\n", "\n").replace("\r", "\n"))
    normalized = "\n".join(line.rstrip(" \t") for line in text.split("\n"))
    if normalized and not normalized.endswith("\n"):
        normalized += "\n"
    if PurePosixPath(path).suffix.casefold() in _WINDOWS_EOL_SUFFIXES:
        normalized = normalized.replace("\n", "\r\n")
    return normalized.encode("utf-8")


def scan_text_bytes(path: str, content: bytes) -> list[ConventionIssue]:
    """Return deterministic text-contract violations for one repository path."""
    frozen_hash = _FROZEN_ORIGINALS.get(path)
    if frozen_hash and hashlib.sha256(content).hexdigest() != frozen_hash:
        return [ConventionIssue("frozen-original-mismatch", path,
                                "preserved package bytes differ from the pinned original")]
    fixture_hash = (
        _PRESERVED_FIXTURE_HASHES.get(path)
        or _PRESERVED_PACKAGE_MEMBER_HASHES.get(path)
    )
    if fixture_hash:
        if hashlib.sha256(content).hexdigest() != fixture_hash:
            return [ConventionIssue(
                "preserved-fixture-mismatch",
                path,
                "byte-exact quality fixture differs from its pinned manifest bytes",
            )]
        return []
    if _is_declared_binary(path, content):
        return []
    try:
        text = content.decode("utf-8")
    except UnicodeDecodeError as exc:
        return [ConventionIssue("invalid-utf8", path, str(exc))]

    issues: list[ConventionIssue] = []
    if content.startswith(b"\xef\xbb\xbf"):
        issues.append(ConventionIssue("unexpected-bom", path, "UTF-8 BOM is prohibited"))
    windows_eol = PurePosixPath(path).suffix.casefold() in _WINDOWS_EOL_SUFFIXES
    invalid_carriage_return = (
        b"\r" in content.replace(b"\r\n", b"") if windows_eol else b"\r" in content
    )
    if invalid_carriage_return:
        issues.append(
            ConventionIssue(
                "crlf",
                path,
                "only Windows command files may use CRLF; lone CR is prohibited",
            )
        )
    if unicodedata.normalize("NFC", text) != text:
        issues.append(ConventionIssue("non-nfc-text", path, "text must be Unicode NFC"))
    body = text[1:] if text.startswith("\ufeff") else text
    if any(character in body for character in _ZERO_WIDTH) or "\ufeff" in body:
        issues.append(
            ConventionIssue(
                "zero-width-character",
                path,
                "prohibited invisible Unicode character",
            )
        )
    generated_no_lf = _GENERATED_NO_FINAL_LF.get(path) == hashlib.sha256(content).hexdigest()
    if content and not content.endswith(b"\n") and not frozen_hash and not generated_no_lf:
        issues.append(
            ConventionIssue("missing-final-newline", path, "text must end with LF")
        )
    if not frozen_hash and any(
        line.rstrip(" \t") != line for line in text.splitlines()
    ):
        issues.append(
            ConventionIssue("trailing-whitespace", path, "line ends with space or tab")
        )
    return sorted(issues)


def scan_naming_registry_bytes(path: str, content: bytes) -> list[ConventionIssue]:
    """Validate the naming registry schema and alias ownership."""
    try:
        payload = yaml.safe_load(content.decode("utf-8-sig"))
        if not isinstance(payload, dict):
            raise NamingRegistryError("naming registry root must be a mapping")
        NamingRegistry.from_mapping(payload)
    except (UnicodeDecodeError, yaml.YAMLError, NamingRegistryError) as exc:
        return [ConventionIssue("invalid-naming-registry", path, str(exc))]
    return []


def scan_path_set(paths: list[str]) -> list[ConventionIssue]:
    """Return cross-platform path and collision violations."""
    issues: list[ConventionIssue] = []
    folded: dict[str, list[str]] = defaultdict(list)
    for path in paths:
        normalized = unicodedata.normalize("NFC", path)
        if normalized != path:
            issues.append(ConventionIssue("non-nfc-path", path, f"use {normalized!r}"))
        folded[normalized.casefold()].append(path)
        for part in PurePosixPath(path).parts:
            base = part.rstrip(" .").split(".", 1)[0].casefold()
            if base in _RESERVED_WINDOWS_NAMES:
                issues.append(
                    ConventionIssue(
                        "windows-reserved-name",
                        path,
                        f"reserved Windows path component: {part!r}",
                    )
                )
            if part.endswith((" ", ".")) or re.search(r'[<>:"|?*]', part):
                issues.append(
                    ConventionIssue(
                        "windows-invalid-name",
                        path,
                        f"cross-platform-invalid path component: {part!r}",
                    )
                )
    for variants in folded.values():
        if len(variants) > 1:
            joined = ", ".join(sorted(variants))
            issues.append(
                ConventionIssue(
                    "case-path-collision",
                    sorted(variants)[0],
                    f"case-insensitive collision: {joined}",
                )
            )
    return sorted(issues)


def _read_git_blobs(root: Path, object_ids: list[str]) -> list[bytes]:
    """Read Git blobs in one process instead of spawning ``git show`` per file."""
    if not object_ids:
        return []
    result = subprocess.run(
        ["git", "cat-file", "--batch"],
        cwd=root,
        input="".join(f"{object_id}\n" for object_id in object_ids).encode("ascii"),
        capture_output=True,
        check=True,
    )
    output = result.stdout
    cursor = 0
    contents: list[bytes] = []
    for expected_object_id in object_ids:
        header_end = output.find(b"\n", cursor)
        if header_end < 0:
            raise RuntimeError("truncated git cat-file batch header")
        header = output[cursor:header_end].decode("ascii").split()
        if len(header) != 3 or header[1] != "blob":
            raise RuntimeError(f"expected Git blob {expected_object_id}, got: {' '.join(header)}")
        size = int(header[2])
        content_start = header_end + 1
        content_end = content_start + size
        if content_end >= len(output) or output[content_end : content_end + 1] != b"\n":
            raise RuntimeError(f"truncated git cat-file batch body for {expected_object_id}")
        contents.append(output[content_start:content_end])
        cursor = content_end + 1
    return contents


def _git_blob_entries(root: Path, source: str) -> list[tuple[str, str]]:
    if source == "head":
        command = ["git", "ls-tree", "-r", "-z", "HEAD"]
        raw_entries = subprocess.run(command, cwd=root, capture_output=True, check=True).stdout
        entries: list[tuple[str, str]] = []
        for record in raw_entries.split(b"\0")[:-1]:
            metadata, raw_path = record.split(b"\t", 1)
            _, object_type, object_id = metadata.decode("ascii").split()
            if object_type == "blob":
                entries.append((raw_path.decode("utf-8"), object_id))
        return entries

    raw_entries = subprocess.run(
        ["git", "ls-files", "-s", "-z"], cwd=root, capture_output=True, check=True
    ).stdout
    entries = []
    for record in raw_entries.split(b"\0")[:-1]:
        metadata, raw_path = record.split(b"\t", 1)
        _, object_id, stage = metadata.decode("ascii").split()
        if stage != "0":
            raise RuntimeError(f"index contains an unmerged path: {raw_path.decode('utf-8')}")
        entries.append((raw_path.decode("utf-8"), object_id))
    return entries


def scan_naming_forbidden_terms(path: str, content: bytes) -> list[ConventionIssue]:
    """AXW-1209: reject legacy product names outside Legacy/Migration context.

    Legacy product names (元枢工作台, ArcheAxis OS, ArcheAxis Workspace as a
    product name) are allowed only in files that explicitly declare historical /
    superseded / migration context or that are historical by nature (intake
    records, handoffs, third-party notices, status logs). Current product name
    is locked by docs/truth/NAMING_CONTRACT_V2.md (V1 superseded).

    Only active documentation surfaces are scanned: README, docs/current,
    docs/blueprint, docs/architecture, docs/decisions, docs/environment,
    docs/migration, docs/truth (newer files), config/, .worklab/.
    """
    pure = PurePosixPath(path)
    # Active product surfaces scanned for legacy product names: markdown
    # docs, YAML config, and JSON config. Python/Rust sources are excluded
    # because test fixtures deliberately embed forbidden names to assert
    # rejection logic.
    if pure.suffix.casefold() not in {".md", ".yaml", ".yml", ".txt", ".json", ".html"}:
        return []
    if pure.name in {"NAMING_CONTRACT_V1.md", "NAMING_CONTRACT_V2.md"}:
        return []
    # Historical-by-nature surfaces are exempt (they record the past).
    exempt_prefixes = (
        "workspace/intake/",
        "docs/architecture/imported-designs/",
        "docs/taskpacks/",
    )
    exempt_files = {
        "THIRD_PARTY_NOTICES.md",
        "docs/truth/EXECUTION_STATUS_LOG.md",
        "docs/truth/AUTHORITY_CONTRACT.md",
        "docs/truth/CURRENT_STATE_TRUTH.md",
        "docs/truth/README.md",
        "docs/README.md",
        "docs/NAMING_ALIGNMENT_MATRIX.md",
        "docs/HANDOFF_2026-08-07_stage-summary.md",
        "workspace/ui/archeaxis/README.md",
        "docs/architecture/imported-designs/reference-deliveries/archeaxis-2026/README.md",
    }
    active_prefixes = (
        "README.md",
        "docs/current/",
        "docs/blueprint/",
        "docs/architecture/",
        "docs/decisions/",
        "docs/environment/",
        "docs/migration/",
        "docs/truth/",
        "config/",
        "desktop/",
        ".worklab/",
    )
    if not path.startswith(active_prefixes):
        return []
    if path.startswith(exempt_prefixes) or path in exempt_files:
        return []
    historical_hash = _PRESERVED_HISTORICAL_REPORT_HASHES.get(path)
    if historical_hash:
        if hashlib.sha256(content).hexdigest() != historical_hash:
            return [ConventionIssue(
                "historical-report-mismatch",
                path,
                "historical branch-audit evidence changed from its pinned bytes",
            )]
        return []
    try:
        text = content.decode("utf-8-sig")
    except UnicodeDecodeError:
        return []
    head = text[:600].casefold()
    legacy_context = any(
        marker in head
        for marker in (
            "superseded",
            "legacy",
            "historical",
            "migration",
            "compatibility",
            "retired",
            "旧名",
            "历史",
            "仅历史",
            "暂不在维护",
        )
    )
    if legacy_context:
        return []
    # Generated audit receipts quote historical commits verbatim (see
    # _AUDIT_RECEIPT_SCHEMA_PREFIXES). They are evidence, not naming surfaces.
    if _is_audit_receipt(text):
        return []
    # 全文搜索的 retired/legacy 说明（如 SCOPE_LEDGER retired 条目、
    # EXTERNAL_DEPENDENCIES 的固定字段说明）同样视为合法历史语境。
    if "仅历史" in text or "暂不在维护" in text or "retired" in text.casefold():
        return []
    issues: list[ConventionIssue] = []
    # 元枢/元枢工作台 as an active product name is forbidden outside legacy docs
    for term, code in (
        ("元枢工作台", "legacy-product-name"),
        ("元枢系统", "legacy-product-name"),
        ("ArcheAxis OS", "legacy-product-name"),
        ("ArcheAxis Workspace", "legacy-product-name"),
    ):
        if term in text:
            issues.append(
                ConventionIssue(
                    code,
                    path,
                    f"legacy product name {term!r} outside Legacy/Migration context "
                    "(see docs/truth/NAMING_CONTRACT_V1.md)",
                )
            )
    return sorted(issues)


def scan_git_repository(root: Path, *, source: str = "worktree") -> list[ConventionIssue]:
    """Scan tracked paths from the worktree, index, or HEAD without mixing sources."""
    if source not in {"worktree", "index", "head"}:
        raise ValueError(f"unsupported Git source: {source!r}")

    blob_contents: dict[str, bytes] = {}
    if source == "worktree":
        raw_paths = subprocess.run(
            ["git", "ls-files", "-z"], cwd=root, capture_output=True, check=True
        ).stdout
        paths = raw_paths.decode("utf-8").split("\0")[:-1]
    else:
        entries = _git_blob_entries(root, source)
        paths = [path for path, _ in entries]
        contents = _read_git_blobs(root, [object_id for _, object_id in entries])
        blob_contents = dict(zip(paths, contents, strict=True))

    issues = scan_path_set(paths)
    for path in paths:
        if source == "worktree":
            candidate = root / Path(*PurePosixPath(path).parts)
            if not candidate.is_file():
                issues.append(
                    ConventionIssue(
                        "missing-worktree-file",
                        path,
                        "tracked path is absent from the worktree",
                    )
                )
                continue
            content = candidate.read_bytes()
        else:
            content = blob_contents[path]
        issues.extend(scan_text_bytes(path, content))
        issues.extend(scan_naming_forbidden_terms(path, content))
        if path == "config/naming-registry.yaml":
            issues.extend(scan_naming_registry_bytes(path, content))
    return sorted(issues)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("root", nargs="?", type=Path, default=Path.cwd())
    parser.add_argument(
        "--source",
        choices=("worktree", "index", "head"),
        default="worktree",
    )
    parser.add_argument("--format", choices=("text", "json"), default="text")
    args = parser.parse_args(argv)

    issues = scan_git_repository(args.root.resolve(), source=args.source)
    if args.format == "json":
        print(
            json.dumps(
                {
                    "source": args.source,
                    "issue_count": len(issues),
                    "issues": [asdict(issue) for issue in issues],
                },
                ensure_ascii=False,
                indent=2,
            )
        )
    elif issues:
        for issue in issues:
            print(f"{issue.path}: {issue.code}: {issue.detail}")
        print(f"repository convention check failed: {len(issues)} issue(s)")
    else:
        print(f"repository convention check passed ({args.source})")
    return 1 if issues else 0


if __name__ == "__main__":
    sys.exit(main())
